export class Menus {
    //APP_ID: number;
    //MENU_CODE: string;
    //MENU_SEQ_NO: number;
    //LAST_UPDATE_DATE: Date;
    //LAST_UPDATE_USER: string;
    //LAST_CLIENT_ADDRESS: string;
    //MENU_ID: string;
    //MENU_SUB_GROUP: string;
    //ENTERPRISE_SYSTEM: string;
    //MENU_NAME: string;
    //AUDIT: string;
    //PROFILE_ID: string;
    //USER_ID: string;
    //PASSHASH: string;
    //FIRST_NAME: string;
    //LAST_NAME: string;
    //MIDDLE_INITIAL: string;
    //EMAIL_ID: string;
    //PHONE1: string;
    //PHONE2: string;
    //FAX: string;
    //PAGER: string;
    //HINT_QUESTION: string;
    //HINT_ANSWER: string;
    //CREATE_USER_ID: string;
    //CREATE_DATE: Date;
    //LDAP_USER: string;
    //LDAP_ROLE: string;
    //LDAP_ORG: string;
    //USERDN: string;
    //CLIENT_USER: string;
    //SERVER_USER: string;
    //APP_NAME: string;
    //ROUTE: string;

    GROUP_ID: number;
    GROUP_NAME: string;
    APP_GROUP_SEQ_NO: number;
    APP_GROUP_IMAGE_PATH: string;
    APP_ID: number;
    APP_NAME: string;
    APP_IMAGE_PATH: string;
    SUB_MENU_GROUP_ID: number;
    SUB_MENU_GROUP_NAME: string;
    SUB_MENU_SEQ_NO: number;
    SUB_MENU_IMAGE_PATH: string;
    MENU_CODE: string;
    MENU_NAME: string;
    MENU_SEQ_NO: number;
    ROUTE: string;
    APP_FRIENDLYNAME: string;
    REPORT_ID: string;
    SUB_MENU_NAME: string;
    SUB_CATEGORY: string;
    IS_DIV: boolean = true;
    IS_MESSAGE: boolean = false;
}