--Single Procedure outliers yearly by procedure

-- Before running ---

-- Uncomment the INTO statement and run the entire procedure.

select SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD
--,COUNT(PROCEDURE_CODE) 
,COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES 
-- INTO SINGLE_PROC_CASES_Y
from [dbo].[RPT_CASE_DATA_12072017]
-- WHERE SERVICE_CODE = 'Cardiac' AND PROCEDURE_CODE= 'CTAODI' AND PHY_ID = 'SAMYS'
group by SERVICE_CODE, PROCEDURE_CODE, PHY_ID,
DATEPART(YYYY,[PERFORM_DATE]) 
--HAVING COUNT(DISTINCT(CASE_ID)) = 1
order by SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE])

---- VALIDATION FROM TABLE

--select DISTINCT(CASE_ID),SERVICE_CODE,PROCEDURE_CODE,PHY_ID,DATEPART(YYYY,[PERFORM_DATE]) PERIOD
-- from [dbo].[RPT_CASE_DATA_12072017]
--WHERE SERVICE_CODE = 'Cardiac' AND PROCEDURE_CODE= 'CTAODI' AND PHY_ID = 'SAMYS'

---- Update the Single Procedure outliers yearly by procedure

UPDATE RPT_CASE_DATA_12072017 SET SINGLE_PROC_OUTLIER_Y = 'Y' FROM SINGLE_PROC_CASES_Y
WHERE RPT_CASE_DATA_12072017.SERVICE_CODE = SINGLE_PROC_CASES_Y.SERVICE_CODE
AND RPT_CASE_DATA_12072017.PROCEDURE_CODE = SINGLE_PROC_CASES_Y.PROCEDURE_CODE
AND RPT_CASE_DATA_12072017.PHY_ID=SINGLE_PROC_CASES_Y.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_PROC_CASES_Y.PERIOD

