--Single Procedure outliers HALFYEARLY by procedure

-- Before running ---

-- Uncomment the INTO statement and run the entire procedure.

-- --HALFYEARLY BY PROC

select SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD,
IIF(DATEPART(MM,PERFORM_DATE)<= 6,1,2) [HYRLY]
--,COUNT(PROCEDURE_CODE) 
,COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES 
--INTO SINGLE_PROC_CASES_H
from [dbo].[RPT_CASE_DATA_12072017]
-- WHERE SERVICE_CODE = 'General' AND PROCEDURE_CODE= 'GNVEHERP' AND PHY_ID = 'NIGAMA'
group by SERVICE_CODE, PROCEDURE_CODE, PHY_ID,DATEPART(YYYY,[PERFORM_DATE]) , IIF(DATEPART(MM,PERFORM_DATE)<= 6,1,2) 
--HAVING COUNT(DISTINCT(CASE_ID)) = 1
order by SERVICE_CODE, PROCEDURE_CODE, PHY_ID ,DATEPART(YYYY,[PERFORM_DATE]),IIF(DATEPART(MM,PERFORM_DATE)<= 6,1,2)


-- VALIDATION FROM TABLE

-- General	GNVEHERP	NIGAMA	2016	2	1

--select DISTINCT(CASE_ID),SERVICE_CODE,PROCEDURE_CODE,PHY_ID,DATEPART(YYYY,[PERFORM_DATE]) PERIOD,
--IIF(DATEPART(MM,PERFORM_DATE)<= 6,1,2) [HYRLY]
-- from [dbo].[RPT_CASE_DATA_12072017]
--WHERE SERVICE_CODE = 'General' AND PROCEDURE_CODE= 'GNVEHERP' AND PHY_ID = 'NIGAMA'


---- Update the Single Procedure outliers HALFYEARLY by procedure

UPDATE RPT_CASE_DATA_12072017 SET SINGLE_PROC_OUTLIER_H = 'Y' FROM SINGLE_PROC_CASES_H
WHERE RPT_CASE_DATA_12072017.SERVICE_CODE = SINGLE_PROC_CASES_H.SERVICE_CODE
AND RPT_CASE_DATA_12072017.PROCEDURE_CODE = SINGLE_PROC_CASES_H.PROCEDURE_CODE
AND RPT_CASE_DATA_12072017.PHY_ID=SINGLE_PROC_CASES_H.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_PROC_CASES_H.PERIOD