--Single Procedure outliers MONTHLY by procedure

-- Before running ---

-- Uncomment the INTO statement and run the entire procedure.

-- --MONTHLY BY PROC

select SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD,
DATEPART(MM,[PERFORM_DATE]) MONTH,
--,COUNT(PROCEDURE_CODE) 
COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES 
--INTO SINGLE_PROC_CASES_M
from [dbo].[RPT_CASE_DATA_12072017]
--WHERE SERVICE_CODE = 'Cardiac' AND PROCEDURE_CODE= 'CTAAAAVR' AND PHY_ID = 'ZHANGL3'
group by SERVICE_CODE, PROCEDURE_CODE, PHY_ID,DATEPART(YYYY,[PERFORM_DATE]) , DATEPART(MM,[PERFORM_DATE])
--HAVING COUNT(DISTINCT(CASE_ID)) = 1
order by SERVICE_CODE, PROCEDURE_CODE, PHY_ID ,DATEPART(YYYY,[PERFORM_DATE]),DATEPART(MM,[PERFORM_DATE])


-- VALIDATION FROM TABLE

--- Cardiac	CTAAAAVR	ZHANGL3	2016	8	1

--select DISTINCT(CASE_ID),SERVICE_CODE,PROCEDURE_CODE,PHY_ID,DATEPART(YYYY,[PERFORM_DATE]) PERIOD,
--DATEPART(MM,[PERFORM_DATE]) MONTH
-- from [dbo].[RPT_CASE_DATA_12072017]
--WHERE SERVICE_CODE = 'Cardiac' AND PROCEDURE_CODE= 'CTAAAAVR' AND PHY_ID = 'ZHANGL3'

---- Update the Single Procedure outliers MONTHLY by procedure

UPDATE RPT_CASE_DATA_12072017 SET SINGLE_PROC_OUTLIER_M = 'Y' FROM SINGLE_PROC_CASES_M
WHERE RPT_CASE_DATA_12072017.SERVICE_CODE = SINGLE_PROC_CASES_M.SERVICE_CODE
AND RPT_CASE_DATA_12072017.PROCEDURE_CODE = SINGLE_PROC_CASES_M.PROCEDURE_CODE
AND RPT_CASE_DATA_12072017.PHY_ID=SINGLE_PROC_CASES_M.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_PROC_CASES_M.PERIOD