export class MT_POU_DEPT {
    public ORG_GROUP_ID: string;
    public DEPT_ID: string;
    public DEPT_NAME: string;
    public ATTN_TO: string;
    public ADDRESS1: string;
    public ADDRESS2: string;
    public CITY: string;
    public STATE: string;
    public ZIP: string;
    public COUNTRY: string;
    public PHONE: string;
    public FAX: string;
    public E_MAIL: string;
    public STATUS: boolean;
    public LAST_UPDATE_DATE?: Date;
    public LAST_UPDATE_USER: string;
    public LAST_CLIENT_ADDRESS: string;
    public EXCP_APPROVAL_REQ: string;
    public INV_COORD_EMAIL: string;
    public EXCP_APPROVER_EMAIL: string;
    public REMINDER_FREQ: number;
    public RECALL_NOTIFICATION_EMAIL: string;
    public INV_INTERFACE_ENABLE: string;
    public BILLING_ENABLE: string;
    public DEFAULT_PRINTER: string;
    public DEFAULT_DISTRIBUTION_TYPE: string;
    public DEFAULT_DESTINATION_LOCATION: string;
    public ALERT_NOTIFY_REQ: string;
    public EMAIL_NOTIFY: string;
    public CATEGORY_CODE: string;
    public BILLONLY_BUSINESS_UNIT: string;
    public BILLONLY_LOCATION: string;
    public NO_OF_CASES_DOWNLOAD: number =1;
    public SEND_LOWSTOCK_EMAIL_ALERTS: string;
    public EMAILID_FOR_LOWSTOCK_ALERTS: string;
    public SEND_PRODUCT_EXP_EMAIL_ALERTS: string;
    public EMAILID_FOR_PRODUCT_EXP_ALERTS: string;
    public DURATION_TRACKING_EXP: number = 0;
    public PERCENTAGE_OPTIMUM_QTY: number = 0;
    public PREPICK_QA_PROCESS_REQUIRED: boolean;
    public BUYER_ID: string;
    public AUTO_PUTAWAY_ENABLED: string;
    public ALLOW_LOC_SELECT: boolean = true;
    public STORAGE_AREA: string;
    public CASE_PICK_STATUS: string = "0";
    public AUTO_CASE_PICK: string;
    public AUTO_CASE_PICK_STATUS: boolean;
    public BILL_ONLY_CONSIGN_IMPLMENTED: boolean;
    public DEFAULT_IMPLANT_TYPE: string;
    //Local changes
    public ALERT_NOTIFY_REQ_STATUS: boolean = false;
    public EXCP_APPROVAL_REQ_STATUS: boolean = false;
    public INV_INTERFACE_ENABLE_STATUS: boolean = false;
    public BILLING_ENABLE_STATUS: boolean = false;
    public SEND_LOWSTOCK_EMAIL_ALERTS_STATUS: boolean = false;
    public SEND_PRODUCT_EXP_EMAIL_ALERTS_STATUS: boolean = false;
    public AUTO_PUTAWAY_ENABLED_STATUS: boolean = false;
}