export class PAR_MNGT_ORDER_DETAILS {
    public ORDER_NO: number;
    public LINE_NO: string;
    public ITEM_ID: string;
    public BIN_LOC: string;
    public QTY: any;
    public ORDER_STATUS?: string;
    public QTY_RCVD: any;
    public UOM: string;
    public SERIAL_NO: string;
    public LOT_NO: string;
    public TRANSACTION_ID?: number;
    public REQUISITION_NO: string;
    public LINE_COMMENTS: string;
    public ACTUAL_ORDERQTY?: number;
    public ACTUAL_ISSUE_UOM: string;
    public COUNT_QTY?: number;
    public QTY_PICKED: number;
    public NDC_CODE: string;
    public DESCRIPTION: string;
    public PRICE: string;
    public ITEM_PRICE: string;
    public txtqty: string;
    public txtRCDqty: string;
    public txtstatus: string;
    public prevTxtQty: string;
    public prevTxtRCDQty: string;
    public prevTxtStatus: string;
}