import { SelectItem } from './../components/common/api';

export class VM_MT_POU_CASE_CART_HEADER_TB {
    public CASE_ID: string;
    public PATIENT_ID: string;
    public DESCRIPTION: string;
    public PHYSICIAN: string;
    public PREF_LIST_ID: string;
    public STATUS: string;
    public UPDATE_DATE?: Date;
    public UPDATE_USER_ID: string;
    public CREATE_DATE?: Date;
    public CREATE_USER_ID: string;
    public ROOM_NO: string;
    public PERFORM_DATE: string;
    public PROCEDURE_CODE: string;
    public EMERGENCY_CASE: string;
    public MERGED_CASE_ID: string;
    public DEPT_ID: string;
    public PROCESSED_FILE_TYPE?: number;
    public COST_CENTER_CODE: string;
    public SERVICE_CODE: string;
    public CASE_DESC: string;
    public PHYSICIAN_NAME: string;
    public PROCEDURENAME: string;
    public PREFERENCENAME: string;
    public PATIENTNAME: string;
    public DEPTNAME: string;
    public SERVICENAME: string;
    public CHANGE_STATUS: string;
    public CHECKED: string;
    public REPLACE_CASE: string;
    public CURRENT_STATUS: string;
    public CHANGED_STATUS: string;
    public DETAILS: any[];
    public isExpander: boolean;
    public selectCase: boolean;
    public selectStatus: boolean;
    public statusData: any[];
    public repCaseData: any[];
    public statusValue: string;
    public repCaseValue: string;
    public selectPref: boolean;
    rowClsStyle: string = '';
    public cursor: string;
    public selectToggle: boolean;
    public qCaseId: string;
    public PATIENT_BARCODE: string;
}