export class VM_RECV_SENDLINEHEADER {
    public TRANSACTION_ID: number;
    public BUSINESS_UNIT: string;
    public PO_ID: string;
    public STORAGE_LOCATION: string;
    public LINE_NBR: number;
    public SCHED_NBR: number;
    public SCHED_COUNT: number;
    public INV_ITEM_ID: string;
    public ITM_ID_VNDR: string;
    public MFG_ITEM_ID: string;
    public DESCR: string;
    public INVENTORY_ITEM: string;
    public UPC_ID: string;
    public COMMENTS: string;
    public DUE_DT: string;
    public QTY?: number;
    public ASN_QTY?: number;
    public QTY_PO?: number;
    public LINE_QTY?: number;
    public LINE_PO_QTY?: number;
    public RECEIVED_QTY?: number;
    public LOCATION: string;
    public SHIPTO_ID: string;
    public CARRIER_ID: string;
    public UNIT_OF_MEASURE: string;
    public BILL_OF_LADING: string;
    public ASN_BILL_OF_LADING: string;
    public USER_ID: string;
    public DEVICE_DT_TIME: string;
    public NO_OF_BOXES: number;
    public INSP_FLAG: string;
    public QTY_RECV_TOL_PCT?: number;
    public DELIVER_TO: string;
    public REQ_LOC_DESC: string;
    public TRACKING_ID: string;
    public CUST_ITEM_NO: string;
    public RECEIVING_ROUTING_ID: string;
    public BIN_TRACK_FLAG: string;
    public ASSET_ITEM_FLAG: string;
    public EXT_TRK_NO: string;
    public QTY_UPDATE: string;
    public ISSUE_UOM: string;
    public CONVERSION_RATE?: number;
    public RECV_UOM: string;
    public RECV_CONVERSION_RATE?: number;
    public GTIN: string;
    public LOT_CONTROLLED: string;
    public SERIAL_CONTROLLED: string;
    public RECAL_FLAG: string;
    public ADDRESS1: string;
    public ADDRESS2: string;
    public ADDRESS3: string;
    public PHONE: string;
    public REQ_NUM: string;
    public PRICE?: number;
    public PACKAGING_STRING: string;
    public BUILDING: string;
    public FLOOR: string;
    public SECTOR: string;
    public REQUISITION_NAME: string;
    public BUYER_NAME: string;
    public LOC_DESCR: string;
    public ITEMID_DESC: string;
    public ALT_UOM: string;
    public OPENQTY?: number;
    public START_DT_TIME: string;
    public END_DT_TIME: string;
    public STATUS: number;
    public RECEIVED_FLAG: string;
    public RBFlAG: boolean = false;
    public DDLUOMS: any;
    public SELECTEDUOM: string;
    public LINE_ID: string;
    public PRVCARRIER_ID: string;
    public SCHDFLAG: boolean = false;
    public DDLUOMFLAG: boolean = false;
    public TXTQTYFLAG: boolean = false;
    public DESCR_TOOLTIP: string;
    public QTYDESABLEFLAG: boolean = false;
    public LOTSERIALSCHDFLAG: boolean = false;
    public SCHDQTYCHANGFLAG: boolean = false;
}