--By ICD:
-- delete from Item_details where [performdatewtime] is null

--SELECT ICD10,[ICD10 DESCRIPTION],* FROM [Item_details] WHERE ICD10='K8042'

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_ALL_PHYSICIANS_TAB2_Y')
BEGIN
drop table TEMP_ALL_PHYSICIANS_TAB2_Y
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_COUNT_TAB2_Y')
BEGIN
drop table TEMP_PHYSICIAN_COUNT_TAB2_Y
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB2_Y')
BEGIN
drop table TEMP_PHYSICIAN_AVERAGE_TAB2_Y
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC')
BEGIN
drop table TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC
END


--drop table TEMP_ALL_PHYSICIANS_TAB2_Y

--drop table TEMP_PHYSICIAN_COUNT_TAB2_Y

--drop table TEMP_PHYSICIAN_AVERAGE_TAB2_Y

--drop table TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC



-- DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y WHERE ICD_CODE=' '

--TEMP_ALL_PHYSICIANS_TAB2_Y TABLE:contains min max average usage among all physicians

SELECT SERVICE_CODE, ICD10, MIN(B.AVG_SPEND) MIN_AVG, MAX(B.AVG_SPEND) MAX_AVG, [YEAR] INTO TEMP_ALL_PHYSICIANS_TAB2_Y
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN, CASEID, 
SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND,  
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details] where ICD10 is not null AND ICD_OUTLIER_Y = 'N' 
			  --WHERE SERVICE_CODE='ORTHOPEDICS' AND ICD10 IS NOT NULL AND ICD10='M23.221'			 
GROUP BY SERVICE_CODE, ICD10, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, ICD10, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, ICD10, [YEAR]

-------------------------PHYSICIAN COUNT--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS, SERVICE_CODE, ICD10, DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP_PHYSICIAN_COUNT_TAB2_Y
FROM [Item_details] where ICD10 is not null	AND ICD_OUTLIER_Y = 'N'
--WHERE SERVICE_CODE = 'GYNECOLOGY' AND ICD10='C54.1'
GROUP BY  SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], DATEPART(YYYY,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB2_Y TABLE:contains min max average usage by physician

SELECT C.SERVICE_CODE, PHYSICIAN, ICD10, [ICD10 DESCRIPTION], [YEAR], COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, 
		SUM(TOTAL_SPEND) TOTAL_SPEND, MIN(TOTAL_SPEND) MIN_SPEND, AVG(TOTAL_SPEND) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND 
		INTO TEMP_PHYSICIAN_AVERAGE_TAB2_Y
FROM (SELECT SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, CASEID, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details] where ICD10 is not null AND ICD_OUTLIER_Y = 'N'
			-- WHERE SERVICE_CODE='ORTHOPEDICS' AND ICD10 IS NOT NULL AND ICD10='M23.221'		 
GROUP BY  SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN,  CASEID,  DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN,  [YEAR]

--select * from TEMP_PHYSICIAN_AVERAGE_TAB2_Y WHERE SERVICE_CODE='ORTHOPEDICS' AND ICD10 IS NOT NULL AND ICD10='M23.221'		

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Y ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Y ADD NO_OF_PHYSICIANS INT

--------------

UPDATE TEMP_PHYSICIAN_AVERAGE_TAB2_Y 
SET TEMP_PHYSICIAN_AVERAGE_TAB2_Y.[VARIANCE] = ROUND(TEMP_PHYSICIAN_AVERAGE_TAB2_Y.AVG_SPEND - TEMP_ALL_PHYSICIANS_TAB2_Y.MIN_AVG,2) * (TEMP_PHYSICIAN_AVERAGE_TAB2_Y.NO_OF_PROCEDURES),
NO_OF_PHYSICIANS = TEMP_PHYSICIAN_COUNT_TAB2_Y.NO_OF_PHYSICIANS
--SELECT 
--ROUND(TEMP_PHYSICIAN_AVERAGE_TAB2_Y.AVG_SPEND,2) - ROUND(TEMP_ALL_PHYSICIANS_TAB2_Y.MIN_AVG,2) VARIANCE, TEMP_PHYSICIAN_AVERAGE_TAB2_Y.NO_OF_PROCEDURES,
--(ROUND(TEMP_PHYSICIAN_AVERAGE_TAB2_Y.AVG_SPEND,2) - ROUND(TEMP_ALL_PHYSICIANS_TAB2_Y.MIN_AVG,2) ) * (TEMP_PHYSICIAN_AVERAGE_TAB2_Y.NO_OF_PROCEDURES) TOTAL_VARIANCE,
--TEMP_PHYSICIAN_AVERAGE_TAB2_Y.AVG_SPEND, TEMP_ALL_PHYSICIANS_TAB2_Y.MIN_AVG
FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Y,TEMP_ALL_PHYSICIANS_TAB2_Y ,TEMP_PHYSICIAN_COUNT_TAB2_Y
WHERE TEMP_ALL_PHYSICIANS_TAB2_Y.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB2_Y.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y.ICD10 = TEMP_ALL_PHYSICIANS_TAB2_Y.ICD10
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y.[YEAR] = TEMP_ALL_PHYSICIANS_TAB2_Y.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y.[YEAR] = TEMP_PHYSICIAN_COUNT_TAB2_Y.[YEAR]
AND TEMP_PHYSICIAN_COUNT_TAB2_Y.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB2_Y.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y.ICD10 = TEMP_PHYSICIAN_COUNT_TAB2_Y.ICD10
AND TEMP_PHYSICIAN_COUNT_TAB2_Y.SERVICE_CODE=TEMP_ALL_PHYSICIANS_TAB2_Y.SERVICE_CODE 
--and TEMP_PHYSICIAN_AVERAGE_TAB2_Y.SERVICE_CODE='ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y.ICD10 IS NOT NULL 
--AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y.ICD10='M17.12'

--BY YEAR

--DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y WHERE [DIAGNOSIS_CODE_TYPE]=1 
--(ROWS: 4355)
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y
 ([SPECIALTY_CODE]
 ,[SPECIALTY_DESCRIPTION]
,[DIAGNOSIS_CODE],[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[NO_OF_PHYSICIANS]
,[NO_OF_PROCEDURES]
,[MAX_USAGE]
,[MIN_USAGE]
,[TOTAL_VARIANCE]
,[TOTAL_SPEND]
,[TOTAL_ANNUAL_SPEND]
,[PERCENTAGE_VAR_OVER_SPEND]
,[YEAR])
SELECT SERVICE_CODE, SERVICE_CODE,  
--ISNULL(ICD10, ' ') ICD10,' ' [CPT_CODE], ISNULL(ICD10, ' ') PROCEDURE_CODE, ISNULL([ICD10 DESCRIPTION], ' '), 
ISNULL(ICD10, ' ') ICD10, ISNULL([ICD10 DESCRIPTION], ' '),
1 AS 'DIAGNOSIS_CODE_TYPE', 
AVG(ISNULL(NO_OF_PHYSICIANS,0)) NO_OF_PHYSICIANS, SUM(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES, MAX(ISNULL(AVG_SPEND,0)) MAX_SPEND,
MIN(ISNULL(AVG_SPEND,0)) MIN_SPEND, SUM(ISNULL([VARIANCE],0)) [VARIANCE], 
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND, ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND_ANNUAL,
(([TOTAL_VARIANCE]/[TOTAL_SPEND]) * 100) [PERCENTAGE_VAR_OVER_SPEND],
[YEAR] FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Y
--WHERE SERVICE_CODE = 'GYNECOLOGY' AND ICD10='C54.1'
--WHERE SERVICE_CODE = 'ORTHOPEDICS' AND ICD10='M17.12'
GROUP BY [YEAR], SERVICE_CODE, ICD10, [ICD10 DESCRIPTION]






------------------By PROCEDURE----------------------------------------------------------------------------------------------


IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC')
BEGIN
drop table TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_ALL_PHYSICIANS_TAB2_Y_PROC')
BEGIN
drop table TEMP_ALL_PHYSICIANS_TAB2_Y_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC')
BEGIN
drop table TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC')
BEGIN
drop table TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC
END



--DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC
--DROP TABLE TEMP_ALL_PHYSICIANS_TAB2_Y_PROC
--DROP TABLE TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC
--DROP TABLE TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC

--  DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y
--  DROP TABLE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y


--populating ICD description and procedure code,procedure description with ICD code and ICD description

ALTER TABLE [Item_details]
ALTER COLUMN [PROCEDURE_CODE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

--TEMP_ALL_PHYSICIANS_TAB2_Y_PROC TABLE:contains min max average usage among all physicians

--select * from [Item_details]

SELECT SERVICE_CODE, PROCEDURE_CODE, MIN(B.AVG_SPEND) MIN_AVG, MAX(B.AVG_SPEND) MAX_AVG, [YEAR] 
INTO TEMP_ALL_PHYSICIANS_TAB2_Y_PROC
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details] WHERE PROC_OUTLIER_Y = 'N'
			  --WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='M23.221'			 
GROUP BY SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, PROCEDURE_CODE, [YEAR]

-------------------------PHYSICIAN COUNT--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS, SERVICE_CODE, PROCEDURE_CODE, DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC
FROM [Item_details]	WHERE PROC_OUTLIER_Y = 'N'
--WHERE SERVICE_CODE = 'GYNECOLOGY' AND PROCEDURE_CODE='C54.1'
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, DATEPART(YYYY,[performdatewtime])

-------------------------PHYSICIAN COUNT(SUMMARY)--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS, SERVICE_CODE,  DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC
FROM [Item_details]	WHERE PROC_OUTLIER_Y = 'N'
--WHERE SERVICE_CODE = 'GYNECOLOGY' AND PROCEDURE_CODE='C54.1'
GROUP BY  SERVICE_CODE, DATEPART(YYYY,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC TABLE:contains min max average usage by physician

SELECT C.SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE, proc_descr, [YEAR], COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, 
		SUM(TOTAL_SPEND) TOTAL_SPEND, MIN(TOTAL_SPEND) MIN_SPEND, AVG(TOTAL_SPEND) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND 
		INTO TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, CASEID, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND,  
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details] WHERE PROC_OUTLIER_Y = 'N'
			--WHERE SERVICE_CODE='GYNECOLOGY' --AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='M23.221'		 
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN,  CASEID,  DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN,  [YEAR]

--select * from TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='M23.221'		

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC ADD NO_OF_PHYSICIANS INT

--------------

UPDATE TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC 
SET TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.[VARIANCE] = ROUND(TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.AVG_SPEND - TEMP_ALL_PHYSICIANS_TAB2_Y_PROC.MIN_AVG,2) * (TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.NO_OF_PROCEDURES),
NO_OF_PHYSICIANS = TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC.NO_OF_PHYSICIANS
--SELECT 
--ROUND(TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.AVG_SPEND,2) - ROUND(TEMP_ALL_PHYSICIANS_TAB2_Y_PROC.MIN_AVG,2) VARIANCE, TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.NO_OF_PROCEDURES,
--(ROUND(TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.AVG_SPEND,2) - ROUND(TEMP_ALL_PHYSICIANS_TAB2_Y_PROC.MIN_AVG,2) ) * (TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.NO_OF_PROCEDURES) TOTAL_VARIANCE,
--TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.AVG_SPEND, TEMP_ALL_PHYSICIANS_TAB2_Y_PROC.MIN_AVG
FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC,TEMP_ALL_PHYSICIANS_TAB2_Y_PROC ,TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC
WHERE TEMP_ALL_PHYSICIANS_TAB2_Y_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.PROCEDURE_CODE = TEMP_ALL_PHYSICIANS_TAB2_Y_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.[YEAR] = TEMP_ALL_PHYSICIANS_TAB2_Y_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.[YEAR] = TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC.[YEAR]
AND TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.PROCEDURE_CODE = TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_COUNT_TAB2_Y_PROC.SERVICE_CODE=TEMP_ALL_PHYSICIANS_TAB2_Y_PROC.SERVICE_CODE 
--and TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.SERVICE_CODE='ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.PROCEDURE_CODE IS NOT NULL 
--AND TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC.PROCEDURE_CODE='M17.12'

--BY YEAR

DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y where [DIAGNOSIS_CODE_TYPE]=3 
--(ROWS: 1110)
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y
 ([SPECIALTY_CODE]
 ,[SPECIALTY_DESCRIPTION]
,[DIAGNOSIS_CODE],[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[NO_OF_PHYSICIANS]
,[NO_OF_PROCEDURES]
,[MAX_USAGE]
,[MIN_USAGE]
,[TOTAL_VARIANCE]
,[TOTAL_SPEND]
,[TOTAL_ANNUAL_SPEND]
,[PERCENTAGE_VAR_OVER_SPEND]
,[YEAR])
SELECT SERVICE_CODE, SERVICE_CODE,  
--ISNULL(ICD10, ' ') ICD10,' ' [CPT_CODE], 
ISNULL(PROCEDURE_CODE, ' ') PROCEDURE_CODE, '',
--ISNULL([ICD10 DESCRIPTION], ' '), 
--ISNULL(ICD10, ' ') ICD10, ISNULL([ICD10 DESCRIPTION], ' '),
3 AS 'DIAGNOSIS_CODE_TYPE', 
AVG(ISNULL(NO_OF_PHYSICIANS,0)) NO_OF_PHYSICIANS, SUM(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES, MAX(ISNULL(AVG_SPEND,0)) MAX_SPEND,
MIN(ISNULL(AVG_SPEND,0)) MIN_SPEND, SUM(ISNULL([VARIANCE],0)) [VARIANCE], 
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND, ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND_ANNUAL,
(([TOTAL_VARIANCE]/[TOTAL_SPEND]) * 100) [PERCENTAGE_VAR_OVER_SPEND],
[YEAR] FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Y_PROC
--WHERE SERVICE_CODE = 'GYNECOLOGY' AND ICD10='C54.1'
--WHERE SERVICE_CODE = 'ORTHOPEDICS' AND ICD10='M17.12'
GROUP BY [YEAR], SERVICE_CODE, PROCEDURE_CODE
--[ICD10 DESCRIPTION]
------------------------------------------------------------------------------------------
	--SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y
	--ALTER TABLE SPECIALTY_MASTER
	--ALTER COLUMN SPECIALTY [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

--select * from ATPAR_MT.MT_RPT_POU_PROCEDURE_PREF_DATA

UPDATE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y SET [SPECIALTY_DESCRIPTION]=ATPAR_MT.MT_RPT_POU_PROCEDURE_PREF_DATA.SC_DESCRIPTION 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y,ATPAR_MT.MT_RPT_POU_PROCEDURE_PREF_DATA
WHERE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.SPECIALTY_CODE=ATPAR_MT.MT_RPT_POU_PROCEDURE_PREF_DATA.SPECIALTY_CODE


UPDATE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y 
SET DIAGNOSIS_DESCRIPTION = ATPAR_MT.MT_RPT_POU_PROCEDURE_PREF_DATA.PC_DESCRIPTION
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y,ATPAR_MT.MT_RPT_POU_PROCEDURE_PREF_DATA
WHERE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.[DIAGNOSIS_CODE]=ATPAR_MT.MT_RPT_POU_PROCEDURE_PREF_DATA.PROCEDURE_ID
AND (MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.DIAGNOSIS_DESCRIPTION IS NULL OR MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.DIAGNOSIS_DESCRIPTION = ''
OR MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.DIAGNOSIS_DESCRIPTION=' ')


UPDATE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y 
SET DIAGNOSIS_DESCRIPTION = ATPAR_MT.MT_POU_PROCEDURE_CODE.DESCRIPTION
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y,ATPAR_MT.MT_POU_PROCEDURE_CODE
WHERE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.[DIAGNOSIS_CODE]=ATPAR_MT.MT_POU_PROCEDURE_CODE.PROCEDURE_CODE
AND (MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.DIAGNOSIS_DESCRIPTION IS NULL OR MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.DIAGNOSIS_DESCRIPTION = ''
OR MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.DIAGNOSIS_DESCRIPTION=' ')


update MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y set DIAGNOSIS_DESCRIPTION=[DIAGNOSIS_CODE] 
where DIAGNOSIS_DESCRIPTION='' OR DIAGNOSIS_DESCRIPTION=' ' OR DIAGNOSIS_DESCRIPTION IS NULL

--658554.55

update MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y set SPECIALTY_CODE='OTHERS' 
where SPECIALTY_CODE='' OR SPECIALTY_CODE=' ' OR SPECIALTY_CODE IS NULL

update MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y set SPECIALTY_DESCRIPTION='Others'
where SPECIALTY_DESCRIPTION='' OR SPECIALTY_DESCRIPTION=' ' OR SPECIALTY_DESCRIPTION IS NULL




