--By ICD
DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y WHERE DIAGNOSIS_CODE_TYPE = 1

------------------COST VARIANCE BY SPECIALTY---------------------------

--DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y WHERE DIAGNOSIS_CODE_TYPE=1
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y
		    ([SPECIALTY_CODE]
           ,[SPECIALTY_DESCRIPTION]
           ,[NO_OF_PROCEDURES]
           ,[NO_OF_PHYSICIANS]
           ,[TOTAL_SPEND]
           ,[TOTAL_VARIANCE]
		   ,[PERCENTAGE_VAR_OVER_SPEND]
		   ,[DIAGNOSIS_CODE_TYPE]
           ,[YEAR])
SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION, SUM(NO_OF_PROCEDURES), SUM(NO_OF_PHYSICIANS) , SUM([TOTAL_SPEND]), SUM([TOTAL_VARIANCE]), 
(([TOTAL_VARIANCE]/[TOTAL_SPEND]) * 100) [PERCENTAGE_VAR_OVER_SPEND],
DIAGNOSIS_CODE_TYPE,[YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y WHERE DIAGNOSIS_CODE_TYPE=1
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION,DIAGNOSIS_CODE_TYPE,[YEAR]




------------------By PROCEDURE-------------------------------------------------------------------------------

DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y WHERE [DIAGNOSIS_CODE_TYPE]=3
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y
	([SPECIALTY_CODE]
	,[SPECIALTY_DESCRIPTION]
	,[NO_OF_PROCEDURES]
	,[NO_OF_PHYSICIANS]
	,[TOTAL_SPEND]
	,[TOTAL_VARIANCE]
	,[PERCENTAGE_VAR_OVER_SPEND]
	,[DIAGNOSIS_CODE_TYPE]
	,[YEAR])
SELECT SPECIALTY_CODE,
SPECIALTY_DESCRIPTION, 
SUM(NO_OF_PROCEDURES), 
AVG(TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC.NO_OF_PHYSICIANS) , 
SUM([TOTAL_SPEND]), 
SUM([TOTAL_VARIANCE]), 
(([TOTAL_VARIANCE]/[TOTAL_SPEND]) * 100) [PERCENTAGE_VAR_OVER_SPEND],
DIAGNOSIS_CODE_TYPE, 
MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.[YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y,TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC
WHERE DIAGNOSIS_CODE_TYPE = 3
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.SPECIALTY_CODE= TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC.SERVICE_CODE
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.[YEAR]= TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC.[YEAR] 
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION, DIAGNOSIS_CODE_TYPE,MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.[YEAR]

update MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y set SPECIALTY_CODE='OTHERS' 
where SPECIALTY_CODE='' OR SPECIALTY_CODE=' ' OR SPECIALTY_CODE IS NULL

update MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y set SPECIALTY_DESCRIPTION='Others' 
where SPECIALTY_DESCRIPTION='' OR SPECIALTY_DESCRIPTION=' ' OR SPECIALTY_DESCRIPTION IS NULL






