--By ICD:

--DELETE FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y WHERE DIAGNOSIS_CODE_TYPE = 1


--TEMP_TAB3_Y_ICD TABLE:contains min max average usage among all physicians

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_TAB3_Y_ICD')
BEGIN
drop table TEMP_TAB3_Y_ICD
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP1_TAB3_Y_ICD')
BEGIN
drop table TEMP1_TAB3_Y_ICD
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD')
BEGIN
drop table TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD
END

------------------------------------------------------------------------------------------------

SELECT  B.SERVICE_CODE , B.ICD10, MIN(AVG_SPEND) MIN_AVG, MAX(AVG_SPEND) MAX_AVG, 
[YEAR] INTO TEMP_TAB3_Y_ICD
FROM (SELECT C.SERVICE_CODE, C.ICD10,  C.PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN,CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details] where ICD10 is not null  AND ICD_OUTLIER_Y = 'N'
			  --WHERE SERVICE_CODE = 'ORTHOPEDICS' AND ICD10 IN ('C79.51')
			  --WHERE SERVICE_CODE = 'ORTHOPEDICS' AND ICD10='M17.12'
			  --WHERE ICD10='C54.1' AND SERVICE_CODE='GYNECOLOGY' 
GROUP BY  SERVICE_CODE, ICD10, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY  SERVICE_CODE, ICD10, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, ICD10, [YEAR]

-------------------------PHYSICIAN COUNT--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS_DEPT, 
COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES_DEPT,
SERVICE_CODE, ICD10, DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP1_TAB3_Y_ICD
FROM [Item_details] where ICD10 is not null AND ICD_OUTLIER_Y = 'N'
GROUP BY  SERVICE_CODE, ICD10,
DATEPART(YYYY,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD TABLE:contains min max average usage by physician

SELECT C.SERVICE_CODE, PHYSICIAN, SURGE_DESCIPTION_orig, ICD10, [ICD10 DESCRIPTION], COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SUM(TOTAL_SPEND) TOTAL_SPEND,
	   MIN(TOTAL_SPEND) MIN_SPEND, AVG(ISNULL(TOTAL_SPEND,0)) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND, [YEAR] 
	   INTO TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD
FROM (SELECT SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, SURGE_DESCIPTION_orig , CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR] 
			 FROM [Item_details] where ICD10 is not null AND ICD_OUTLIER_Y = 'N'
			 --WHERE SERVICE_CODE='GYNECOLOGY' 
GROUP BY SERVICE_CODE, ICD10,[ICD10 DESCRIPTION], PHYSICIAN,SURGE_DESCIPTION_orig, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PHYSICIAN,SURGE_DESCIPTION_orig, ICD10,[ICD10 DESCRIPTION], [YEAR]


ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD ADD NO_OF_PHYSICIANS_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD ADD NO_OF_PROCEDURES_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD ADD [PER_VAR_TOTAL_SPEND] FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD ADD [LOW_COST_AVG_DEPT] FLOAT


UPDATE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD 
SET TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.VARIANCE = ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.AVG_SPEND - TEMP_TAB3_Y_ICD.MIN_AVG),2),
TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.[PER_VAR_TOTAL_SPEND] = CASE WHEN ISNULL(TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.TOTAL_SPEND,0) > 0 THEN (ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.AVG_SPEND - TEMP_TAB3_Y_ICD.MIN_AVG),2) / TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.TOTAL_SPEND) * 100 ELSE 0 END ,
NO_OF_PHYSICIANS_DEPT = TEMP1_TAB3_Y_ICD.NO_OF_PHYSICIANS_DEPT,
NO_OF_PROCEDURES_DEPT = TEMP1_TAB3_Y_ICD.NO_OF_PROCEDURES_DEPT,
[LOW_COST_AVG_DEPT] = TEMP_TAB3_Y_ICD.MIN_AVG
--SELECT ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.AVG_SPEND - TEMP_TAB3_Y_ICD.MIN_AVG),2) VARIANCE , TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.AVG_SPEND , TEMP_TAB3_Y_ICD.MIN_AVG
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD,TEMP_TAB3_Y_ICD,TEMP1_TAB3_Y_ICD
WHERE TEMP_TAB3_Y_ICD.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.[YEAR] = TEMP_TAB3_Y_ICD.[YEAR]
--AND TEMP1_TAB3_Y_ICD.[YEAR] = TEMP_TAB3_Y_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.[YEAR] = TEMP1_TAB3_Y_ICD.[YEAR]
AND TEMP1_TAB3_Y_ICD.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.ICD10 = TEMP1_TAB3_Y_ICD.ICD10
AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.ICD10 = TEMP_TAB3_Y_ICD.ICD10
AND TEMP1_TAB3_Y_ICD.SERVICE_CODE=TEMP_TAB3_Y_ICD.SERVICE_CODE 
--AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.SERVICE_CODE = 'ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD.ICD10='M17.12'

---INSERT INTO MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON
-- SELECT *  FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y WHERE [DIAGNOSIS_CODE_TYPE] =1  (3846)
--BY YEAR

-- WHERE [DIAGNOSIS_CODE_TYPE] =1
INSERT INTO MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[NO_OF_PROCEDURES]
,[MIN_PROC_COST]
,[MAX_PROC_COST]
,[AVG_PROC_COST]
,[TOTAL_SPEND]
,[PER_VAR_TOTAL_SPEND]
,[PHYSICIAN_RANK]
,[NO_OF_PHY_DEPT]
,[NO_OF_PROCS_DEPT]
,[LOW_COST_AVG_DEPT]
,[MIN_PROC_VARIANCE]
,[EXTENDED_VARIANCE]
,[YEAR])
SELECT SERVICE_CODE, ISNULL(ICD10, ' '),
--' ', ISNULL(ICD10, ' ') ICD10,
ISNULL(PHYSICIAN,' ') PHYSICIAN, '' PHYSICIAN_NAME , ISNULL([ICD10 DESCRIPTION], ' '),
1 AS 'DIAGNOSIS_CODE_TYPE', 
--ISNULL([ICD10 DESCRIPTION], ' '),' ', 
AVG(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  MIN(ISNULL(MIN_SPEND,0)) MIN_SPEND, MAX(ISNULL(MAX_SPEND,0)) MAX_SPEND, AVG(ISNULL(AVG_SPEND,0)) AVG_SPEND,
ISNULL(SUM(TOTAL_SPEND),0) TOTAL_SPEND, 
SUM([PER_VAR_TOTAL_SPEND]) [PER_VAR_TOTAL_SPEND],
0,
AVG(NO_OF_PHYSICIANS_DEPT) NO_OF_PHYSICIANS_DEPT,
AVG(NO_OF_PROCEDURES_DEPT) NO_OF_PROCEDURES_DEPT,
AVG([LOW_COST_AVG_DEPT]) [LOW_COST_AVG_DEPT],
ROUND(SUM([VARIANCE]),2) [VARIANCE],
ROUND((SUM(ISNULL(NO_OF_PROCEDURES,0)) * SUM([VARIANCE])),2) [EXTENDED_VARIANCE],
[YEAR] FROM TEMP_PHYSICIAN_AVERAGE_TAB3_Y_ICD
--WHERE ICD10='I21.09' AND SERVICE_CODE='CARDIOTHORACIC' AND PHYSICIAN='SAMYS'
--WHERE SERVICE_CODE = 'ORTHOPEDICS' AND ICD10='M17.12'
GROUP BY SERVICE_CODE,ICD10,[ICD10 DESCRIPTION],[YEAR], PHYSICIAN


UPDATE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y SET [PHYSICIAN_NAME] = ISNULL([Item_details].SURGE_DESCIPTION_orig,'') 
FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y,[Item_details]
WHERE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.PHYSICIAN_ID=[Item_details].PHYSICIAN AND ICD_OUTLIER_Y = 'N'


ALTER TABLE [Item_details]
ALTER COLUMN PHYSICIAN [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

-------------By Procedure:---------------------------------------------------------------------



	--TEMP_TAB3_Y_PROC TABLE:contains min max average usage among all physicians

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_TAB3_Y_PROC')
BEGIN
drop table TEMP_TAB3_Y_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP1_TAB3_Y_PROC')
BEGIN
drop table TEMP1_TAB3_Y_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC')
BEGIN
drop table TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC
END

SELECT  B.SERVICE_CODE , B.PROCEDURE_CODE, MIN(AVG_SPEND) MIN_AVG, MAX(AVG_SPEND) MAX_AVG, 
[YEAR] INTO TEMP_TAB3_Y_PROC
FROM (SELECT C.SERVICE_CODE, C.PROCEDURE_CODE,  C.PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN,CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details] 
			  WHERE PROC_OUTLIER_Y = 'N'
			  --WHERE SERVICE_CODE = 'ORTHOPEDICS' AND PROCEDURE_CODE IN ('C79.51')
			  --WHERE SERVICE_CODE = 'ORTHOPEDICS' AND PROCEDURE_CODE='M17.12'
			  --WHERE PROCEDURE_CODE='C54.1' AND SERVICE_CODE='GYNECOLOGY' 
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, PROCEDURE_CODE, [YEAR]

-------------------------PHYSICIAN COUNT--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS_DEPT, 
COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES_DEPT,
SERVICE_CODE, PROCEDURE_CODE, DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP1_TAB3_Y_PROC
FROM [Item_details] WHERE PROC_OUTLIER_Y = 'N'
GROUP BY  SERVICE_CODE, PROCEDURE_CODE,
DATEPART(YYYY,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC TABLE:contains min max average usage by physician

SELECT C.SERVICE_CODE, PHYSICIAN, SURGE_DESCIPTION_orig, PROCEDURE_CODE, proc_descr, COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SUM(TOTAL_SPEND) TOTAL_SPEND,
	   MIN(TOTAL_SPEND) MIN_SPEND, AVG(ISNULL(TOTAL_SPEND,0)) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND, [YEAR] 
	   INTO TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, SURGE_DESCIPTION_orig , CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR] 
			 FROM [Item_details]
			 WHERE PROC_OUTLIER_Y = 'N'
			 --WHERE SERVICE_CODE='GYNECOLOGY' 
GROUP BY SERVICE_CODE, PROCEDURE_CODE,proc_descr, PHYSICIAN,SURGE_DESCIPTION_orig, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PHYSICIAN,SURGE_DESCIPTION_orig, PROCEDURE_CODE,proc_descr, [YEAR]

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC ADD NO_OF_PHYSICIANS_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC ADD NO_OF_PROCEDURES_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC ADD [PER_VAR_TOTAL_SPEND] FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC ADD [LOW_COST_AVG_DEPT] FLOAT

--SET TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.MIN_AVG_ALL_PHYSICIANS = TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.AVG_SPEND - TEMP_TAB3_Y_PROC.MIN_AVG,

UPDATE TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC 
SET TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.VARIANCE = ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.AVG_SPEND - TEMP_TAB3_Y_PROC.MIN_AVG),2),
TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.[PER_VAR_TOTAL_SPEND] = CASE WHEN ISNULL(TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.TOTAL_SPEND,0) > 0 THEN (ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.AVG_SPEND - TEMP_TAB3_Y_PROC.MIN_AVG),2) / TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.TOTAL_SPEND) * 100 ELSE 0 END ,
NO_OF_PHYSICIANS_DEPT = TEMP1_TAB3_Y_PROC.NO_OF_PHYSICIANS_DEPT,
NO_OF_PROCEDURES_DEPT = TEMP1_TAB3_Y_PROC.NO_OF_PROCEDURES_DEPT,
[LOW_COST_AVG_DEPT] = TEMP_TAB3_Y_PROC.MIN_AVG
--SELECT ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.AVG_SPEND - TEMP_TAB3_Y_PROC.MIN_AVG),2) VARIANCE , TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.AVG_SPEND , TEMP_TAB3_Y_PROC.MIN_AVG
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC,TEMP_TAB3_Y_PROC,TEMP1_TAB3_Y_PROC
WHERE TEMP_TAB3_Y_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.[YEAR] = TEMP_TAB3_Y_PROC.[YEAR]
--AND TEMP1_TAB3_Y_PROC.[YEAR] = TEMP_TAB3_Y_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.[YEAR] = TEMP1_TAB3_Y_PROC.[YEAR]
AND TEMP1_TAB3_Y_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.PROCEDURE_CODE = TEMP1_TAB3_Y_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.PROCEDURE_CODE = TEMP_TAB3_Y_PROC.PROCEDURE_CODE
AND TEMP1_TAB3_Y_PROC.SERVICE_CODE=TEMP_TAB3_Y_PROC.SERVICE_CODE 
--AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.SERVICE_CODE = 'ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC.PROCEDURE_CODE='M17.12'

---INSERT INTO MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON
-- SELECT *  FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y  (3846)
--BY YEAR

----DELETE FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y WHERE DIAGNOSIS_CODE_TYPE = 3

INSERT INTO MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[NO_OF_PROCEDURES]
,[MIN_PROC_COST]
,[MAX_PROC_COST]
,[AVG_PROC_COST]
,[TOTAL_SPEND]
,[PER_VAR_TOTAL_SPEND]
,[PHYSICIAN_RANK]
,[NO_OF_PHY_DEPT]
,[NO_OF_PROCS_DEPT]
,[LOW_COST_AVG_DEPT]
,[MIN_PROC_VARIANCE]
,[EXTENDED_VARIANCE]
,[YEAR])
SELECT SERVICE_CODE, ISNULL(PROCEDURE_CODE, ' '),ISNULL(PHYSICIAN,' ') PHYSICIAN, '' PHYSICIAN_NAME , ISNULL(proc_descr, ' '),
3 AS 'DIAGNOSIS_CODE_TYPE', 
--' ',' ', 
AVG(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  MIN(ISNULL(MIN_SPEND,0)) MIN_SPEND, MAX(ISNULL(MAX_SPEND,0)) MAX_SPEND, AVG(ISNULL(AVG_SPEND,0)) AVG_SPEND,
ISNULL(SUM(TOTAL_SPEND),0) TOTAL_SPEND, 
SUM([PER_VAR_TOTAL_SPEND]) [PER_VAR_TOTAL_SPEND],
0,
AVG(NO_OF_PHYSICIANS_DEPT) NO_OF_PHYSICIANS_DEPT,
AVG(NO_OF_PROCEDURES_DEPT) NO_OF_PROCEDURES_DEPT,
AVG([LOW_COST_AVG_DEPT]) [LOW_COST_AVG_DEPT],
ROUND(SUM([VARIANCE]),2) [VARIANCE],
ROUND((SUM(ISNULL(NO_OF_PROCEDURES,0)) * SUM([VARIANCE])),2) [EXTENDED_VARIANCE],
[YEAR] FROM TEMP_PHYSICIAN_AVERAGE_TAB3_Y_PROC
--WHERE PROCEDURE_CODE='I21.09' AND SERVICE_CODE='CARDIOTHORACIC' AND PHYSICIAN='SAMYS'
--WHERE SERVICE_CODE = 'ORTHOPEDICS' AND PROCEDURE_CODE='M17.12'
GROUP BY SERVICE_CODE,PROCEDURE_CODE,proc_descr,[YEAR], PHYSICIAN


-------to update RANK 3rd tab--------------

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHY_RANK_DATA')
BEGIN
drop table TEMP_PHY_RANK_DATA
END


-- DROP TABLE TEMP_PHY_RANK_DATA


SELECT SPECIALTY_CODE, [DIAGNOSIS_CODE], PHYSICIAN_ID, [AVG_PROC_COST], [YEAR], DIAGNOSIS_CODE_TYPE
, DENSE_RANK() OVER(partition by SPECIALTY_CODE, [DIAGNOSIS_CODE], [YEAR] ORDER BY [AVG_PROC_COST] ASC) AS [RANK] 
INTO TEMP_PHY_RANK_DATA
FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y where  DIAGNOSIS_CODE_TYPE=3
order by PHYSICIAN_ID



UPDATE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y
SET [PHYSICIAN_RANK] = TEMP_PHY_RANK_DATA.[RANK]
FROM  MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y, TEMP_PHY_RANK_DATA
WHERE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.SPECIALTY_CODE = TEMP_PHY_RANK_DATA.SPECIALTY_CODE
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.[DIAGNOSIS_CODE] = TEMP_PHY_RANK_DATA.[DIAGNOSIS_CODE]
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.PHYSICIAN_ID = TEMP_PHY_RANK_DATA.PHYSICIAN_ID
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.[YEAR] = TEMP_PHY_RANK_DATA.[YEAR]
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.DIAGNOSIS_CODE_TYPE = TEMP_PHY_RANK_DATA.DIAGNOSIS_CODE_TYPE
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.DIAGNOSIS_CODE_TYPE=3
-------------------

update MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y set PHYSICIAN_NAME=[ATPAR_MT].[MT_POU_PHYSICIAN].FIRST_NAME
+' ' + [ATPAR_MT].[MT_POU_PHYSICIAN].MIDDLE_INITIAL + ' '+[ATPAR_MT].[MT_POU_PHYSICIAN].LAST_NAME
from MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y,[ATPAR_MT].[MT_POU_PHYSICIAN]
where MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.PHYSICIAN_ID=[ATPAR_MT].[MT_POU_PHYSICIAN].PHYSICIAN_ID


	--update MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y set PREF_LIST_DESCRIPTION=[ATPAR_MT].MT_POU_PREF_LIST_HEADER.PREF_LIST_DESCR
	--from [MT_POU_RPT_OPT_BY_PHYSICIAN_Y],[ATPAR_MT].MT_POU_PREF_LIST_HEADER
	--where [MT_POU_RPT_OPT_BY_PHYSICIAN_Y].PREF_LIST_ID=[ATPAR_MT].MT_POU_PREF_LIST_HEADER.PREF_LIST_ID

update MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y set DIAGNOSIS_DESCRIPTION =[ATPAR_MT].[MT_RPT_POU_PROCEDURE_PREF_DATA].[PC_DESCRIPTION] from
MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y,[ATPAR_MT].[MT_RPT_POU_PROCEDURE_PREF_DATA]
where MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.DIAGNOSIS_CODE=[ATPAR_MT].[MT_RPT_POU_PROCEDURE_PREF_DATA].PROCEDURE_id
and MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.SPECIALTY_CODE=[ATPAR_MT].[MT_RPT_POU_PROCEDURE_PREF_DATA].SPECIALTY_CODE

update MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y set SPECIALTY_CODE='OTHERS' 
where  SPECIALTY_CODE='' OR SPECIALTY_CODE=' ' OR SPECIALTY_CODE IS NULL

update MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y set DIAGNOSIS_DESCRIPTION=DIAGNOSIS_CODE where 
DIAGNOSIS_DESCRIPTION='' OR DIAGNOSIS_DESCRIPTION=' ' OR DIAGNOSIS_DESCRIPTION IS NULL


--update MT_POU_RPT_OPT_BY_PHYSICIAN_Y set PHYSICIAN_NAME=substring(PHYSICIAN_ID,(CHARINDEX('-',PHYSICIAN_ID))+1,len(PHYSICIAN_ID)) where PHYSICIAN_NAME=''

--update MT_POU_RPT_OPT_BY_PHYSICIAN_Y set PHYSICIAN_NAME=substring(PHYSICIAN_ID,(CHARINDEX('-',PHYSICIAN_ID))+1,len(PHYSICIAN_ID)) where PHYSICIAN_NAME is null


UPDATE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y 
SET DIAGNOSIS_DESCRIPTION = ATPAR_MT.MT_POU_PROCEDURE_CODE.DESCRIPTION
FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y,ATPAR_MT.MT_POU_PROCEDURE_CODE
WHERE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.[DIAGNOSIS_CODE]=ATPAR_MT.MT_POU_PROCEDURE_CODE.PROCEDURE_CODE
AND (MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.DIAGNOSIS_DESCRIPTION IS NULL OR MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.DIAGNOSIS_DESCRIPTION = ''
OR MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y.DIAGNOSIS_DESCRIPTION=' ')
