"use strict";
var MT_ATPAR_PRINT_LABEL_DETAILS = (function () {
    function MT_ATPAR_PRINT_LABEL_DETAILS() {
    }
    return MT_ATPAR_PRINT_LABEL_DETAILS;
}());
exports.MT_ATPAR_PRINT_LABEL_DETAILS = MT_ATPAR_PRINT_LABEL_DETAILS;
//# sourceMappingURL=MT_ATPAR_PRINT_LABEL_DETAILS.js.map