"use strict";
var MT_ATPAR_PHYSICAL_INVENTORY = (function () {
    function MT_ATPAR_PHYSICAL_INVENTORY() {
    }
    return MT_ATPAR_PHYSICAL_INVENTORY;
}());
exports.MT_ATPAR_PHYSICAL_INVENTORY = MT_ATPAR_PHYSICAL_INVENTORY;
//# sourceMappingURL=MT_ATPAR_PHYSICAL_INVENTORY.js.map