"use strict";
var MT_ATPAR_PROCESS_TRANS_HISTORY = (function () {
    function MT_ATPAR_PROCESS_TRANS_HISTORY() {
    }
    return MT_ATPAR_PROCESS_TRANS_HISTORY;
}());
exports.MT_ATPAR_PROCESS_TRANS_HISTORY = MT_ATPAR_PROCESS_TRANS_HISTORY;
//# sourceMappingURL=MT_ATPAR_PROCESS_TRANS_HISTORY.js.map