"use strict";
var MT_ATPAR_DASHBOARD_HEADER = (function () {
    function MT_ATPAR_DASHBOARD_HEADER() {
    }
    return MT_ATPAR_DASHBOARD_HEADER;
}());
exports.MT_ATPAR_DASHBOARD_HEADER = MT_ATPAR_DASHBOARD_HEADER;
//# sourceMappingURL=MT_ATPAR_DASHBOARD_HEADER.js.map