"use strict";
var MT_ATPAR_ZONE_STORAGE_LEVELS = (function () {
    function MT_ATPAR_ZONE_STORAGE_LEVELS() {
    }
    return MT_ATPAR_ZONE_STORAGE_LEVELS;
}());
exports.MT_ATPAR_ZONE_STORAGE_LEVELS = MT_ATPAR_ZONE_STORAGE_LEVELS;
//# sourceMappingURL=MT_ATPAR_ZONE_STORAGE_LEVELS.js.map