"use strict";
var MT_ATPAR_LOC_GROUP_ALLOCATION = (function () {
    function MT_ATPAR_LOC_GROUP_ALLOCATION() {
    }
    return MT_ATPAR_LOC_GROUP_ALLOCATION;
}());
exports.MT_ATPAR_LOC_GROUP_ALLOCATION = MT_ATPAR_LOC_GROUP_ALLOCATION;
//# sourceMappingURL=MT_ATPAR_LOC_GROUP_ALLOCATION.js.map