"use strict";
var MT_ATPAR_USER_PROFILE_APP_ACL_ORG = (function () {
    function MT_ATPAR_USER_PROFILE_APP_ACL_ORG() {
    }
    return MT_ATPAR_USER_PROFILE_APP_ACL_ORG;
}());
exports.MT_ATPAR_USER_PROFILE_APP_ACL_ORG = MT_ATPAR_USER_PROFILE_APP_ACL_ORG;
//# sourceMappingURL=MT_ATPAR_USER_PROFILE_APP_ACL_ORG.js.map