"use strict";
var MT_ATPAR_ORG_GROUP_PARAMETERS = (function () {
    function MT_ATPAR_ORG_GROUP_PARAMETERS() {
    }
    return MT_ATPAR_ORG_GROUP_PARAMETERS;
}());
exports.MT_ATPAR_ORG_GROUP_PARAMETERS = MT_ATPAR_ORG_GROUP_PARAMETERS;
//# sourceMappingURL=MT_ATPAR_ORG_GROUP_PARAMETERS.js.map