"use strict";
var MT_ATPAR_USER_PROFILE_APP_ACL = (function () {
    function MT_ATPAR_USER_PROFILE_APP_ACL() {
    }
    return MT_ATPAR_USER_PROFILE_APP_ACL;
}());
exports.MT_ATPAR_USER_PROFILE_APP_ACL = MT_ATPAR_USER_PROFILE_APP_ACL;
//# sourceMappingURL=MT_ATPAR_USER_PROFILE_APP_ACL.js.map