"use strict";
var MT_ATPAR_PRINT_FIELD_DEFAULTS = (function () {
    function MT_ATPAR_PRINT_FIELD_DEFAULTS() {
    }
    return MT_ATPAR_PRINT_FIELD_DEFAULTS;
}());
exports.MT_ATPAR_PRINT_FIELD_DEFAULTS = MT_ATPAR_PRINT_FIELD_DEFAULTS;
//# sourceMappingURL=MT_ATPAR_PRINT_FIELD_DEFAULTS.js.map