"use strict";
var MT_ATPAR_PRINT_LABEL_HEADER = (function () {
    function MT_ATPAR_PRINT_LABEL_HEADER() {
    }
    return MT_ATPAR_PRINT_LABEL_HEADER;
}());
exports.MT_ATPAR_PRINT_LABEL_HEADER = MT_ATPAR_PRINT_LABEL_HEADER;
//# sourceMappingURL=MT_ATPAR_PRINT_LABEL_HEADER.js.map