"use strict";
var MT_ATPAR_TRANSACTION_ID_TBL = (function () {
    function MT_ATPAR_TRANSACTION_ID_TBL() {
    }
    return MT_ATPAR_TRANSACTION_ID_TBL;
}());
exports.MT_ATPAR_TRANSACTION_ID_TBL = MT_ATPAR_TRANSACTION_ID_TBL;
//# sourceMappingURL=MT_ATPAR_TRANSACTION_ID_TBL.js.map