"use strict";
var MT_ATPAR_DETAIL_TRANSACTION = (function () {
    function MT_ATPAR_DETAIL_TRANSACTION() {
    }
    return MT_ATPAR_DETAIL_TRANSACTION;
}());
exports.MT_ATPAR_DETAIL_TRANSACTION = MT_ATPAR_DETAIL_TRANSACTION;
//# sourceMappingURL=MT_ATPAR_DETAIL_TRANSACTION.js.map