"use strict";
var MT_ATPAR_HL7_MSGS_TRANSMISSION = (function () {
    function MT_ATPAR_HL7_MSGS_TRANSMISSION() {
    }
    return MT_ATPAR_HL7_MSGS_TRANSMISSION;
}());
exports.MT_ATPAR_HL7_MSGS_TRANSMISSION = MT_ATPAR_HL7_MSGS_TRANSMISSION;
//# sourceMappingURL=MT_ATPAR_HL7_MSGS_TRANSMISSION.js.map