"use strict";
var MT_DELV_COST_CENTER_AUTH_PERSON = (function () {
    function MT_DELV_COST_CENTER_AUTH_PERSON() {
    }
    return MT_DELV_COST_CENTER_AUTH_PERSON;
}());
exports.MT_DELV_COST_CENTER_AUTH_PERSON = MT_DELV_COST_CENTER_AUTH_PERSON;
//# sourceMappingURL=MT_DELV_COST_CENTER_AUTH_PERSON.js.map