"use strict";
var MT_POU_COST_CENTER_ALLOCATIONS = (function () {
    function MT_POU_COST_CENTER_ALLOCATIONS() {
    }
    return MT_POU_COST_CENTER_ALLOCATIONS;
}());
exports.MT_POU_COST_CENTER_ALLOCATIONS = MT_POU_COST_CENTER_ALLOCATIONS;
//# sourceMappingURL=MT_POU_COST_CENTER_ALLOCATIONS.js.map