"use strict";
var MT_POU_CHARGECAPTURE_DETAILS = (function () {
    function MT_POU_CHARGECAPTURE_DETAILS() {
    }
    return MT_POU_CHARGECAPTURE_DETAILS;
}());
exports.MT_POU_CHARGECAPTURE_DETAILS = MT_POU_CHARGECAPTURE_DETAILS;
//# sourceMappingURL=MT_POU_CHARGECAPTURE_DETAILS.js.map