"use strict";
var MT_PKPL_DEVIATION_DETAILS = (function () {
    function MT_PKPL_DEVIATION_DETAILS() {
    }
    return MT_PKPL_DEVIATION_DETAILS;
}());
exports.MT_PKPL_DEVIATION_DETAILS = MT_PKPL_DEVIATION_DETAILS;
//# sourceMappingURL=MT_PKPL_DEVIATION_DETAILS.js.map