"use strict";
var MT_POU_CHARGECAPTURE_HEADER = (function () {
    function MT_POU_CHARGECAPTURE_HEADER() {
    }
    return MT_POU_CHARGECAPTURE_HEADER;
}());
exports.MT_POU_CHARGECAPTURE_HEADER = MT_POU_CHARGECAPTURE_HEADER;
//# sourceMappingURL=MT_POU_CHARGECAPTURE_HEADER.js.map