"use strict";
var MT_POU_PTWY_DEVIATION_DETAILS = (function () {
    function MT_POU_PTWY_DEVIATION_DETAILS() {
    }
    return MT_POU_PTWY_DEVIATION_DETAILS;
}());
exports.MT_POU_PTWY_DEVIATION_DETAILS = MT_POU_PTWY_DEVIATION_DETAILS;
//# sourceMappingURL=MT_POU_PTWY_DEVIATION_DETAILS.js.map