"use strict";
var MT_POU_PAR_LOC_PROCESS_SCHEDULE = (function () {
    function MT_POU_PAR_LOC_PROCESS_SCHEDULE() {
    }
    return MT_POU_PAR_LOC_PROCESS_SCHEDULE;
}());
exports.MT_POU_PAR_LOC_PROCESS_SCHEDULE = MT_POU_PAR_LOC_PROCESS_SCHEDULE;
//# sourceMappingURL=MT_POU_PAR_LOC_PROCESS_SCHEDULE.js.map