"use strict";
var MT_POU_DEPT_USER_ALLOCATIONS = (function () {
    function MT_POU_DEPT_USER_ALLOCATIONS() {
    }
    return MT_POU_DEPT_USER_ALLOCATIONS;
}());
exports.MT_POU_DEPT_USER_ALLOCATIONS = MT_POU_DEPT_USER_ALLOCATIONS;
//# sourceMappingURL=MT_POU_DEPT_USER_ALLOCATIONS.js.map