"use strict";
var MT_POU_DEPT_CART_ALLOCATIONS = (function () {
    function MT_POU_DEPT_CART_ALLOCATIONS() {
    }
    return MT_POU_DEPT_CART_ALLOCATIONS;
}());
exports.MT_POU_DEPT_CART_ALLOCATIONS = MT_POU_DEPT_CART_ALLOCATIONS;
//# sourceMappingURL=MT_POU_DEPT_CART_ALLOCATIONS.js.map