"use strict";
var MT_RECV_PARCEL_COUNTS_DETAIL = (function () {
    function MT_RECV_PARCEL_COUNTS_DETAIL() {
    }
    return MT_RECV_PARCEL_COUNTS_DETAIL;
}());
exports.MT_RECV_PARCEL_COUNTS_DETAIL = MT_RECV_PARCEL_COUNTS_DETAIL;
//# sourceMappingURL=MT_RECV_PARCEL_COUNTS_DETAIL.js.map