"use strict";
var MT_RECV_PARCEL_COUNTS_SIGNATURE = (function () {
    function MT_RECV_PARCEL_COUNTS_SIGNATURE() {
    }
    return MT_RECV_PARCEL_COUNTS_SIGNATURE;
}());
exports.MT_RECV_PARCEL_COUNTS_SIGNATURE = MT_RECV_PARCEL_COUNTS_SIGNATURE;
//# sourceMappingURL=MT_RECV_PARCEL_COUNTS_SIGNATURE.js.map