"use strict";
var MT_RECV_DEVIATION_DETAILS = (function () {
    function MT_RECV_DEVIATION_DETAILS() {
    }
    return MT_RECV_DEVIATION_DETAILS;
}());
exports.MT_RECV_DEVIATION_DETAILS = MT_RECV_DEVIATION_DETAILS;
//# sourceMappingURL=MT_RECV_DEVIATION_DETAILS.js.map