"use strict";
var MT_RECV_SHIPTO_ID_ALLOCATION = (function () {
    function MT_RECV_SHIPTO_ID_ALLOCATION() {
    }
    return MT_RECV_SHIPTO_ID_ALLOCATION;
}());
exports.MT_RECV_SHIPTO_ID_ALLOCATION = MT_RECV_SHIPTO_ID_ALLOCATION;
//# sourceMappingURL=MT_RECV_SHIPTO_ID_ALLOCATION.js.map