"use strict";
var MT_STIS_DEST_LOC_ALLOCATION = (function () {
    function MT_STIS_DEST_LOC_ALLOCATION() {
    }
    return MT_STIS_DEST_LOC_ALLOCATION;
}());
exports.MT_STIS_DEST_LOC_ALLOCATION = MT_STIS_DEST_LOC_ALLOCATION;
//# sourceMappingURL=MT_STIS_DEST_LOC_ALLOCATION.js.map