export class PAR_MNGT_PAR_LOC_DETAILS {
    public ORG_ID: string;
    public PAR_LOC_ID: string;
    public BIN_LOC: string;
    public ITEM_ID: string;
    public STATUS: string;
    public COUNT_ORDER?: number;
    public OPTIMAL_QTY?: number;
    public COUNT_REQUIRED: string;
    public REPLENISHMENT_TYPE?: number;
    public FILL_KILL_FLAG: string;
    public LOT_CONTROLLED: string;
    public SERIAL_CONTROLLED: string;
    public MAX_QTY?: number;
    public FOQ_QTY?: number;
    public ORDERING_TYPE: string;
    public CHARGE_CODE: string;
    public COST_CENTER: string;
    public UNIT_OF_ISSUE: string;
    public CONVERSION_RATE?: number;
    public USER_FIELD_1: string;
    public LAST_UPDATE_DATE:  Date;
    public LAST_UPDATE_USER: string;
    public LAST_CLIENT_ADDRESS: string;
    public INV_BUSINESS_UNIT: string;
    public REQUISITION_TYPE: string;
    public UNIT_OF_PROCUREMENT: string;
    public USER_FIELD_2: string;
}