"use strict";
var RF_READER_CONFIGURATION_DETAILS = (function () {
    function RF_READER_CONFIGURATION_DETAILS() {
    }
    return RF_READER_CONFIGURATION_DETAILS;
}());
exports.RF_READER_CONFIGURATION_DETAILS = RF_READER_CONFIGURATION_DETAILS;
//# sourceMappingURL=RF_READER_CONFIGURATION_DETAILS.js.map