--By ICD

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD
END
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD')
BEGIN
DROP TABLE TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD')
BEGIN
DROP TABLE TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD
END


IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_ALL_PHY_TOTSPEND_TAB2_Q_ICD')
BEGIN
DROP TABLE TEMP_ALL_PHY_TOTSPEND_TAB2_Q_ICD
END

alter table MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q alter column DIAGNOSIS_DESCRIPTION nvarchar(254) null

--  DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q WHERE [DIAGNOSIS_CODE_TYPE]=1
--BY procedure
-----------------------------------------------------------------------------------------------------------------------------
--TO GET TOTAL_SPEND_ANNUAL

SELECT SERVICE_CODE, ICD10, SUM(TOTAL_SPEND) TOTAL_SPEND_ANNUAL, [YEAR] 
INTO TEMP_ALL_PHY_TOTSPEND_TAB2_Q_ICD
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, SUM(C.TOTAL_SPEND) TOTAL_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN, CASEID, SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details] where ICD10 is not null
			  --WHERE SERVICE_CODE='ORTHOPEDICS' AND ICD10 IS NOT NULL AND ICD10='M23.221'			 
GROUP BY SERVICE_CODE, ICD10, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, ICD10, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, ICD10, [YEAR]

-----------------------------------------------------------------------------------------------------------------------------------(Q=1)

--TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD TABLE:contains min max average usage among all physicians (Q=1)

SELECT SERVICE_CODE, ICD10, MIN(B.AVG_SPEND) MIN_AVG, MAX(B.AVG_SPEND) MAX_AVG, [YEAR], [QUARTER] 
INTO TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR], C.[QUARTER]
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN, CASEID, SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR], DATEPART(Q,[performdatewtime]) [QUARTER]
			  FROM [Item_details] where ICD10 is not null			  
			  --WHERE SERVICE_CODE='ORTHOPEDICS' AND ICD10 IS NOT NULL AND ICD10='M23.221'			 
GROUP BY SERVICE_CODE, ICD10, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]), DATEPART(Q,[performdatewtime])) C
GROUP BY SERVICE_CODE, ICD10, PHYSICIAN, [YEAR], [QUARTER]) B
GROUP BY SERVICE_CODE, ICD10, [YEAR], [QUARTER]

-------------------------PHYSICIAN COUNT--------------------(Q=1)

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS, SERVICE_CODE, ICD10, 
DATEPART(YYYY,[performdatewtime]) [YEAR] , DATEPART(Q,[performdatewtime]) [QUARTER]
INTO TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD
FROM [Item_details] where ICD10 is not null	
--WHERE SERVICE_CODE = 'GYNECOLOGY' AND ICD10='C54.1'
GROUP BY  SERVICE_CODE, ICD10, DATEPART(YYYY,[performdatewtime]), DATEPART(Q,[performdatewtime]) 

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB2_Q_PROC TABLE:contains min max average usage by physician(Q=1)

SELECT C.SERVICE_CODE, PHYSICIAN, ICD10, [ICD10 DESCRIPTION], [YEAR], [QUARTER], COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, 
		SUM(TOTAL_SPEND) TOTAL_SPEND, MIN(TOTAL_SPEND) MIN_SPEND, AVG(TOTAL_SPEND) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND 
		INTO TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD
FROM (SELECT SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, CASEID, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND,  
			 DATEPART(YYYY,[performdatewtime]) [YEAR],
			 DATEPART(Q,[performdatewtime]) [QUARTER]
			 FROM [Item_details] where ICD10 is not null			
			-- WHERE SERVICE_CODE='ORTHOPEDICS' AND ICD10 IS NOT NULL AND ICD10='M23.221'		 
GROUP BY  SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN,  CASEID,  DATEPART(YYYY,[performdatewtime]), DATEPART(Q,[performdatewtime])) C
GROUP BY SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN,  [YEAR], [QUARTER]

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD ADD NO_OF_PHYSICIANS INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD ADD TOTAL_SPEND_ANNUAL FLOAT
--------------
UPDATE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD 
SET TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.TOTAL_SPEND_ANNUAL = ISNULL(TEMP_ALL_PHY_TOTSPEND_TAB2_Q_ICD.TOTAL_SPEND_ANNUAL,0)
FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD,TEMP_ALL_PHY_TOTSPEND_TAB2_Q_ICD
WHERE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.SERVICE_CODE=TEMP_ALL_PHY_TOTSPEND_TAB2_Q_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.ICD10 = TEMP_ALL_PHY_TOTSPEND_TAB2_Q_ICD.ICD10
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.[YEAR] = TEMP_ALL_PHY_TOTSPEND_TAB2_Q_ICD.[YEAR]


----------------------------------------------------------------------------------------------------------------------------------------
UPDATE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD 
SET TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.[VARIANCE] = ROUND(TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.AVG_SPEND - TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD.MIN_AVG,2) * (TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.NO_OF_PROCEDURES),
TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.NO_OF_PHYSICIANS = TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD.NO_OF_PHYSICIANS
FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD,TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD ,TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD
WHERE TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.ICD10 = TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD.ICD10
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.[YEAR] = TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.[YEAR] = TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.[QUARTER] = TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD.[QUARTER]
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.[QUARTER] = TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD.[QUARTER]
AND TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD.ICD10 = TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD.ICD10
AND TEMP_PHYSICIAN_COUNT_TAB2_Q1_ICD.SERVICE_CODE=TEMP_ALL_PHYSICIANS_TAB2_Q1_ICD.SERVICE_CODE

--------------------------------------------------------------------------------------------------------------
--DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q WHERE [DIAGNOSIS_CODE_TYPE]=1 (ROWS: 768)
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q
 ([SPECIALTY_CODE],[SPECIALTY_DESCRIPTION],
[DIAGNOSIS_CODE] ,
[DIAGNOSIS_DESCRIPTION],
[DIAGNOSIS_CODE_TYPE]
,[NO_OF_PHYSICIANS]
,[NO_OF_PROCEDURES]
,[MAX_USAGE]
,[MIN_USAGE]
,[TOTAL_VARIANCE]
,[TOTAL_SPEND]
,[TOTAL_ANNUAL_SPEND]
,[PERIOD]
,[YEAR]
)
SELECT SERVICE_CODE, SERVICE_CODE,  
--ISNULL(ICD10, ' ') ICD10,' ' [CPT_CODE], ISNULL(ICD10, ' ') PROCEDURE_CODE, ISNULL([ICD10 DESCRIPTION], ' '), 
ISNULL(ICD10, ' ') ICD10, ISNULL([ICD10 DESCRIPTION], ' '),
1 AS 'DIAGNOSIS_CODE_TYPE', 
AVG(ISNULL(NO_OF_PHYSICIANS,0)) NO_OF_PHYSICIANS, SUM(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES, MAX(ISNULL(AVG_SPEND,0)) MAX_SPEND,
MIN(ISNULL(AVG_SPEND,0)) MIN_SPEND, SUM(ISNULL([VARIANCE],0)) [VARIANCE], 
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND, ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND_ANNUAL,[QUARTER],
[YEAR] FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD
--WHERE SERVICE_CODE = 'GYNECOLOGY' AND ICD10='C54.1'
--WHERE SERVICE_CODE = 'ORTHOPEDICS' AND ICD10='M17.12'
GROUP BY [YEAR], SERVICE_CODE, ICD10, [ICD10 DESCRIPTION],[QUARTER]
------------------------------------------------------------------------------------------
--SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q
--ALTER TABLE SPECIALTY_MASTER
--ALTER COLUMN SPECIALTY [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

UPDATE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q SET [SPECIALTY_DESCRIPTION]=SPECIALTY_CODE
--SPECIALTY_MASTER.SPECIALTY_DESCR 
--FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q,SPECIALTY_MASTER
--WHERE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.SPECIALTY_CODE=SPECIALTY_MASTER.SPECIALTY




--By PROCEDURE

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC
END
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC')
BEGIN
DROP TABLE TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC
END
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC')
BEGIN
DROP TABLE TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC
END
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC')
BEGIN
DROP TABLE TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_ALL_PHY_TOTSPEND_TAB2_Q_PROC')
BEGIN
DROP TABLE TEMP_ALL_PHY_TOTSPEND_TAB2_Q_PROC
END
--  DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q
--BY procedure
-----------------------------------------------------------------------------------------------------------------------------
--TO GET TOTAL_SPEND_ANNUAL

SELECT SERVICE_CODE, PROCEDURE_CODE, SUM(TOTAL_SPEND) TOTAL_SPEND_ANNUAL, [YEAR] 
INTO TEMP_ALL_PHY_TOTSPEND_TAB2_Q_PROC
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, SUM(C.TOTAL_SPEND) TOTAL_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details]
			  --WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='M23.221'			 
GROUP BY SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, PROCEDURE_CODE, [YEAR]

-----------------------------------------------------------------------------------------------------------------------------------(Q=1)

--TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC TABLE:contains min max average usage among all physicians (Q=1)

SELECT SERVICE_CODE, PROCEDURE_CODE, MIN(B.AVG_SPEND) MIN_AVG, MAX(B.AVG_SPEND) MAX_AVG, [YEAR], [QUARTER] 
INTO TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR], C.[QUARTER]
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR], DATEPART(Q,[performdatewtime]) [QUARTER]
			  FROM [Item_details]			  
			  --WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='M23.221'			 
GROUP BY SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]), DATEPART(Q,[performdatewtime])) C
GROUP BY SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, [YEAR], [QUARTER]) B
GROUP BY SERVICE_CODE, PROCEDURE_CODE, [YEAR], [QUARTER]

-------------------------PHYSICIAN COUNT--------------------(Q=1)

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS, SERVICE_CODE,-- PROCEDURE_CODE, 
DATEPART(YYYY,[performdatewtime]) [YEAR] , DATEPART(Q,[performdatewtime]) [QUARTER]
INTO TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC
FROM [Item_details]	
--WHERE SERVICE_CODE = 'ORTHOPEDICS' AND  DATEPART(Q,[performdatewtime]) = 4 --AND PROCEDURE_CODE='C54.1'
GROUP BY  SERVICE_CODE, 
PROCEDURE_CODE, 
DATEPART(YYYY,[performdatewtime]), DATEPART(Q,[performdatewtime]) 

-------------------------PHYSICIAN COUNT(SUMMARY)----------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS, SERVICE_CODE,
DATEPART(YYYY,[performdatewtime]) [YEAR] , DATEPART(Q,[performdatewtime]) [QUARTER]
INTO TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC
FROM [Item_details]	
GROUP BY  SERVICE_CODE, 
DATEPART(YYYY,[performdatewtime]), DATEPART(Q,[performdatewtime]) 

----------------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB2_Q_PROC TABLE:contains min max average usage by physician(Q=1)

SELECT C.SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE, proc_descr, [YEAR], [QUARTER], COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, 
		SUM(TOTAL_SPEND) TOTAL_SPEND, MIN(TOTAL_SPEND) MIN_SPEND, AVG(TOTAL_SPEND) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND 
		INTO TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, CASEID, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND,  
			 DATEPART(YYYY,[performdatewtime]) [YEAR],
			 DATEPART(Q,[performdatewtime]) [QUARTER]
			 FROM [Item_details]			
			-- WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='M23.221'		 
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN,  CASEID,  DATEPART(YYYY,[performdatewtime]), DATEPART(Q,[performdatewtime])) C
GROUP BY SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN,  [YEAR], [QUARTER]

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC ADD NO_OF_PHYSICIANS INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC ADD TOTAL_SPEND_ANNUAL FLOAT
--------------
UPDATE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC 
SET TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.TOTAL_SPEND_ANNUAL = ISNULL(TEMP_ALL_PHY_TOTSPEND_TAB2_Q_PROC.TOTAL_SPEND_ANNUAL,0)
FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC,TEMP_ALL_PHY_TOTSPEND_TAB2_Q_PROC
WHERE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.SERVICE_CODE=TEMP_ALL_PHY_TOTSPEND_TAB2_Q_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.PROCEDURE_CODE = TEMP_ALL_PHY_TOTSPEND_TAB2_Q_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.[YEAR] = TEMP_ALL_PHY_TOTSPEND_TAB2_Q_PROC.[YEAR]


----------------------------------------------------------------------------------------------------------------------------------------
UPDATE TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC 
SET TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.[VARIANCE] = ROUND(TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.AVG_SPEND - TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC.MIN_AVG,2) * (TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.NO_OF_PROCEDURES),
TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.NO_OF_PHYSICIANS = TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC.NO_OF_PHYSICIANS
FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC,TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC ,TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC
WHERE TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.PROCEDURE_CODE = TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.[YEAR] = TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.[YEAR] = TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.[QUARTER] = TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC.[QUARTER]
AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.[QUARTER] = TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC.[QUARTER]
AND TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.SERVICE_CODE 
--AND TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC.PROCEDURE_CODE = TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC.SERVICE_CODE=TEMP_ALL_PHYSICIANS_TAB2_Q1_PROC.SERVICE_CODE

--------------------------------------------------------------------------------------------------------------
--sp_help TEMP_PHYSICIAN_COUNT_TAB2_Q1_PROC

--DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q where [DIAGNOSIS_CODE_TYPE]=3 (ROWS: 768)
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q
 ([SPECIALTY_CODE],[SPECIALTY_DESCRIPTION],
[DIAGNOSIS_CODE] ,
[DIAGNOSIS_DESCRIPTION],
[DIAGNOSIS_CODE_TYPE]
,[NO_OF_PHYSICIANS]
,[NO_OF_PROCEDURES]
,[MAX_USAGE]
,[MIN_USAGE]
,[TOTAL_VARIANCE]
,[TOTAL_SPEND]
,[TOTAL_ANNUAL_SPEND]
,[PERIOD]
,[YEAR]
)
SELECT SERVICE_CODE, SERVICE_CODE,  
--ISNULL(ICD10, ' ') ICD10,' ' [CPT_CODE], 
ISNULL(PROCEDURE_CODE, ' ') PROCEDURE_CODE, '',
--ISNULL([ICD10 DESCRIPTION], ' '), 
--ISNULL(ICD10, ' ') ICD10, ISNULL([ICD10 DESCRIPTION], ' '),
3 AS 'DIAGNOSIS_CODE_TYPE', 
AVG(ISNULL(NO_OF_PHYSICIANS,0)) NO_OF_PHYSICIANS, SUM(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES, MAX(ISNULL(AVG_SPEND,0)) MAX_SPEND,
MIN(ISNULL(AVG_SPEND,0)) MIN_SPEND, SUM(ISNULL([VARIANCE],0)) [VARIANCE], 
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND, ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND_ANNUAL,[QUARTER],
[YEAR] FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_PROC
GROUP BY [YEAR], SERVICE_CODE, PROCEDURE_CODE,[QUARTER]
------------------------------------------------------------------------------------------
--SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q
--ALTER TABLE SPECIALTY_MASTER
--ALTER COLUMN SPECIALTY [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

--sp_help TEMP_PHYSICIAN_AVERAGE_TAB2_Q1_ICD

UPDATE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q 
SET DIAGNOSIS_DESCRIPTION = [Item_details].proc_descr
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q,[Item_details]
WHERE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.DIAGNOSIS_CODE=[Item_details].PROCEDURE_CODE AND [DIAGNOSIS_CODE_TYPE]=3
AND (MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.DIAGNOSIS_DESCRIPTION IS NULL 
OR MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.DIAGNOSIS_DESCRIPTION = ''
OR MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.DIAGNOSIS_DESCRIPTION=' ')

--UPDATE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q SET [SPECIALTY_DESCRIPTION]=SPECIALTY_MASTER.SPECIALTY_DESCR 
--FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q,SPECIALTY_MASTER
--WHERE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.SPECIALTY_CODE=SPECIALTY_MASTER.SPECIALTY

--SELECT *  FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Q_PROC
--WHERE SERVICE_CODE = 'ORTHOPEDICS' AND PROCEDURE_CODE='M23.221'

--658554.55



--SELECT proc_descr,PROCEDURE_CODE FROM TEMP_PHYSICIAN_AVERAGE_TAB2_Q_PROC WHERE (proc_descr IS NULL OR proc_descr='' OR proc_descr=' ')
--GROUP BY proc_descr,PROCEDURE_CODE

UPDATE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q SET [SPECIALTY_DESCRIPTION]=SPECIALTY_CODE



