--By ICD


------------------COST VARIANCE BY SPECIALTY---------------------------
--DROP TABLE TEMP_PHYSICIAN_AVERAGE
--DROP TABLE TEMP

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP')
BEGIN
DROP TABLE TEMP
END

DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q

--TEMP TABLE:contains min max average usage among all physicians

--INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q

--BY QUARTER

-- SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q  WHERE [DIAGNOSIS_CODE_TYPE]=1
-- DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q  WHERE [DIAGNOSIS_CODE_TYPE]=1
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q
		    ([SPECIALTY_CODE]
           ,[SPECIALTY_DESCRIPTION]
           ,[NO_OF_PROCEDURES]
           ,[NO_OF_PHYSICIANS]
           ,[TOTAL_SPEND]
           ,[TOTAL_VARIANCE]
		   ,[DIAGNOSIS_CODE_TYPE]
		   ,[PERIOD]
           ,[YEAR])
SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION, SUM(NO_OF_PROCEDURES), SUM(NO_OF_PHYSICIANS) , 
		SUM([TOTAL_SPEND]), SUM([TOTAL_VARIANCE]),[DIAGNOSIS_CODE_TYPE],[PERIOD], [YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q
WHERE DIAGNOSIS_CODE_TYPE = 1
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION, [DIAGNOSIS_CODE_TYPE],[PERIOD],[YEAR]








--By PROCEDURE
------------------COST VARIANCE BY SPECIALTY---------------------------
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP')
BEGIN
DROP TABLE TEMP
END

------------------COST VARIANCE BY SPECIALTY---------------------------
--DROP TABLE TEMP_PHYSICIAN_AVERAGE
--DROP TABLE TEMP
--by procedure
--TEMP TABLE:contains min max average usage among all physicians

--TEMP TABLE

	--SELECT  MIN(TOTAL_SPEND) MIN_AVG, AVG(TOTAL_SPEND) AVERAGE, MAX(TOTAL_SPEND) MAX_AVG, C.SERVICE_CODE , [YEAR] INTO TEMP
	--FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN, CASEID, SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY]) - (([TOTALRETURNED] + [TOTAL WASTED]))) * [CURRENTITEMCOST])) TOTAL_SPEND, 
	--			  DATEPART(YYYY,[performdatewtime]) [YEAR]
	--			  FROM [Item_details]
	--			  WHERE ICD10 IS NOT NULL
	--GROUP BY  CASEID, SERVICE_CODE, ICD10,  PHYSICIAN, DATEPART(YYYY,[performdatewtime])) C
	--GROUP BY SERVICE_CODE, ICD10, [YEAR]

	----TEMP_PHYSICIAN_AVERAGE TABLE:contains min max average usage by physician

	--SELECT COUNT(DISTINCT(CASEID)) CNT, SUM(TOTAL_SPEND) TOTAL_SPEND, MIN(TOTAL_SPEND) MIN_SPEND, AVG(TOTAL_SPEND) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND, 
	--				A.SERVICE_CODE, A.PROCEDURE_CODE, PHYSICIAN,  [MONTH], [YEAR] INTO TEMP_PHYSICIAN_AVERAGE
	--FROM (SELECT SUM(C.TOTAL_SPEND) TOTAL_SPEND, PROCEDURE_CODE, PREF_LIST_ID, SERVICE_CODE,  C.PHYSICIAN, C.CASEID, [MONTH], [YEAR]
	--FROM (SELECT (((SUM([TOTALCASEPICKQTY]) + SUM([TOTAL IN ROOM QTY])) - ((SUM([TOTALRETURNED]) + SUM([TOTAL WASTED])))) * AVG([CURRENTITEMCOST])) TOTAL_SPEND, 
	--			 CASEID, PROCEDURE_CODE, PREF_LIST_ID, SERVICE_CODE,  PHYSICIAN, [POU ITEM], DATEPART(MM,[performdatewtime]) [MONTH], DATEPART(YYYY,[performdatewtime]) [YEAR] 
	--			 FROM [Item_details]			 
	--GROUP BY  CASEID, PROCEDURE_CODE, PREF_LIST_ID, SERVICE_CODE,  PHYSICIAN, [POU ITEM], DATEPART(MM,[performdatewtime]), DATEPART(YYYY,[performdatewtime])) C
	--GROUP BY  CASEID, PROCEDURE_CODE, PREF_LIST_ID, SERVICE_CODE,  PHYSICIAN , [MONTH], [YEAR]) A
	--GROUP BY PROCEDURE_CODE, SERVICE_CODE, PHYSICIAN,  [MONTH], [YEAR]


	--ALTER TABLE TEMP_PHYSICIAN_AVERAGE ADD VARIANCE FLOAT

	--UPDATE TEMP_PHYSICIAN_AVERAGE SET TEMP_PHYSICIAN_AVERAGE.[VARIANCE] = TEMP_PHYSICIAN_AVERAGE.AVG_SPEND - TEMP.MIN_AVG FROM TEMP_PHYSICIAN_AVERAGE,TEMP
	--WHERE TEMP.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE.SERVICE_CODE AND TEMP_PHYSICIAN_AVERAGE.PROCEDURE_CODE = TEMP.PROCEDURE_CODE 
	--AND TEMP_PHYSICIAN_AVERAGE.[MONTH] = TEMP.[MONTH]
	--AND TEMP_PHYSICIAN_AVERAGE.[YEAR] = TEMP.[YEAR]


	--SELECT  SERVICE_CODE, SUM(CNT) NO_OF_PROCEDURES, ROUND(SUM(TOTAL_SPEND),2) TOTAL_SPEND, ROUND(SUM(VARIANCE),2) TOTAL_VARIANCE
	--, [MONTH], [YEAR]  
	--FROM TEMP_PHYSICIAN_AVERAGE
	--GROUP BY SERVICE_CODE, [MONTH],[YEAR] ORDER BY SERVICE_CODE,[MONTH]

--INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q

--BY QUARTER
ALTER TABLE TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC
ALTER COLUMN SERVICE_CODE [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
-- SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q
-- DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q WHERE [DIAGNOSIS_CODE_TYPE]=3
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q
		    ([SPECIALTY_CODE]
           ,[SPECIALTY_DESCRIPTION]
           ,[NO_OF_PROCEDURES]
           ,[NO_OF_PHYSICIANS]
           ,[TOTAL_SPEND]
           ,[TOTAL_VARIANCE]
		   ,[DIAGNOSIS_CODE_TYPE]
		   ,[PERIOD]
           ,[YEAR])
SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION, SUM(NO_OF_PROCEDURES), AVG(TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC.NO_OF_PHYSICIANS) , 
		SUM([TOTAL_SPEND]), SUM([TOTAL_VARIANCE]),[DIAGNOSIS_CODE_TYPE],[PERIOD], MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.[YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q,TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC
WHERE DIAGNOSIS_CODE_TYPE = 3
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.SPECIALTY_CODE= TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC.SERVICE_CODE
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.[PERIOD]= TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC.[QUARTER]
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.[YEAR]= TEMP_PHYSICIAN_COUNT_SUMMARY_Q1_PROC.[YEAR]
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION, [DIAGNOSIS_CODE_TYPE],[PERIOD],MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q.[YEAR]





