--By ICD:

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_ICD_Q')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_ICD_Q
END
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PROCEDURES_COUNT_Q_ICD')
BEGIN
DROP TABLE TEMP_PROCEDURES_COUNT_Q_ICD
END


  --DELETE FROM MT_POU_RPT_SPEND_BY_GROUP_Q  WHERE [DIAGNOSIS_CODE_TYPE]=1
--BY ICD
--MT_POU_RPT_SPEND_BY_GROUP

-------------------------------------------------------------------------------------

-------------------------PROCEDURES COUNT--------------------

SELECT COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SERVICE_CODE, PHYSICIAN, ICD10,
 DATEPART(YYYY,[performdatewtime]) [YEAR], DATEPART(Q,[performdatewtime]) [QUARTER] INTO TEMP_PROCEDURES_COUNT_Q_ICD
FROM [Item_details] where ICD10 is not null
GROUP BY  SERVICE_CODE, PHYSICIAN, ICD10,
DATEPART(YYYY,[performdatewtime]),DATEPART(Q,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_ICD_Q TABLE:contains min max average usage by physician and item group

SELECT DISTINCT([Group]) [Group], C.SERVICE_CODE, PHYSICIAN, ICD10, [ICD10 DESCRIPTION], SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY, SUM(TOTAL_SPEND) TOTAL_SPEND, 
				 [YEAR], [QUARTER] INTO TEMP_PHYSICIAN_AVERAGE_ICD_Q
FROM (SELECT SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, CASEID, [Group] ,  SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED]))  TOTAL_ITEM_QTY, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY]) - (([TOTALRETURNED] + [TOTAL WASTED]))) * [CURRENTITEMCOST])) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR], DATEPART(Q,[performdatewtime]) [QUARTER]
			 FROM [Item_details] where ICD10 is not null
			 --WHERE ICD10 IS NOT NULL				  
GROUP BY SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]), [Group], DATEPART(Q,[performdatewtime])) C
GROUP BY SERVICE_CODE, PHYSICIAN, ICD10, [ICD10 DESCRIPTION], [YEAR], [Group], [QUARTER]

------------------------------------------------
 

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_ICD_Q ADD NO_OF_CASES INT


UPDATE TEMP_PHYSICIAN_AVERAGE_ICD_Q SET TEMP_PHYSICIAN_AVERAGE_ICD_Q.NO_OF_CASES = TEMP_PROCEDURES_COUNT_Q_ICD.NO_OF_PROCEDURES
FROM TEMP_PHYSICIAN_AVERAGE_ICD_Q, TEMP_PROCEDURES_COUNT_Q_ICD
WHERE TEMP_PHYSICIAN_AVERAGE_ICD_Q.SERVICE_CODE = TEMP_PROCEDURES_COUNT_Q_ICD.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_ICD_Q.PHYSICIAN = TEMP_PROCEDURES_COUNT_Q_ICD.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_ICD_Q.[YEAR] = TEMP_PROCEDURES_COUNT_Q_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_ICD_Q.ICD10 = TEMP_PROCEDURES_COUNT_Q_ICD.ICD10
AND TEMP_PHYSICIAN_AVERAGE_ICD_Q.[QUARTER] = TEMP_PROCEDURES_COUNT_Q_ICD.[QUARTER]

--BY YEAR
--alter table MT_POU_RPT_SPEND_BY_GROUP_Q
--alter column [TOTAL_COST_ITEM_GROUP] [FLOAT] NULL

-- delete from MT_POU_RPT_SPEND_BY_GROUP_Q  WHERE [DIAGNOSIS_CODE_TYPE]=1 (10923)
INSERT INTO MT_POU_RPT_SPEND_BY_GROUP_Q
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[NO_OF_ITEMS_BY_ITEM_GROUP]
,[ITEM_GROUP]
,[ITEM_GROUP_DESCRIPTION]
,[TOTAL_NO_OF_CASES_PHYSICIAN]
,[TOTAL_COST_ITEM_GROUP]
,[PERIOD]
,[YEAR])
SELECT TEMP_PHYSICIAN_AVERAGE_ICD_Q.SERVICE_CODE, ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_Q.ICD10, ' '),
-- ' ',  ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_Q.ICD10, ' ') ICD10, 
ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_Q.[ICD10 DESCRIPTION], ' ') PROCEDURE_DESCR,
 1 AS 'DIAGNOSIS_CODE_TYPE', 
--ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_Q.[ICD10 DESCRIPTION], ' ') ICD10_DESCR ,' ', 
ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_Q.PHYSICIAN,' ') PHYSICIAN, 
 '' PHYSICIAN_NAME,  
SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY,[Group],[Group], AVG(ISNULL(TEMP_PROCEDURES_COUNT_Q_ICD.NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND,
TEMP_PHYSICIAN_AVERAGE_ICD_Q.[QUARTER],
TEMP_PHYSICIAN_AVERAGE_ICD_Q.[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_ICD_Q, TEMP_PROCEDURES_COUNT_Q_ICD
WHERE TEMP_PHYSICIAN_AVERAGE_ICD_Q.SERVICE_CODE = TEMP_PROCEDURES_COUNT_Q_ICD.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_ICD_Q.PHYSICIAN = TEMP_PROCEDURES_COUNT_Q_ICD.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_ICD_Q.[YEAR] = TEMP_PROCEDURES_COUNT_Q_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_ICD_Q.ICD10 = TEMP_PROCEDURES_COUNT_Q_ICD.ICD10
GROUP BY TEMP_PHYSICIAN_AVERAGE_ICD_Q.SERVICE_CODE,TEMP_PHYSICIAN_AVERAGE_ICD_Q.ICD10,TEMP_PHYSICIAN_AVERAGE_ICD_Q.[ICD10 DESCRIPTION],
TEMP_PHYSICIAN_AVERAGE_ICD_Q.PHYSICIAN,[Group],TEMP_PHYSICIAN_AVERAGE_ICD_Q.[YEAR], TEMP_PHYSICIAN_AVERAGE_ICD_Q.[QUARTER]
ORDER BY TEMP_PHYSICIAN_AVERAGE_ICD_Q.[Group]


-----------------------------
UPDATE MT_POU_RPT_SPEND_BY_GROUP_Q SET [PHYSICIAN_NAME] = ISNULL([Item_details].SURGE_DESCIPTION_orig,'') 
FROM MT_POU_RPT_SPEND_BY_GROUP_Q,[Item_details]
WHERE MT_POU_RPT_SPEND_BY_GROUP_Q.PHYSICIAN_ID=[Item_details].PHYSICIAN



--By PROCEDURE:


IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_PROC_Q')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_PROC_Q
END
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PROCEDURES_COUNT_Q_PROC')
BEGIN
DROP TABLE TEMP_PROCEDURES_COUNT_Q_PROC
END


  --DELETE FROM MT_POU_RPT_SPEND_BY_GROUP_Q
--BY ICD
--MT_POU_RPT_SPEND_BY_GROUP

-------------------------------------------------------------------------------------

ALTER TABLE [Item_details]
ALTER COLUMN [PROCEDURE_CODE] [nvarchar](255) NULL
-------
ALTER TABLE [Item_details]
ALTER COLUMN [PROCEDURE_CODE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

---------------------------------------------------------------------------------------------------------------------

-------------------------PROCEDURES COUNT--------------------

SELECT COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE,
 DATEPART(YYYY,[performdatewtime]) [YEAR], DATEPART(Q,[performdatewtime]) [QUARTER] INTO TEMP_PROCEDURES_COUNT_Q_PROC
FROM [Item_details] 
 --WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='C79.51'
--WHERE SERVICE_CODE = 'GYNECOLOGY' AND PROCEDURE_CODE='C54.1'	
GROUP BY  SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE,
DATEPART(YYYY,[performdatewtime]),DATEPART(Q,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_PROC_Q TABLE:contains min max average usage by physician and item group

SELECT DISTINCT([Group]) [Group], C.SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE, proc_descr, SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY, SUM(TOTAL_SPEND) TOTAL_SPEND, 
				 [YEAR], [QUARTER] INTO TEMP_PHYSICIAN_AVERAGE_PROC_Q
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, CASEID, [Group] ,  SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED]))  TOTAL_ITEM_QTY, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY]) - (([TOTALRETURNED] + [TOTAL WASTED]))) * [CURRENTITEMCOST])) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR], DATEPART(Q,[performdatewtime]) [QUARTER]
			 FROM [Item_details]
			-- WHERE PROCEDURE_CODE IS NOT NULL
			 --WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='C79.51'			  
GROUP BY SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]), [Group], DATEPART(Q,[performdatewtime])) C
GROUP BY SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE, proc_descr, [YEAR], [Group], [QUARTER]

------------------------------------------------
 

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_PROC_Q ADD NO_OF_CASES INT


UPDATE TEMP_PHYSICIAN_AVERAGE_PROC_Q SET TEMP_PHYSICIAN_AVERAGE_PROC_Q.NO_OF_CASES = TEMP_PROCEDURES_COUNT_Q_PROC.NO_OF_PROCEDURES
--SELECT TEMP_PROCEDURES_COUNT_Q_PROC.NO_OF_PROCEDURES
FROM TEMP_PHYSICIAN_AVERAGE_PROC_Q, TEMP_PROCEDURES_COUNT_Q_PROC
WHERE TEMP_PHYSICIAN_AVERAGE_PROC_Q.SERVICE_CODE = TEMP_PROCEDURES_COUNT_Q_PROC.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.PHYSICIAN = TEMP_PROCEDURES_COUNT_Q_PROC.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.[YEAR] = TEMP_PROCEDURES_COUNT_Q_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.PROCEDURE_CODE = TEMP_PROCEDURES_COUNT_Q_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.[QUARTER] = TEMP_PROCEDURES_COUNT_Q_PROC.[QUARTER]
--AND  TEMP_PHYSICIAN_AVERAGE_PROC_Q.SERVICE_CODE='ORTHOPEDICS' 
--AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.PROCEDURE_CODE IS NOT NULL 
--AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.PROCEDURE_CODE='C79.51'

--SELECT * FROM TEMP_PHYSICIAN_AVERAGE_PROC_Q

---INSERT INTO MT_POU_RPT_SPEND_BY_GROUP

--BY YEAR
--alter table MT_POU_RPT_SPEND_BY_GROUP_Q
--alter column [TOTAL_COST_ITEM_GROUP] [FLOAT] NULL

-- delete from MT_POU_RPT_SPEND_BY_GROUP_Q (10923)
INSERT INTO MT_POU_RPT_SPEND_BY_GROUP_Q
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[NO_OF_ITEMS_BY_ITEM_GROUP]
,[ITEM_GROUP]
,[ITEM_GROUP_DESCRIPTION]
,[TOTAL_NO_OF_CASES_PHYSICIAN]
,[TOTAL_COST_ITEM_GROUP]
,[PERIOD]
,[YEAR])
SELECT TEMP_PHYSICIAN_AVERAGE_PROC_Q.SERVICE_CODE,
-- ' ', ' ', 
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_Q.PROCEDURE_CODE, ' ') PROCEDURE_CODE, 
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_Q.proc_descr, ' ') PROCEDURE_DESCR,
 3 AS 'DIAGNOSIS_CODE_TYPE',
-- ' ' ICD10_DESCR ,' ', 
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_Q.PHYSICIAN,' ') PHYSICIAN, 
 '' PHYSICIAN_NAME,  
SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY,[Group],[Group], AVG(ISNULL(TEMP_PROCEDURES_COUNT_Q_PROC.NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND,
TEMP_PHYSICIAN_AVERAGE_PROC_Q.[QUARTER],
TEMP_PHYSICIAN_AVERAGE_PROC_Q.[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_PROC_Q, TEMP_PROCEDURES_COUNT_Q_PROC
WHERE TEMP_PHYSICIAN_AVERAGE_PROC_Q.SERVICE_CODE = TEMP_PROCEDURES_COUNT_Q_PROC.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.PHYSICIAN = TEMP_PROCEDURES_COUNT_Q_PROC.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.[YEAR] = TEMP_PROCEDURES_COUNT_Q_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.PROCEDURE_CODE = TEMP_PROCEDURES_COUNT_Q_PROC.PROCEDURE_CODE
--AND  TEMP_PHYSICIAN_AVERAGE_PROC_Q.SERVICE_CODE='ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_PROC_Q.PROCEDURE_CODE='M17.12'
GROUP BY TEMP_PHYSICIAN_AVERAGE_PROC_Q.SERVICE_CODE,TEMP_PHYSICIAN_AVERAGE_PROC_Q.PROCEDURE_CODE,TEMP_PHYSICIAN_AVERAGE_PROC_Q.proc_descr,
TEMP_PHYSICIAN_AVERAGE_PROC_Q.PHYSICIAN,[Group],TEMP_PHYSICIAN_AVERAGE_PROC_Q.[YEAR], TEMP_PHYSICIAN_AVERAGE_PROC_Q.[QUARTER]
ORDER BY TEMP_PHYSICIAN_AVERAGE_PROC_Q.[Group]

--UPDATE MT_POU_RPT_SPEND_BY_GROUP_Q SET DIAGNOSIS_CODE_TYPE=3 WHERE ICD_CODE=' ' AND PROCEDURE_CODE IS NOT NULL
--SELECT COUNT(*) FROM MT_POU_RPT_SPEND_BY_GROUP_Q WHERE ICD_CODE=' ' AND PROCEDURE_CODE IS NOT NULL

-----------------------------
UPDATE MT_POU_RPT_SPEND_BY_GROUP_Q SET [PHYSICIAN_NAME]=ISNULL([Item_details].SURGE_DESCIPTION_orig,'') FROM MT_POU_RPT_SPEND_BY_GROUP_Q,[Item_details]
WHERE MT_POU_RPT_SPEND_BY_GROUP_Q.PHYSICIAN_ID=[Item_details].PHYSICIAN


--------------------------------
--SELECT ITEM_GROUP, SUM([TOTAL_COST_ITEM_GROUP]) FROM MT_POU_RPT_SPEND_BY_GROUP_Q WHERE SPECIALTY_CODE='ORTHOPEDICS' AND ICD_CODE='M17.12' GROUP BY ITEM_GROUP


