--By ICD:

DELETE FROM MT_POU_RPT_SUPPLY_COMPARISON_Y
-- WHERE [DIAGNOSIS_CODE_TYPE]=1 (297404)

INSERT INTO MT_POU_RPT_SUPPLY_COMPARISON_Y
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[ITEM_GROUP]
,[ITEM_GROUP_DESCRIPTION]
,[ITEM_ID]
,[ITEM_DESCRIPTION]
,[MFR_CATALOG_NO]
,[UNIT_COST]
,[NO_OF_TIMES_ITEM_USED_BY_PHY]
,[YEAR])
SELECT SERVICE_CODE,ISNULL(ICD10, ' ') DIAGNOSIS_CODE,
--' ' [CPT_CODE], ISNULL(ICD10, ' ') PROCEDURE_CODE,
ISNULL([ICD10 DESCRIPTION],' ') DIAGNOSIS_DESCRIPTION, 
1 AS 'DIAGNOSIS_CODE_TYPE',
--ISNULL([ICD10 DESCRIPTION],' ') ICD10_DESCR,' ' [CPT_DESCR], 
ISNULL(PHYSICIAN,' ') PHYSICIAN, ' ' PHYSICIAN_NAME,  
ISNULL([Group],''),ISNULL([Group],''), [POU ITEM], [POU DESCRIPTION], [MHS MFGID], AVG(ISNULL([CURRENTITEMCOST],0)) [CURRENTITEMCOST], 
ISNULL(SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])),0) [TOTALRETURNED],  
DATEPART(YYYY,[performdatewtime]) [YEAR] 
FROM [Item_details] 
WHERE [POU ITEM] IS NOT NULL 
AND ICD10 IS NOT NULL
AND ICD_OUTLIER_Y = 'N'
--AND SERVICE_CODE = 'UROLOGY' AND ICD10 = 'Z43.6' AND PHYSICIAN = 'KOGAN' AND [POU ITEM] = '10884521007819'
GROUP BY SERVICE_CODE, ICD10,[ICD10 DESCRIPTION], PHYSICIAN, [Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID], DATEPART(YYYY,[performdatewtime])
ORDER BY [POU ITEM]

-------------
update MT_POU_RPT_SUPPLY_COMPARISON_Y set PHYSICIAN_NAME=[ATPAR_MT].[MT_POU_PHYSICIAN].FIRST_NAME
+' ' + [ATPAR_MT].[MT_POU_PHYSICIAN].MIDDLE_INITIAL + ' '+[ATPAR_MT].[MT_POU_PHYSICIAN].LAST_NAME
from MT_POU_RPT_SUPPLY_COMPARISON_Y,[ATPAR_MT].[MT_POU_PHYSICIAN]
where MT_POU_RPT_SUPPLY_COMPARISON_Y.PHYSICIAN_ID=[ATPAR_MT].[MT_POU_PHYSICIAN].PHYSICIAN_ID


--select top 10000 * from MT_POU_RPT_SUPPLY_COMPARISON_Y
--------------------------------


--(UROLOGY, Z43.6,  , Z43.6, KOGAN, General Surgical Supply, 10884521007819, 1, 2016)
--(OTOLOGY, C79.2,  , C79.2, GALATI, General Surgical Supply, 7103, 1, 2016)
--(ORTHOPEDICS, S52.571A,  , S52.571A, MULLIGM, Surgical Implant, 212.818, 1, 2016)


--SELECT * FROM AMULYA WHERE   SERVICE_CODE = 'ORTHOPEDICS' AND ICD10 = 'M84.551A' AND PROCEDURE_CODE = 'ORFEMROD' AND PHYSICIAN = 'DICAPRM'  AND [POU ITEM] = '1210-6450s'
--GROUP BY SERVICE_CODE, ICD10, PROCEDURE_CODE, PHYSICIAN, [Group], [POU ITEM], DATEPART(YYYY,[performdatewtime])
--ORDER BY [POU ITEM]
--SELECT SERVICE_CODE,ICD10,PROCEDURE_CODE,PHYSICIAN,[Group], [POU ITEM],DIAGNOSIS_CODE_TYPE,ISNULL(COUNT(DISTINCT(COUNT1)),0),ISNULL(COUNT([POU ITEM]),0) NO_OF_ITEMS,[POU DESCRIPTION] FROM AMULYA
--GROUP BY
--SERVICE_CODE, ICD10 ,[CPT_CODE],  PROCEDURE_CODE, PHYSICIAN,[Group], [POU ITEM],DIAGNOSIS_CODE_TYPE,[POU DESCRIPTION]

--(ORTHOPEDICS, M84.551A,  , ORFEMROD, DICAPRM, Physician Preference, 1210-6450s, 1, 2016)
--(ORTHOPEDICS, M84.551A,  , M84.551A, DICAPRM, Physician Preference, 1210-6450s, 1, 2016)

--  DELETE FROM [Item_details] WHERE SERVICE_CODE = 'ORTHOPEDICS' AND ICD10 = 'M84.551A' AND PHYSICIAN = 'DICAPRM' AND [POU ITEM] = '1210-6450s'

--UPDATE [Item_details] SET [MHS MFGID] = '212.812' WHERE [POU ITEM] = '212.818'










--By PROCEDURE:


--MT_POU_RPT_SUPPLY_COMPARISON
--MT_POU_RPT_SUPPLY_COMPARISON_M

-------------------------
--ALTER TABLE [Item_details]
--ALTER COLUMN [ICD10] [nvarchar](255) NULL
---------------------


-- BY YEAR (176582)
	-- DELETE FROM MT_POU_RPT_SUPPLY_COMPARISON_Y (297404)
INSERT INTO MT_POU_RPT_SUPPLY_COMPARISON_Y
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[ITEM_GROUP]
,[ITEM_GROUP_DESCRIPTION]
,[ITEM_ID]
,[ITEM_DESCRIPTION]
,[MFR_CATALOG_NO]
,[UNIT_COST]
,[NO_OF_TIMES_ITEM_USED_BY_PHY]
,[YEAR])
SELECT SERVICE_CODE,
-- ' ' ICD10,' ' [CPT_CODE],
ISNULL(PROCEDURE_CODE, ' ') PROCEDURE_CODE, ISNULL(proc_descr,' ') PROCEDURE_DESCR , 3 AS 'DIAGNOSIS_CODE_TYPE',
--' ' ICD10_DESCR,' ' [CPT_DESCR], 
ISNULL(PHYSICIAN,' ') PHYSICIAN, ' ' PHYSICIAN_NAME,  
ISNULL([Group],''),ISNULL([Group],''), [POU ITEM], [POU DESCRIPTION], [MHS MFGID], AVG(ISNULL([CURRENTITEMCOST],0)) [CURRENTITEMCOST], 
ISNULL(SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])),0)  TOTAL_ITEM_QTY ,  
DATEPART(YYYY,[performdatewtime]) [YEAR] FROM [Item_details] 
WHERE [POU ITEM] IS NOT NULL 
AND PROC_OUTLIER_Y = 'N'
--AND SERVICE_CODE = 'UROLOGY' AND ICD10 = 'Z43.6' AND PHYSICIAN = 'KOGAN' AND [POU ITEM] = '10884521007819'
GROUP BY SERVICE_CODE, PROCEDURE_CODE,[proc_descr], PHYSICIAN, [Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID], DATEPART(YYYY,[performdatewtime])
ORDER BY [POU ITEM]

-------------

update MT_POU_RPT_SUPPLY_COMPARISON_Y set PHYSICIAN_NAME=[ATPAR_MT].[MT_POU_PHYSICIAN].FIRST_NAME
+' ' + [ATPAR_MT].[MT_POU_PHYSICIAN].MIDDLE_INITIAL + ' '+[ATPAR_MT].[MT_POU_PHYSICIAN].LAST_NAME
from MT_POU_RPT_SUPPLY_COMPARISON_Y,[ATPAR_MT].[MT_POU_PHYSICIAN]
where MT_POU_RPT_SUPPLY_COMPARISON_Y.PHYSICIAN_ID=[ATPAR_MT].[MT_POU_PHYSICIAN].PHYSICIAN_ID and MT_POU_RPT_SUPPLY_COMPARISON_Y.DIAGNOSIS_CODE_TYPE=3

UPDATE MT_POU_RPT_SUPPLY_COMPARISON_Y SET ITEM_GROUP = 'UNKNOWN' WHERE ITEM_GROUP IS NULL OR ITEM_GROUP = '' OR ITEM_GROUP = ' '
--------------------------------


--(UROLOGY, Z43.6,  , Z43.6, KOGAN, General Surgical Supply, 10884521007819, 1, 2016)
--(OTOLOGY, C79.2,  , C79.2, GALATI, General Surgical Supply, 7103, 1, 2016)
--(ORTHOPEDICS, S52.571A,  , S52.571A, MULLIGM, Surgical Implant, 212.818, 1, 2016)


--SELECT * FROM AMULYA WHERE   SERVICE_CODE = 'ORTHOPEDICS' AND ICD10 = 'M84.551A' AND PROCEDURE_CODE = 'ORFEMROD' AND PHYSICIAN = 'DICAPRM'  AND [POU ITEM] = '1210-6450s'
--GROUP BY SERVICE_CODE, ICD10, PROCEDURE_CODE, PHYSICIAN, [Group], [POU ITEM], DATEPART(YYYY,[performdatewtime])
--ORDER BY [POU ITEM]
--SELECT SERVICE_CODE,ICD10,PROCEDURE_CODE,PHYSICIAN,[Group], [POU ITEM],DIAGNOSIS_CODE_TYPE,ISNULL(COUNT(DISTINCT(COUNT1)),0),ISNULL(COUNT([POU ITEM]),0) NO_OF_ITEMS,[POU DESCRIPTION] FROM AMULYA
--GROUP BY
--SERVICE_CODE, ICD10 ,[CPT_CODE],  PROCEDURE_CODE, PHYSICIAN,[Group], [POU ITEM],DIAGNOSIS_CODE_TYPE,[POU DESCRIPTION]

--(ORTHOPEDICS, M84.551A,  , ORFEMROD, DICAPRM, Physician Preference, 1210-6450s, 1, 2016)
--(ORTHOPEDICS, M84.551A,  , M84.551A, DICAPRM, Physician Preference, 1210-6450s, 1, 2016)

--  DELETE FROM [Item_details] WHERE SERVICE_CODE = 'ORTHOPEDICS' AND ICD10 = 'M84.551A' AND PHYSICIAN = 'DICAPRM' AND [POU ITEM] = '1210-6450s'

--UPDATE [Item_details] SET [MHS MFGID] = '212.812' WHERE [POU ITEM] = '212.818'


