--Table creation script:
--drop table RPT_CASE_DATA

--select count(*) from RPT_CASE_DATA

DROP TABLE RPT_CASE_DATA_COST_VARIANCE

CREATE TABLE RPT_CASE_DATA_COST_VARIANCE
(CASE_DATA_UNIQUE_ID int identity (1,1),
[PROCEDURE_CODE] [nvarchar](50),
[SERVICE_CODE] [nvarchar](20) NULL,
[PHY_ID] [nvarchar](60) NULL,
[ITEM_COUNT] [float] NULL,
[ISSUE_QTY] [float] NULL,
[WASTAGE_QTY] [float] NULL,
RETURN_QTY [float] NULL,
ITEM_PRICE [float] NULL,
[PERFORM_DATE] [datetime] NULL,
[CASE_ID] [nvarchar](20) ,
[ITEM_ID] [nvarchar](50),
[ITEM_DESCRIPTION] [nvarchar](255) NULL,
[MFG_ITEM_ID] [nvarchar](50) NULL,
ENCOUNTER_ID [bigint] NULL,
[PATIENT_ID] [nvarchar](50) NULL,
)

--1497868 (ROWS)  1497868
INSERT INTO RPT_CASE_DATA_COST_VARIANCE (
[PROCEDURE_CODE],
[SERVICE_CODE] ,
[PHY_ID] ,
[ITEM_COUNT] ,
[ISSUE_QTY] ,
[WASTAGE_QTY] ,
RETURN_QTY,
ITEM_PRICE ,
[PERFORM_DATE],
[CASE_ID],
[ITEM_ID],
[ITEM_DESCRIPTION],
[MFG_ITEM_ID],
ENCOUNTER_ID,
[PATIENT_ID]
)
SELECT 
H.EXAM_ID,
CH.SERVICE_CODE,
H.PHYSICIAN_ID,
D.ITEM_COUNT,
D.ISSUE_QTY,
D.WASTAGE_QTY,
R.RETURN_QTY,
D.ITEM_PRICE,
CH.PERFORM_DATE,
H.CASE_ID,
D.ITEM_ID,
D.ITEM_DESCRIPTION,
D.MFG_ITEM_ID,
CH.ENCOUNTER_ID,
H.[PATIENT_ID]
FROM 
ATPAR_MT.MT_POU_CHARGECAPTURE_DETAILS D
JOIN ATPAR_MT.MT_POU_CHARGECAPTURE_HEADER H 
ON H.TRANSACTION_ID = D.TRANSACTION_ID
JOIN ATPAR_MT.MT_POU_CASE_CART_HEADER CH
ON CH.CASE_ID = H.CASE_ID
AND CH.PREF_LIST_ID = H.PREF_LIST_ID
AND CH.PROCEDURE_CODE = H.EXAM_ID
LEFT JOIN ATPAR_MT.MT_POU_CASE_CART_DETAILS CD
ON CD.CASE_ID = CH.CASE_ID
AND CD.PREF_LIST_ID = CH.PREF_LIST_ID
AND CD.PROCEDURE_CODE = CH.PROCEDURE_CODE
AND CD.ITEM_ID = D.ITEM_ID
LEFT JOIN ATPAR_MT.MT_POU_CHARGECAPTURE_RETURNS R
ON D.TRANSACTION_ID = R.TRANSACTION_ID 
AND D.LINE_NO = R.LINE_NO
WHERE CH.STATUS IN (10,50)

go

alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_PROC_OUTLIER_Y CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_PROC_OUTLIER_H CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_PROC_OUTLIER_Q CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_PROC_OUTLIER_M CHAR(1)

alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_ICD_OUTLIER_Y CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_ICD_OUTLIER_H CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_ICD_OUTLIER_Q CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_ICD_OUTLIER_M CHAR(1)

alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_CPT_OUTLIER_Y CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_CPT_OUTLIER_H CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_CPT_OUTLIER_Q CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add SINGLE_CPT_OUTLIER_M CHAR(1)

alter table RPT_CASE_DATA_COST_VARIANCE add PROC_OUTLIER_Y CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add PROC_OUTLIER_H CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add PROC_OUTLIER_Q CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add PROC_OUTLIER_M CHAR(1)

alter table RPT_CASE_DATA_COST_VARIANCE add ICD_OUTLIER_Y CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add ICD_OUTLIER_H CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add ICD_OUTLIER_Q CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add ICD_OUTLIER_M CHAR(1)

alter table RPT_CASE_DATA_COST_VARIANCE add CPT_OUTLIER_Y CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add CPT_OUTLIER_H CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add CPT_OUTLIER_Q CHAR(1)
alter table RPT_CASE_DATA_COST_VARIANCE add CPT_OUTLIER_M CHAR(1)

--DELETE PERFORM_DATE IS NULL

DELETE FROM RPT_CASE_DATA_COST_VARIANCE WHERE PERFORM_DATE IS NULL

update RPT_CASE_DATA_COST_VARIANCE set SERVICE_CODE='OTHERS' where SERVICE_CODE=''

-- Handling Physician ID with -(hyphen)--------------------------------------------------------------------

ALTER TABLE RPT_CASE_DATA_COST_VARIANCE ADD PHYSICIAN_NAME NVARCHAR(100)

--86322 --select * from RPT_CASE_DATA_COST_VARIANCE where PHY_ID like '%-%'
update RPT_CASE_DATA_COST_VARIANCE 
set PHYSICIAN_NAME = SUBSTRING(PHY_ID,(CHARINDEX('-',PHY_ID))+1,len(PHY_ID)),
PHY_ID = SUBSTRING(PHY_ID,0,CHARINDEX('-',PHY_ID,0))
where PHY_ID like '%-%'

---physician name update--------------------------------------------------------------------------------------------
update RPT_CASE_DATA_COST_VARIANCE set PHYSICIAN_NAME = [MT_POU_PHYSICIAN].FIRST_NAME
+' ' + [MT_POU_PHYSICIAN].MIDDLE_INITIAL + ' '+[MT_POU_PHYSICIAN].LAST_NAME
from RPT_CASE_DATA_COST_VARIANCE,[MT_POU_PHYSICIAN]
where RPT_CASE_DATA_COST_VARIANCE.PHY_ID= [MT_POU_PHYSICIAN].PHYSICIAN_ID

--------------------qty null handling-----------------------------------------------------------------------------

UPDATE RPT_CASE_DATA_COST_VARIANCE SET [ITEM_COUNT]= ISNULL([ITEM_COUNT],0),[WASTAGE_QTY]= ISNULL([WASTAGE_QTY],0),
[ITEM_PRICE]= ISNULL([ITEM_PRICE],0),[ISSUE_QTY]= ISNULL([ISSUE_QTY],0),[RETURN_QTY]= ISNULL([RETURN_QTY],0)

-- Multi pro cases elimination---------------------------------------------------------------------------------------------

DROP TABLE RPT_CASE_DATA_COST_VARIANCE_MULTI_PROC

SELECT SERVICE_CODE,PROCEDURE_CODE,CASE_ID INTO RPT_CASE_DATA_COST_VARIANCE_MULTI_PROC FROM RPT_CASE_DATA_COST_VARIANCE

ALTER TABLE RPT_CASE_DATA_COST_VARIANCE ADD MP_CASE VARCHAR(1) 

--SELECT TOP 10 * FROM RPT_CASE_DATA_COST_VARIANCE 

UPDATE RPT_CASE_DATA_COST_VARIANCE SET MP_CASE = 'Y' WHERE CASE_ID IN
(SELECT DISTINCT CASE_ID FROM RPT_CASE_DATA_COST_VARIANCE_MULTI_PROC GROUP BY CASE_ID HAVING COUNT(DISTINCT PROCEDURE_CODE)>1) 

UPDATE RPT_CASE_DATA_COST_VARIANCE SET MP_CASE = 'N' WHERE MP_CASE IS NULL

-- Need to mark QTY_OUTLIER-------------------------------------

ALTER TABLE RPT_CASE_DATA_COST_VARIANCE ADD QTY_OUTLIER VARCHAR(1) 

UPDATE RPT_CASE_DATA_COST_VARIANCE SET QTY_OUTLIER = 'Y' WHERE (ISSUE_QTY > 99 OR RETURN_QTY > 99 OR ITEM_COUNT > 99)

UPDATE RPT_CASE_DATA_COST_VARIANCE SET QTY_OUTLIER = 'N' WHERE QTY_OUTLIER IS NULL

-- ITM PRICE UPDATE
ALTER TABLE RPT_CASE_DATA_COST_VARIANCE ADD ITEM_GROUP VARCHAR(200) 

update RPT_CASE_DATA_COST_VARIANCE 
set RPT_CASE_DATA_COST_VARIANCE.ITEM_PRICE=Itemmasterfrominventoryteam22092017.[AMC UNIT COST],
RPT_CASE_DATA_COST_VARIANCE.ITEM_DESCRIPTION=Itemmasterfrominventoryteam22092017.[DESCRIPTION],
RPT_CASE_DATA_COST_VARIANCE.ITEM_GROUP = Itemmasterfrominventoryteam22092017.ITEM_GROUP
from Itemmasterfrominventoryteam22092017,RPT_CASE_DATA_COST_VARIANCE
where Itemmasterfrominventoryteam22092017.ITEM = RPT_CASE_DATA_COST_VARIANCE.ITEM_ID

-- TOTAL USAGE UPDATE

ALTER TABLE RPT_CASE_DATA_COST_VARIANCE ADD TOTAL_USAGE FLOAT

update RPT_CASE_DATA_COST_VARIANCE 
set TOTAL_USAGE= (((ISNULL(ITEM_COUNT,0) + ISNULL(ISSUE_QTY,0) + ISNULL(WASTAGE_QTY,0)) - ISNULL(RETURN_QTY,0)) * ITEM_PRICE)


-- TO ELIMINATE SINGLE PROC CASE

DROP TABLE SINGLE_PROC_CASES_Y
-------------------------------PROC-------------------------------------------------------
SELECT SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD
--,COUNT(PROCEDURE_CODE) 
,COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES INTO SINGLE_PROC_CASES_Y
FROM RPT_CASE_DATA_COST_VARIANCE
WHERE MP_CASE = 'N' AND QTY_OUTLIER = 'N'
GROUP BY SERVICE_CODE, PROCEDURE_CODE, PHY_ID,
DATEPART(YYYY,[PERFORM_DATE]) 
HAVING COUNT(DISTINCT(CASE_ID)) = 1
ORDER BY SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE])


UPDATE RPT_CASE_DATA_COST_VARIANCE SET SINGLE_PROC_OUTLIER_Y = 'Y' 
FROM RPT_CASE_DATA_COST_VARIANCE, SINGLE_PROC_CASES_Y
WHERE MP_CASE = 'N' AND QTY_OUTLIER = 'N'
AND RPT_CASE_DATA_COST_VARIANCE.SERVICE_CODE = SINGLE_PROC_CASES_Y.SERVICE_CODE
AND RPT_CASE_DATA_COST_VARIANCE.PROCEDURE_CODE = SINGLE_PROC_CASES_Y.PROCEDURE_CODE
AND RPT_CASE_DATA_COST_VARIANCE.PHY_ID=SINGLE_PROC_CASES_Y.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE) = SINGLE_PROC_CASES_Y.PERIOD

UPDATE RPT_CASE_DATA_COST_VARIANCE SET SINGLE_PROC_OUTLIER_Y = 'N' WHERE SINGLE_PROC_OUTLIER_Y IS NULL


-- ICD10 UPDATE


alter table RPT_CASE_DATA_COST_VARIANCE add ICD10 varchar(50)


--SELECT COUNT(*)
--from RPT_CASE_DATA_COST_VARIANCE,inpatient
--where RPT_CASE_DATA_COST_VARIANCE.ENCOUNTER_ID=inpatient.ECD
--and RPT_CASE_DATA_COST_VARIANCE.[PHY_ID]=inpatient.CaseIDToEncCrossWalkPhysician
--and datepart(yyyy,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(yyyy,Inpatient.PERFORM_DATE)
--and datepart(MM,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(MM,Inpatient.PERFORM_DATE)
--and datepart(DD,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(DD,Inpatient.PERFORM_DATE)

update RPT_CASE_DATA_COST_VARIANCE set ICD10=inpatient.[Primary ICD10 Procedure Code]
from RPT_CASE_DATA_COST_VARIANCE,inpatient
where RPT_CASE_DATA_COST_VARIANCE.ENCOUNTER_ID=inpatient.ECD
and RPT_CASE_DATA_COST_VARIANCE.[PHY_ID]=inpatient.CaseIDToEncCrossWalkPhysician
and datepart(yyyy,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(yyyy,Inpatient.PERFORM_DATE)
and datepart(MM,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(MM,Inpatient.PERFORM_DATE)
and datepart(DD,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(DD,Inpatient.PERFORM_DATE)



--SELECT COUNT(*)
--from RPT_CASE_DATA_COST_VARIANCE,inpatient
--where RPT_CASE_DATA_COST_VARIANCE.ENCOUNTER_ID=inpatient.ECD
--and RPT_CASE_DATA_COST_VARIANCE.[PHY_ID] = SUBSTRING(inpatient.Physician,0,CHARINDEX(',',inpatient.Physician,0))
--and datepart(yyyy,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(yyyy,Inpatient.PERFORM_DATE)
--and datepart(MM,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(MM,Inpatient.PERFORM_DATE)
--and datepart(DD,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(DD,Inpatient.PERFORM_DATE)
--AND RPT_CASE_DATA_COST_VARIANCE.ICD10 IS NULL


update RPT_CASE_DATA_COST_VARIANCE set ICD10=inpatient.[Primary ICD10 Procedure Code]
from RPT_CASE_DATA_COST_VARIANCE,inpatient
where RPT_CASE_DATA_COST_VARIANCE.ENCOUNTER_ID=inpatient.ECD
and RPT_CASE_DATA_COST_VARIANCE.[PHY_ID] = SUBSTRING(inpatient.Physician,0,CHARINDEX(',',inpatient.Physician,0))
and datepart(yyyy,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(yyyy,Inpatient.PERFORM_DATE)
and datepart(MM,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(MM,Inpatient.PERFORM_DATE)
and datepart(DD,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(DD,Inpatient.PERFORM_DATE)
AND RPT_CASE_DATA_COST_VARIANCE.ICD10 IS NULL


--SELECT COUNT(*)
--from RPT_CASE_DATA_COST_VARIANCE,inpatient
--where RPT_CASE_DATA_COST_VARIANCE.ENCOUNTER_ID=inpatient.ECD
--and RPT_CASE_DATA_COST_VARIANCE.[PHY_ID] = inpatient.Physician
--and datepart(yyyy,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(yyyy,Inpatient.PERFORM_DATE)
--and datepart(MM,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(MM,Inpatient.PERFORM_DATE)
--and datepart(DD,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(DD,Inpatient.PERFORM_DATE)
--AND RPT_CASE_DATA_COST_VARIANCE.ICD10 IS NULL

--SELECT TOP 10 * FROM Inpatient

--SELECT COUNT(*)
--from RPT_CASE_DATA_COST_VARIANCE,inpatient
--where RPT_CASE_DATA_COST_VARIANCE.ENCOUNTER_ID=inpatient.ECD
----and RPT_CASE_DATA_12072017.PERFORM_DATE=inpatient.PERFORM_DATE
--and datepart(yyyy,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(yyyy,Inpatient.PERFORM_DATE)
--and datepart(MM,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(MM,Inpatient.PERFORM_DATE)
--and datepart(DD,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE)=datepart(DD,Inpatient.PERFORM_DATE)

------------ICD------------------------

DROP TABLE SINGLE_ICD_CASES_Y

SELECT SERVICE_CODE, ICD10, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD
--,COUNT(PROCEDURE_CODE) 
,COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES INTO SINGLE_ICD_CASES_Y
FROM RPT_CASE_DATA_COST_VARIANCE
WHERE MP_CASE = 'N' AND QTY_OUTLIER = 'N'
GROUP BY SERVICE_CODE, ICD10, PHY_ID,
DATEPART(YYYY,[PERFORM_DATE]) 
HAVING COUNT(DISTINCT(CASE_ID)) = 1
ORDER BY SERVICE_CODE, ICD10, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE])


UPDATE RPT_CASE_DATA_COST_VARIANCE SET SINGLE_ICD_OUTLIER_Y = 'Y' 
FROM RPT_CASE_DATA_COST_VARIANCE,SINGLE_ICD_CASES_Y
WHERE MP_CASE = 'N' AND QTY_OUTLIER = 'N'
AND RPT_CASE_DATA_COST_VARIANCE.SERVICE_CODE = SINGLE_ICD_CASES_Y.SERVICE_CODE
AND RPT_CASE_DATA_COST_VARIANCE.ICD10 = SINGLE_ICD_CASES_Y.ICD10
AND RPT_CASE_DATA_COST_VARIANCE.PHY_ID=SINGLE_ICD_CASES_Y.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_COST_VARIANCE.PERFORM_DATE) = SINGLE_ICD_CASES_Y.PERIOD

UPDATE RPT_CASE_DATA_COST_VARIANCE SET SINGLE_ICD_OUTLIER_Y = 'N' WHERE SINGLE_ICD_OUTLIER_Y IS NULL


-- IMPORTANT: BEFORE THIS NEED TO RUN STANDARD DEVIATION LOGIC THEN RUN  OUTLIER UPDATE QUERY



--UPDATE RPT_CASE_DATA_COST_VARIANCE SET [ITEM_DESCRIPTION]= ISNULL([ITEM_DESCRIPTION],' '),
--[ITEM_ID]= ISNULL([ITEM_ID],' '),[CASE_ID]= ISNULL([CASE_ID],' '),
--[PROCEDURE_CODE]= ISNULL([PROCEDURE_CODE],' '),[PHY_ID]= ISNULL([PHY_ID],' '),
--[MFG_ITEM_ID]= ISNULL([MFG_ITEM_ID],' '),
--[SERVICE_CODE]= ISNULL([SERVICE_CODE],' ')


DELETE FROM Item_details

--1319981 (ROWS)
INSERT INTO Item_details(PROCEDURE_CODE,SERVICE_CODE,PHYSICIAN,SURGE_DESCIPTION_orig, TOTALCASEPICKQTY,[TOTAL IN ROOM QTY],[TOTAL WASTED],
TOTALRETURNED,CURRENTITEMCOST,performdatewtime,CASEID,[Group],[POU ITEM],[POU DESCRIPTION],[MHS MFGID],[PATIENT_ID],
ICD10,[ICD10 DESCRIPTION]
--,CPT1,CPT2,CPT3
,PROC_OUTLIER_Y, PROC_OUTLIER_H, PROC_OUTLIER_Q, PROC_OUTLIER_M
,ICD_OUTLIER_Y, ICD_OUTLIER_H, ICD_OUTLIER_Q, ICD_OUTLIER_M
,CPT_OUTLIER_Y, CPT_OUTLIER_H, CPT_OUTLIER_Q, CPT_OUTLIER_M)
SELECT PROCEDURE_CODE,SERVICE_CODE,PHY_ID,PHYSICIAN_NAME, ITEM_COUNT,ISSUE_QTY,WASTAGE_QTY,
RETURN_QTY,ITEM_PRICE,PERFORM_DATE,CASE_ID,ITEM_GROUP,ITEM_ID,ITEM_DESCRIPTION,MFG_ITEM_ID,[PATIENT_ID],
ICD10,ICD10
--,CPT1,CPT2,CPT3
,PROC_OUTLIER_Y, PROC_OUTLIER_H, PROC_OUTLIER_Q, PROC_OUTLIER_M
,ICD_OUTLIER_Y, ICD_OUTLIER_H, ICD_OUTLIER_Q, ICD_OUTLIER_M
,CPT_OUTLIER_Y, CPT_OUTLIER_H, CPT_OUTLIER_Q, CPT_OUTLIER_M 
FROM RPT_CASE_DATA_COST_VARIANCE WHERE MP_CASE = 'N' AND QTY_OUTLIER = 'N'

DELETE FROM Item_details WHERE performdatewtime IS NULL





