
--YEARLY BY PROC

select SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD
--,COUNT(PROCEDURE_CODE) 
,COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES INTO SINGLE_PROC_CASES_Y
from [dbo].[RPT_CASE_DATA_12072017]
group by SERVICE_CODE, PROCEDURE_CODE, PHY_ID,
DATEPART(YYYY,[PERFORM_DATE]) 
HAVING COUNT(DISTINCT(CASE_ID)) = 1
order by SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE])


UPDATE RPT_CASE_DATA_12072017 SET SINGLE_PROC_OUTLIER_Y = 'Y' FROM SINGLE_PROC_CASES_Y
WHERE RPT_CASE_DATA_12072017.SERVICE_CODE = SINGLE_PROC_CASES_Y.SERVICE_CODE
AND RPT_CASE_DATA_12072017.PROCEDURE_CODE = SINGLE_PROC_CASES_Y.PROCEDURE_CODE
AND RPT_CASE_DATA_12072017.PHY_ID=SINGLE_PROC_CASES_Y.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_PROC_CASES_Y.PERIOD

---------------

--YEARLY BY ICD

select SERVICE_CODE, ICD10, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD
--,COUNT(PROCEDURE_CODE) 
,COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES INTO SINGLE_ICD_CASES_Y
from [dbo].[RPT_CASE_DATA_12072017]
group by SERVICE_CODE, ICD10, PHY_ID,
DATEPART(YYYY,[PERFORM_DATE]) 
HAVING COUNT(DISTINCT(CASE_ID)) = 1
order by SERVICE_CODE, ICD10, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE])


UPDATE RPT_CASE_DATA_12072017 SET SINGLE_ICD_OUTLIER_Y = 'Y' FROM SINGLE_ICD_CASES_Y
WHERE RPT_CASE_DATA_12072017.SERVICE_CODE = SINGLE_ICD_CASES_Y.SERVICE_CODE
AND RPT_CASE_DATA_12072017.ICD10 = SINGLE_ICD_CASES_Y.ICD10
AND RPT_CASE_DATA_12072017.PHY_ID=SINGLE_ICD_CASES_Y.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_ICD_CASES_Y.PERIOD



-----------------


--QUARTERLY BY PROC

select SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD,
DATEPART(QUARTER,[PERFORM_DATE]) [QTR]
--,COUNT(PROCEDURE_CODE) 
,COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES INTO SINGLE_PROC_CASES_Q
from [dbo].[RPT_CASE_DATA_12072017]
--WHERE SERVICE_CODE = 'Anesthesia' AND PROCEDURE_CODE= 'PNRFALUM' AND PHY_ID = 'MOHSINI'
group by SERVICE_CODE, PROCEDURE_CODE, PHY_ID,
DATEPART(YYYY,[PERFORM_DATE]) , DATEPART(QUARTER,[PERFORM_DATE]) 
HAVING COUNT(DISTINCT(CASE_ID)) = 1
order by SERVICE_CODE, PROCEDURE_CODE, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]), DATEPART(QUARTER,[PERFORM_DATE])


UPDATE RPT_CASE_DATA_12072017 SET SINGLE_PROC_OUTLIER_Q = 'Y' FROM SINGLE_PROC_CASES_Q
WHERE RPT_CASE_DATA_12072017.SERVICE_CODE = SINGLE_PROC_CASES_Q.SERVICE_CODE
AND RPT_CASE_DATA_12072017.PROCEDURE_CODE = SINGLE_PROC_CASES_Q.PROCEDURE_CODE
AND RPT_CASE_DATA_12072017.PHY_ID=SINGLE_PROC_CASES_Q.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_PROC_CASES_Q.PERIOD
AND DATEPART(QUARTER,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_PROC_CASES_Q.[QTR]



--QUARTERLY BY ICD

select SERVICE_CODE, ICD10, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]) PERIOD,
DATEPART(QUARTER,[PERFORM_DATE]) [QTR]
--,COUNT(PROCEDURE_CODE) 
,COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES INTO SINGLE_ICD_CASES_Q
from [dbo].[RPT_CASE_DATA_12072017]
group by SERVICE_CODE, ICD10, PHY_ID,
DATEPART(YYYY,[PERFORM_DATE]) , DATEPART(QUARTER,[PERFORM_DATE]) 
HAVING COUNT(DISTINCT(CASE_ID)) = 1
order by SERVICE_CODE, ICD10, PHY_ID, 
DATEPART(YYYY,[PERFORM_DATE]), DATEPART(QUARTER,[PERFORM_DATE])


UPDATE RPT_CASE_DATA_12072017 SET SINGLE_PROC_OUTLIER_Q = 'Y' FROM SINGLE_ICD_CASES_Q
WHERE RPT_CASE_DATA_12072017.SERVICE_CODE = SINGLE_ICD_CASES_Q.SERVICE_CODE
AND RPT_CASE_DATA_12072017.ICD10 = SINGLE_ICD_CASES_Q.ICD10
AND RPT_CASE_DATA_12072017.PHY_ID=SINGLE_ICD_CASES_Q.PHY_ID
AND DATEPART(YYYY,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_ICD_CASES_Q.PERIOD
AND DATEPART(QUARTER,RPT_CASE_DATA_12072017.PERFORM_DATE) = SINGLE_ICD_CASES_Q.[QTR]


--VALIDATION

--select DATEPART(YYYY,[PERFORM_DATE]),DATEPART(QUARTER,[PERFORM_DATE]),
----SERVICE_CODE, PROCEDURE_CODE, PHY_ID, CASE_ID,
----DATEPART(YYYY,[PERFORM_DATE])
----,
--COUNT(DISTINCT(CASE_ID)) NO_OF_PROCEDURES
--from [dbo].[RPT_CASE_DATA_12072017]
--WHERE SERVICE_CODE = 'Anesthesia' AND PROCEDURE_CODE= 'PNRFALUM' AND PHY_ID = 'MOHSINI'
--GROUP BY DATEPART(YYYY,[PERFORM_DATE]),DATEPART(QUARTER,[PERFORM_DATE])