--By ICD


------------------COST VARIANCE BY SPECIALTY---------------------------
--DROP TABLE TEMP_PHYSICIAN_AVERAGE
--DROP TABLE TEMP

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP')
BEGIN
DROP TABLE TEMP
END



--TEMP TABLE:contains min max average usage among all physicians

--INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M

--BY QUARTER

-- SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M  WHERE [DIAGNOSIS_CODE_TYPE]=1
 DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M 
 WHERE [DIAGNOSIS_CODE_TYPE]=1
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M
		    ([SPECIALTY_CODE]
           ,[SPECIALTY_DESCRIPTION]
           ,[NO_OF_PROCEDURES]
           ,[NO_OF_PHYSICIANS]
           ,[TOTAL_SPEND]
           ,[TOTAL_VARIANCE]
		   ,[DIAGNOSIS_CODE_TYPE]
		   ,[MONTH]
           ,[YEAR])
SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION, SUM(NO_OF_PROCEDURES), SUM(NO_OF_PHYSICIANS) , 
		SUM([TOTAL_SPEND]), SUM([TOTAL_VARIANCE]),[DIAGNOSIS_CODE_TYPE],[MONTH], [YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M
WHERE DIAGNOSIS_CODE_TYPE = 1
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION, [DIAGNOSIS_CODE_TYPE],[MONTH],[YEAR]








--By PROCEDURE
------------------COST VARIANCE BY SPECIALTY---------------------------
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP')
BEGIN
DROP TABLE TEMP
END

--TEMP TABLE:contains min max average usage among all physicians


--BY YEAR
--  SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M WHERE DIAGNOSIS_CODE_TYPE=1
-- DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M WHERE DIAGNOSIS_CODE_TYPE=1

--DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M WHERE [DIAGNOSIS_CODE_TYPE]=3
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M
	([SPECIALTY_CODE]
	,[SPECIALTY_DESCRIPTION]
	,[NO_OF_PROCEDURES]
	,[NO_OF_PHYSICIANS]
	,[TOTAL_SPEND]
	,[TOTAL_VARIANCE]
	,[DIAGNOSIS_CODE_TYPE]
	,[MONTH]
	,[YEAR])
SELECT SPECIALTY_CODE,
SPECIALTY_DESCRIPTION, 
SUM(NO_OF_PROCEDURES), 
AVG(TEMP_PHYSICIAN_COUNT_TAB2_M1_PROC.NO_OF_PHYSICIANS) , 
SUM([TOTAL_SPEND]), 
SUM([TOTAL_VARIANCE]), 
DIAGNOSIS_CODE_TYPE, 
MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M.[MONTH],
MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M.[YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M,TEMP_PHYSICIAN_COUNT_TAB2_M1_PROC
WHERE DIAGNOSIS_CODE_TYPE = 3
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M.SPECIALTY_CODE= TEMP_PHYSICIAN_COUNT_TAB2_M1_PROC.SERVICE_CODE
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M.[YEAR]= TEMP_PHYSICIAN_COUNT_TAB2_M1_PROC.[YEAR] 
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION, DIAGNOSIS_CODE_TYPE,MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M.[YEAR],
MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M.[MONTH]

--select * from MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M



