/*  --------------------------------------------------------------------------------------------
	
	Author  : Ajay.S
	Date    :07/08/2017
	Purpose : CC360 new tables creation
 	
--------------------------------------------------------------------------------------------------	
*/	

IF object_id('ATPAR_SP_POU_RPT_TABLES_PATCH30') IS NOT NULL
DROP PROCEDURE ATPAR_SP_POU_RPT_TABLES_PATCH30
GO

CREATE PROCEDURE ATPAR_SP_POU_RPT_TABLES_PATCH30
AS
BEGIN

	DECLARE @intReturn int
	SET @intReturn = 0
	--De-normalized tables--

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_TRANS_CASEHEADER') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_TRANS_CASEHEADER](
	[CAPTURE_DATE_TIME] [datetime] NULL,
	[ACCOUNT_ID] [nvarchar](50) NULL,
	[EXAM_ID] [nvarchar](50) NULL,
	[COMMENTS] [nvarchar](1024) NULL,
	[REVIEWED] [bit] NULL,
	[MM_LAST_STATUS_DATE] [datetime] NULL,
	[MM_STATUS] [nvarchar](50) NULL,
	[CHARGE_LAST_STATUS_DATE] [datetime] NULL,
	[CHARGE_STATUS] [nvarchar](50) NULL,
	[REVIEW_USER_ID] [nvarchar](50) NULL,
	[REVIEW_DATE] [datetime] NULL,
	[PHYSICIAN_ID] [nvarchar](35) NULL,
	[REASON_CODE] [nvarchar](20) NULL,
	[OTHER_DEPTID] [nvarchar](50) NULL,
	[BED_NO] [nvarchar](50) NULL,
	[TRANSACTION_TYPE] [smallint] NULL,
	[HHT_TRANSACTION_ID] [bigint] NULL,
	[CASE_ID] [nvarchar](20) NOT NULL,
	[PATIENT_ID] [nvarchar](50) NULL,
	[DESCRIPTION] [nvarchar](254) NULL,
	[PREF_LIST_ID] [nvarchar](50) NOT NULL,
	[CCH_STATUS] [smallint] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[UPDATE_USER_ID] [nvarchar](20) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER_ID] [nvarchar](20) NULL,
	[ROOM_NO] [nvarchar](25) NOT NULL,
	[PERFORM_DATE] [datetime] NULL,
	[PROCEDURE_CODE] [nvarchar](50) NOT NULL,
	[EMERGENCY_CASE] [char](1) NOT NULL,
	[MERGED_CASE_ID] [nvarchar](20) NULL,
	[DEPT_ID] [nvarchar](50) NULL,
	[COST_CENTER_CODE] [nvarchar](20) NULL,
	[SERVICE_CODE] [nvarchar](20) NULL,
	[PROCESSED_FILE_TYPE] [smallint] NULL,
	[ENCOUNTER_ID] [bigint] NULL,
	[TRANSACTION_ID] [int] NOT NULL,
	[APP_ID] [smallint] NOT NULL,
	[ID] [nvarchar](50) NULL,
	[BUSINESS_UNIT] [nvarchar](50) NULL,
	[DESCR] [nvarchar](30) NULL,
	[STATUS] [smallint] NULL,
	[TOTAL_REC_DOWNLOADED] [smallint] NULL,
	[TOTAL_REC_SENT] [smallint] NULL,
	[STATUS_CODE] [int] NULL,
	[DOWNLOAD_DT_TIME] [datetime] NULL,
	[START_DT_TIME] [datetime] NULL,
	[END_DT_TIME] [datetime] NULL,
	[UPDATE_DT_TIME] [datetime] NULL,
	[USER_ID] [nvarchar](32) NULL,
	[DOWNLOAD_USERID] [nvarchar](20) NULL,
	[DEVICE_ID] [nvarchar](150) NULL,
	[SCANS_COUNT] [smallint] NULL,
	[REPORT_DATA_1] [nvarchar](20) NULL,
	[REPORT_DATA_2] [nvarchar](50) NULL,
	[REPORT_DATA_3] [nvarchar](20) NULL,
	[REPORT_DATA_4] [nvarchar](20) NULL,
	[REPORT_DATA_5] [nvarchar](20) NULL,
	[REPORT_DATA_6] [datetime] NULL,
	[REPORT_DATA_7] [datetime] NULL,
	[REPORT_DATA_8] [nvarchar](20) NULL,
	[REPORT_DATA_9] [real] NULL,
	[REPORT_DATA_10] [real] NULL,
	[REPORT_DATA_11] [real] NULL,
	[REPORT_DATA_12] [nvarchar](50) NULL,
	[CTH_ID] [bigint] NULL,
	[CTH_PREF_LIST_ID] [nvarchar](50) NULL,
	[CASE_STATUS] [smallint] NULL,
	[CTH_UPDATE_USER_ID] [nvarchar](50) NULL,
	[WORKSTATION_MAC_ADDRESS] [nvarchar](100) NULL,
	[CTH_UPDATE_DT_TIME] [datetime] NULL,
	[CASE_PICK_STATUS] [smallint] NULL,
	[CTH_TRANSACTION_ID] [int] NULL,
	[CHARGE_CAPTURE_TRANS_ID] [int] NULL,
	[CTH_COMMENTS] [nvarchar](250) NULL,
	[REASON_DESCRIPTION] [nvarchar](50) NULL,
	[PATIENT_ACCNUMBER] [nvarchar](20) NULL,
	[PATIENT_NAME] [nvarchar](150) NULL,
	[PATIENT_BEDNUMBER] [nvarchar](50) NULL
) ON [PRIMARY]
END

SET ANSI_PADDING OFF
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_TRANS_ISSUERETURNHEADER') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_TRANS_ISSUERETURNHEADER](
	[CAPTURE_DATE_TIME] [datetime] NULL,
	[ACCOUNT_ID] [nvarchar](50) NULL,
	[EXAM_ID] [nvarchar](50) NULL,
	[COMMENTS] [nvarchar](1024) NULL,
	[REVIEWED] [bit] NULL,
	[MM_LAST_STATUS_DATE] [datetime] NULL,
	[MM_STATUS] [nvarchar](50) NULL,
	[CHARGE_LAST_STATUS_DATE] [datetime] NULL,
	[CHARGE_STATUS] [nvarchar](50) NULL,
	[REVIEW_USER_ID] [nvarchar](50) NULL,
	[REVIEW_DATE] [datetime] NULL,
	[PHYSICIAN_ID] [nvarchar](35) NULL,
	[REASON_CODE] [nvarchar](20) NULL,
	[OTHER_DEPTID] [nvarchar](50) NULL,
	[BED_NO] [nvarchar](50) NULL,
	[TRANSACTION_TYPE] [smallint] NULL,
	[HHT_TRANSACTION_ID] [bigint] NULL,
	[TRANSACTION_ID] [int] NOT NULL,
	[APP_ID] [smallint] NOT NULL,
	[ID] [nvarchar](50) NULL,
	[BUSINESS_UNIT] [nvarchar](50) NULL,
	[DESCR] [nvarchar](30) NULL,
	[STATUS] [smallint] NULL,
	[TOTAL_REC_DOWNLOADED] [smallint] NULL,
	[TOTAL_REC_SENT] [smallint] NULL,
	[STATUS_CODE] [int] NULL,
	[DOWNLOAD_DT_TIME] [datetime] NULL,
	[START_DT_TIME] [datetime] NULL,
	[END_DT_TIME] [datetime] NULL,
	[UPDATE_DT_TIME] [datetime] NULL,
	[USER_ID] [nvarchar](32) NULL,
	[DOWNLOAD_USERID] [nvarchar](20) NULL,
	[DEVICE_ID] [nvarchar](150) NULL,
	[SCANS_COUNT] [smallint] NULL,
	[REPORT_DATA_1] [nvarchar](20) NULL,
	[REPORT_DATA_2] [nvarchar](50) NULL,
	[REPORT_DATA_3] [nvarchar](20) NULL,
	[REPORT_DATA_4] [nvarchar](20) NULL,
	[REPORT_DATA_5] [nvarchar](20) NULL,
	[REPORT_DATA_6] [datetime] NULL,
	[REPORT_DATA_7] [datetime] NULL,
	[REPORT_DATA_8] [nvarchar](20) NULL,
	[REPORT_DATA_9] [real] NULL,
	[REPORT_DATA_10] [real] NULL,
	[REPORT_DATA_11] [real] NULL,
	[REPORT_DATA_12] [nvarchar](50) NULL,
	[CTH_ID] [bigint] NULL,
	[CTH_PREF_LIST_ID] [nvarchar](50) NULL,
	[CASE_STATUS] [smallint] NULL,
	[CTH_UPDATE_USER_ID] [nvarchar](50) NULL,
	[WORKSTATION_MAC_ADDRESS] [nvarchar](100) NULL,
	[CTH_UPDATE_DT_TIME] [datetime] NULL,
	[CASE_PICK_STATUS] [smallint] NULL,
	[CTH_TRANSACTION_ID] [int] NULL,
	[CHARGE_CAPTURE_TRANS_ID] [int] NULL,
	[CTH_COMMENTS] [nvarchar](250) NULL,
	[REASON_DESCRIPTION] [nvarchar](50) NULL,
	[PATIENT_ACCNUMBER] [nvarchar](20) NULL,
	[PATIENT_NAME] [nvarchar](150) NULL,
	[PATIENT_BEDNUMBER] [nvarchar](50) NULL
) ON [PRIMARY]
END
SET ANSI_PADDING OFF
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_PROCEDURE_PREF_SETUP_DETAIL') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_PROCEDURE_PREF_SETUP_DETAIL](
	[PREF_LIST_ID] [nvarchar](50) NOT NULL,
	[ITEM_ID] [nvarchar](50) NOT NULL,
	[ITEM_DESCR] [nvarchar](255) NULL,
	[QUANTITY] [float] NULL,
	[STATUS] [bit] NULL,
	[UPDATE_DATE] [smalldatetime] NOT NULL,
	[UPDATE_USERID] [nvarchar](20) NOT NULL,
	[HOLD_QTY] [float] NOT NULL,
	[PROCEDURE_ID] [nvarchar](50) NOT NULL,
	[CUST_ITEM_NO] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[PREF_LIST_ID] ASC,
	[ITEM_ID] ASC,
	[PROCEDURE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_PROCEDURE_PREF_SETUP_HEADER') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_PROCEDURE_PREF_SETUP_HEADER](
	[PREF_LIST_ID] [nvarchar](50) NOT NULL,
	[PREF_LIST_DESCR] [nvarchar](50) NULL,
	[DEPARTMENT_ID] [nvarchar](50) NULL,
	[STATUS] [bit] NULL,
	[PROCEDURE_ID] [nvarchar](50) NOT NULL,
	[PHYSICIAN_ID] [nvarchar](30) NULL,
	[PROCEDURE_CODE] [nvarchar](20) NULL,
	[DESCRIPTION] [nvarchar](254) NOT NULL,
	[PC_STATUS] [bit] NOT NULL,
	[SPECIALTY_CODE] [nvarchar](20) NOT NULL,
	[SC_DESCRIPTION] [nvarchar](50) NOT NULL,
	[SC_STATUS] [bit] NOT NULL,
	[FIRST_NAME] [nvarchar](50) NULL,
	[LAST_NAME] [nvarchar](50) NULL,
	[MIDDLE_INITIAL] [nvarchar](20) NULL,
	[P_STATUS] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[PREF_LIST_ID] ASC,
	[PROCEDURE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_SETUP_DETAIL') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_SETUP_DETAIL](
	[CART_ID] [nvarchar](50) NOT NULL,
	[DEPARTMENT_ID] [nvarchar](50) NOT NULL,
	[WORKSTATION_ID] [nvarchar](100) NOT NULL,
	[BUSINESS_UNIT] [nvarchar](50) NOT NULL,
	[ORG_GROUP_ID] [nvarchar](50) NOT NULL,
	[LOCATION_TYPE] [nvarchar](1) NOT NULL DEFAULT (''),
	[PRIORITY] [int] NOT NULL,
 CONSTRAINT [PK_MT_RPT_POU_SETUP_DETAIL] PRIMARY KEY CLUSTERED 
(
	[CART_ID] ASC,
	[DEPARTMENT_ID] ASC,
	[WORKSTATION_ID] ASC,
	[BUSINESS_UNIT] ASC,
	[ORG_GROUP_ID] ASC,
	[LOCATION_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_SETUP_HEADER') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_SETUP_HEADER](
	[ORG_GROUP_ID] [nvarchar](20) NOT NULL,
	[BUSINESS_UNIT] [nvarchar](50) NOT NULL,
	[BU_TYPE] [nvarchar](1) NOT NULL,
	[USER_ID] [nvarchar](20) NOT NULL,
	[PASSHASH] [nvarchar](64) NULL,
	[FIRST_NAME] [nvarchar](20) NULL,
	[LAST_NAME] [nvarchar](20) NULL,
	[MIDDLE_INITIAL] [nvarchar](2) NULL,
	[EMAIL_ID] [nvarchar](50) NULL,
	[PHONE1] [nvarchar](15) NULL,
	[PHONE2] [nvarchar](15) NULL,
	[FAX] [nvarchar](15) NULL,
	[PAGER] [nvarchar](15) NULL,
	[HINT_QUESTION] [nvarchar](255) NULL,
	[HINT_ANSWER] [nvarchar](255) NULL,
	[CREATE_USER_ID] [nvarchar](20) NULL,
	[CREATE_DATE] [datetime] NULL,
	[PROFILE_ID] [nvarchar](30) NULL,
	[LDAP_USER] [nvarchar](1) NULL,
	[LDAP_ROLE] [nvarchar](50) NULL,
	[LDAP_ORG] [nvarchar](50) NULL,
	[USERDN] [nvarchar](512) NULL,
	[DEPT_ID] [nvarchar](50) NOT NULL,
	[DEPT_NAME] [nvarchar](50) NULL,
	[ATTN_TO] [nvarchar](30) NULL,
	[ADDRESS1] [nvarchar](55) NULL,
	[ADDRESS2] [nvarchar](55) NULL,
	[CITY] [nvarchar](30) NULL,
	[STATE] [nvarchar](20) NULL,
	[ZIP] [nvarchar](10) NULL,
	[COUNTRY] [nvarchar](50) NULL,
	[PHONE] [nvarchar](20) NULL,
	[E_MAIL] [nvarchar](300) NULL,
	[STATUS] [bit] NULL,
	[EXCP_APPROVAL_REQ] [char](1) NOT NULL,
	[INV_COORD_EMAIL] [nvarchar](300) NULL,
	[EXCP_APPROVER_EMAIL] [nvarchar](300) NULL,
	[REMINDER_FREQ] [smallint] NOT NULL,
	[RECALL_NOTIFICATION_EMAIL] [nvarchar](300) NULL,
	[INV_INTERFACE_ENABLE] [char](1) NULL,
	[BILLING_ENABLE] [char](1) NULL,
	[DEFAULT_PRINTER] [nvarchar](100) NULL,
	[DEFAULT_DISTRIBUTION_TYPE] [nvarchar](30) NULL,
	[DEFAULT_DESTINATION_LOCATION] [nvarchar](30) NULL,
	[ALERT_NOTIFY_REQ] [char](1) NOT NULL,
	[EMAIL_NOTIFY] [nvarchar](300) NULL,
	[CATEGORY_CODE] [nvarchar](50) NULL,
	[BILLONLY_BUSINESS_UNIT] [nvarchar](50) NULL,
	[BILLONLY_LOCATION] [nvarchar](50) NULL,
	[NO_OF_CASES_DOWNLOAD] [smallint] NOT NULL,
	[SEND_LOWSTOCK_EMAIL_ALERTS] [char](1) NOT NULL,
	[EMAILID_FOR_LOWSTOCK_ALERTS] [nvarchar](300) NULL,
	[SEND_PRODUCT_EXP_EMAIL_ALERTS] [char](1) NOT NULL,
	[EMAILID_FOR_PRODUCT_EXP_ALERTS] [nvarchar](300) NULL,
	[DURATION_TRACKING_EXP] [smallint] NULL,
	[PERCENTAGE_OPTIMUM_QTY] [smallint] NULL,
	[PREPICK_QA_PROCESS_REQUIRED] [bit] NOT NULL,
	[BUYER_ID] [nvarchar](100) NULL,
	[AUTO_PUTAWAY_ENABLED] [char](1) NOT NULL,
	[ALLOW_LOC_SELECT] [bit] NOT NULL,
	[CASE_PICK_STATUS] [smallint] NOT NULL,
	[HOME_DEPARTMENT] [bit] NULL,
 CONSTRAINT [PK_MT_RPT_POU_SETUP_HEADER] PRIMARY KEY CLUSTERED 
(
	[ORG_GROUP_ID] ASC,
	[BUSINESS_UNIT] ASC,
	[USER_ID] ASC,
	[DEPT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
SET ANSI_PADDING OFF
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_TRANS_DETAIL') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_TRANS_DETAIL](
	[ITEM_ID] [nvarchar](50) NOT NULL DEFAULT (' '),
	[LINE_NO] [int] NOT NULL DEFAULT (' '),
	[ITEM_DESCRIPTION] [nvarchar](255) NULL,
	[ITEM_LOTNUMBER] [nvarchar](30) NULL,
	[ITEM_SRNUMBER] [nvarchar](30) NULL,
	[ITEM_COUNT] [float] NULL,
	[WASTAGE_QTY] [float] NULL,
	[TRANSACTION_ID] [bigint] NOT NULL DEFAULT (' '),
	[CART_ID] [nvarchar](50) NULL,
	[ITEM_COUNT_MM] [float] NULL,
	[UPDATE_USER_ID] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[ITEM_PRICE] [float] NULL,
	[CHARGE_CODE] [nvarchar](50) NULL,
	[BUSINESS_UNIT] [nvarchar](50) NULL,
	[COMPARTMENT] [nvarchar](50) NULL,
	[CART_NONCART_FLAG] [char](2) NULL,
	[UOM] [nvarchar](20) NULL,
	[BILL_STATUS] [char](1) NULL,
	[MM_STATUS] [char](2) NULL,
	[ORDERING_TYPE] [char](2) NULL,
	[ORDER_NO] [int] NULL,
	[BILLED_QTY] [float] NULL,
	[HOLD_QTY] [int] NOT NULL,
	[ITEM_INVENTORY] [nvarchar](10) NULL,
	[STORAGE_AREA] [nvarchar](50) NULL,
	[STORAGE_LEVEL_1] [nvarchar](4) NULL,
	[STORAGE_LEVEL_2] [nvarchar](4) NULL,
	[STORAGE_LEVEL_3] [nvarchar](4) NULL,
	[STORAGE_LEVEL_4] [nvarchar](4) NULL,
	[MFG_ITEM_ID] [nvarchar](50) NULL,
	[UPC_ID] [nvarchar](50) NULL,
	[GTIN] [nvarchar](50) NULL,
	[VEND_ITEM_ID] [nvarchar](50) NULL,
	[CUST_ITEM_NO] [nvarchar](50) NULL,
	[ISSUE_QTY] [float] NULL,
	[TOTE_NO] [nvarchar](50) NULL,
	[ITEM_TYPE] [smallint] NULL,
	[EXPIRY_DATE] [datetime] NULL,
	[CREATE_DATE_TIME] [datetime] NULL,
	[MANUFACTURER] [nvarchar](50) NULL,
	[VENDOR_ID] [nvarchar](50) NULL,
	[PHY_ID] [nvarchar](60) NULL,
	[PREF_ID] [nvarchar](100) NULL,
	[PROC_ID] [nvarchar](100) NULL,
	[ADJUSTED_QTY] [float] NULL,
	[TYPE_OF_ITEM] [int] NULL,
	[ISSUE_ADJ_QTY] [float] NULL,
	[RETURN_ID] [bigint] NULL DEFAULT ((1)),
	[REASON_CODE] [nvarchar](20) NULL,
	[COMMENTS] [nvarchar](1024) NULL,
	[RETURN_QTY] [float] NULL,
	[CCR_WASTAGE_QTY] [float] NULL,
	[CCR_UPDATE_DATE] [datetime] NULL,
	[USER_ID] [nvarchar](50) NULL,
	[CASE_ID] [nvarchar](20) NULL DEFAULT (' '),
	[ITEM_DESCR] [varchar](255) NULL,
	[PICK_QTY] [float] NULL,
	[CSCD_HOLD_QTY] [float] NULL,
	[CSCD_ITEM_INVENTORY] [nvarchar](50) NULL,
	[ITEM_UOM] [nvarchar](20) NULL,
	[STATUS] [smallint] NULL,
	[ACT_OPEN_QTY] [float] NULL,
	[ACT_HOLD_QTY] [float] NULL,
	[QTY] [float] NULL,
	[CSCD_CUST_ITEM_NO] [nvarchar](50) NULL,
	[ITEM_SOURCE] [smallint] NULL,
	[ITEM_STATUS] [nvarchar](1) NULL
) ON [PRIMARY]
END

SET ANSI_PADDING OFF
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_TRANS_DETAIL2') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_TRANS_DETAIL2](
	[CART_ID] [nvarchar](50) NULL,
	[ITEM_ID] [nvarchar](50) NULL,
	[ITEM_QUANTITY_PAR] [float] NULL,
	[ITEM_QUANTITY_ON_HAND] [float] NULL,
	[BUSINESS_UNIT] [nvarchar](50) NULL,
	[LOT_NUMBER] [nvarchar](50) NULL,
	[SERIAL_NUMBER] [nvarchar](50) NULL,
	[EXPIRY_DATE] [datetime] NULL,
	[ACTUAL_QUANTITY] [float] NULL,
	[COMPARTMENT] [nvarchar](50) NULL DEFAULT (''),
	[ID] [bigint] NULL,
	[EVENT_TYPE] [smallint] NULL,
	[UPDATE_DATE] [datetime] NULL,
	[QTY] [float] NULL,
	[ON_HAND_QTY] [float] NULL,
	[TRANSACTION_ID] [int] NOT NULL,
	[ADJUSTMENT_TYPE] [int] NULL,
	[CHARGE_CAPTURE_TRANS_ID] [int] NULL,
	[CYCT_DATE_TIME] [datetime] NULL,
	[ORIGINAL_QUANTITY] [float] NULL,
	[NEW_QUANTITY] [float] NULL,
	[ITEM_PRICE] [float] NULL,
	[UOM] [nvarchar](20) NULL,
	[ORDER_ID] [bigint] NULL,
	[PTWY_DATE_TIME] [datetime] NULL,
	[QUANTITY_ORDERED] [float] NULL,
	[QUANTITY_RECEIVED] [float] NULL
) ON [PRIMARY]
END
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_TRANS_HEADER2') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_TRANS_HEADER2](
	[ORDER_NO] [int] NOT NULL,
	[ORG_ID] [nvarchar](10) NOT NULL,
	[PAR_LOC_ID] [nvarchar](50) NOT NULL,
	[ORDER_DATE] [datetime] NOT NULL,
	[CREATE_USER] [nvarchar](50) NULL,
	[VENDOR_ID] [nvarchar](20) NOT NULL,
	[ERP_ORDER_NO] [nvarchar](30) NULL,
	[APP_ID] [int] NOT NULL,
	[COMMENTS] [nvarchar](4000) NULL,
	[INVENTORYORDER_FLAG] [nvarchar](1) NULL,
	[PTWY_DATE_TIME] [datetime] NULL,
	[CYCT_DATE_TIME] [datetime] NULL,
) ON [PRIMARY]
END

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
	
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id(N'MT_RPT_POU_FIELDS_LIST') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
CREATE TABLE [MT_RPT_POU_FIELDS_LIST](
	[APP_ID] [int] NOT NULL,
	[REPORT_TABLE_NAME] [nvarchar](100) NULL,
	[ATPAR_APPLICATION_TABLE] [nvarchar](100) NULL,
	[ATPAR_TABLE_COLUMN] [nvarchar](100) NULL,
	[REPORT_FRIENDLY_COLUMN_NAME] [nvarchar](100) NULL,
	[DATA_TYPE] [nvarchar](100) NULL,
	[ERP_TYPE] [nvarchar](50) NULL
) ON [PRIMARY]
END




	--OPIMIZATION BY SPECIALTY
	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_SPECIALTY_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_SPECIALTY_M](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL	
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PREF_LISTS [bigint] NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_SPECIALTY_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_SPECIALTY_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_SPECIALTY_Q](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL	
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PREF_LISTS [bigint] NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_SPECIALTY_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			  [PERIOD] ASC,
		     [YEAR] ASC	
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END
	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_SPECIALTY_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_SPECIALTY_H](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PREF_LISTS [bigint] NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_SPECIALTY_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 [PERIOD] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END
	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_SPECIALTY_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_SPECIALTY_Y](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL	
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PREF_LISTS [bigint] NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_SPECIALTY_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

--OPIMIZATION BY PROCEDURE
	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PROCEDURE_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PROCEDURE_M](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PHYSICIANS [bigint] NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PREF_LISTS [bigint] NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PROCEDURE_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			  [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PROCEDURE_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PROCEDURE_Q](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PHYSICIANS [bigint] NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PREF_LISTS [bigint] NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PROCEDURE_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			  [PERIOD] ASC,
		     [YEAR] ASC	
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PROCEDURE_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PROCEDURE_H](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PHYSICIANS [bigint] NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PREF_LISTS [bigint] NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PROCEDURE_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			  [PERIOD] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PROCEDURE_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PROCEDURE_Y](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PHYSICIANS [bigint] NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PREF_LISTS [bigint] NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PROCEDURE_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	--OPIMIZATION BY PHYSICIAN
	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PHYSICIAN_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN	
		CREATE TABLE [MT_POU_RPT_OPT_BY_PHYSICIAN_M](
		 SPECIALTY_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PROCEDURES [bigint] NULL		
		,PREF_LIST_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PREF_LIST_DESCRIPTION [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PHYSICIAN_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 PHYSICIAN_ID ASC,
			 PREF_LIST_ID ASC,
			 [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PHYSICIAN_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PHYSICIAN_Q](
		 SPECIALTY_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PROCEDURES [bigint] NULL		
		,PREF_LIST_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PREF_LIST_DESCRIPTION [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PHYSICIAN_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 PHYSICIAN_ID ASC,
			 PREF_LIST_ID ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PHYSICIAN_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PHYSICIAN_H](
		 SPECIALTY_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PROCEDURES [bigint] NULL		
		,PREF_LIST_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PREF_LIST_DESCRIPTION [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
	    ,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PHYSICIAN_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 PHYSICIAN_ID ASC,
			 PREF_LIST_ID ASC,
			 [PERIOD] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PHYSICIAN_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PHYSICIAN_Y](
		 SPECIALTY_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_PROCEDURES [bigint] NULL		
		,PREF_LIST_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PREF_LIST_DESCRIPTION [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,EFFICIENCY_PERCENTAGE [float] NULL
		,TOTAL_PICKED_QTY [float] NULL
		,TOTAL_PICKED_VALUE [float] NULL
		,TOTAL_ISSUED_EXISTING_QTY [float] NULL
		,TOTAL_ISSUED_EXISTING_VALUE [float] NULL
		,TOTAL_ISSUED_NEW_QTY [float] NULL
		,TOTAL_ISSUED_NEW_VALUE [float] NULL
		,TOTAL_RETURN_QTY [float] NULL
		,TOTAL_RETURN_VALUE [float] NULL
		,TOTAL_WASTED_QTY [float] NULL
		,TOTAL_WASTED_VALUE [float] NULL
		,TOTAL_USAGE [float] NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PHYSICIAN_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 PHYSICIAN_ID ASC,
			 PREF_LIST_ID ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	--OPIMIZATION BY PREFERENCE
	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PREFERENCE_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PREFERENCE_M](
		 SPECIALTY_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PREF_LIST_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,ITEM_PRICE [float] NULL
		,CURRENT_OPEN_QTY [float] NULL
		,CURRENT_HOLD_QTY [float] NULL
		,[MAX_USAGE] [float] NULL
		,[MIN_USAGE] [float] NULL
		,MEAN_USAGE [float] NULL
		,USAGE_PER [float] NULL
		,SUGGESTED_OPEN_QTY [float] NULL
		,SUGGESTED_HOLD_QTY [float] NULL
		,NET_CHANGE_OPEN_QTY [float] NULL
		,NET_CHANGE_HOLD_QTY [float] NULL
		,NET_CHANGE_OPEN_VALUE [float] NULL
		,NET_CHANGE_HOLD_VALUE [float] NULL
		,ITEM_TYPE [int]
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PREFERENCE_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 PREF_LIST_ID ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_ID ASC,
			 [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PREFERENCE_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PREFERENCE_Q](
		 SPECIALTY_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PREF_LIST_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,ITEM_PRICE [float] NULL
		,CURRENT_OPEN_QTY [float] NULL
		,CURRENT_HOLD_QTY [float] NULL
		,[MAX_USAGE] [float] NULL
		,[MIN_USAGE] [float] NULL
		,MEAN_USAGE [float] NULL
		,USAGE_PER [float] NULL
		,SUGGESTED_OPEN_QTY [float] NULL
		,SUGGESTED_HOLD_QTY [float] NULL
		,NET_CHANGE_OPEN_QTY [float] NULL
		,NET_CHANGE_HOLD_QTY [float] NULL
		,NET_CHANGE_OPEN_VALUE [float] NULL
		,NET_CHANGE_HOLD_VALUE [float] NULL
		,ITEM_TYPE [int]
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PREFERENCE_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 PREF_LIST_ID ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_ID ASC,
			 [PERIOD] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PREFERENCE_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PREFERENCE_H](
		 SPECIALTY_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PREF_LIST_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,ITEM_PRICE [float] NULL
		,CURRENT_OPEN_QTY [float] NULL
		,CURRENT_HOLD_QTY [float] NULL
		,[MAX_USAGE] [float] NULL
		,[MIN_USAGE] [float] NULL
		,MEAN_USAGE [float] NULL
		,USAGE_PER [float] NULL
		,SUGGESTED_OPEN_QTY [float] NULL
		,SUGGESTED_HOLD_QTY [float] NULL
		,NET_CHANGE_OPEN_QTY [float] NULL
		,NET_CHANGE_HOLD_QTY [float] NULL
		,NET_CHANGE_OPEN_VALUE [float] NULL
		,NET_CHANGE_HOLD_VALUE [float] NULL
		,ITEM_TYPE [int]
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PREFERENCE_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 PREF_LIST_ID ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_ID ASC,
			 [PERIOD] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_OPT_BY_PREFERENCE_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_OPT_BY_PREFERENCE_Y](
		 SPECIALTY_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PROCEDURE_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PREF_LIST_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,ITEM_PRICE [float] NULL
		,CURRENT_OPEN_QTY [float] NULL
		,CURRENT_HOLD_QTY [float] NULL
		,MAX_USAGE [float] NULL
		,MIN_USAGE [float] NULL
		,MEAN_USAGE [float] NULL
		,USAGE_PER [float] NULL
		,SUGGESTED_OPEN_QTY [float] NULL
		,SUGGESTED_HOLD_QTY [float] NULL
		,NET_CHANGE_OPEN_QTY [float] NULL
		,NET_CHANGE_HOLD_QTY [float] NULL
		,NET_CHANGE_OPEN_VALUE [float] NULL
		,NET_CHANGE_HOLD_VALUE [float] NULL
		,ITEM_TYPE [int]
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_OPT_BY_PREFERENCE_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 PROCEDURE_CODE ASC,
			 PREF_LIST_ID ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_ID ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	----cost variance analysis----------
	
	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PHYSICIANS [bigint] NULL --ADDED FOR pHYSICIAN BENCH MARK
		,TOTAL_SPEND [float] NULL
		,TOTAL_VARIANCE [float] NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL		
		CONSTRAINT [PK_MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PHYSICIANS [bigint] NULL --ADDED FOR pHYSICIAN BENCH MARK
		,TOTAL_SPEND [float] NULL
		,TOTAL_VARIANCE [float] NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL		
		CONSTRAINT [PK_MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [PERIOD] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_H](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PHYSICIANS [bigint] NULL  --ADDED FOR pHYSICIAN BENCH MARK
		,TOTAL_SPEND [float] NULL
		,TOTAL_VARIANCE [float] NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL
		,[PERIOD] [int] NOT NULL
		,[YEAR] [int] NOT NULL		
		CONSTRAINT [PK_MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [PERIOD] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE [MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y](
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL	
		,NO_OF_PROCEDURES [bigint] NULL
		,NO_OF_PHYSICIANS [bigint] NULL  --ADDED FOR pHYSICIAN BENCH MARK
		,TOTAL_SPEND [float] NULL
		,TOTAL_VARIANCE [float] NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL
		,[YEAR] [int] NOT NULL		
		CONSTRAINT [PK_MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	--COST VARIANCE BY REIMBURSEMENT CODE
-- 3-PROCEDURE, 1-ICD, 2-CPT
	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M(

		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL		
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,NO_OF_PHYSICIANS [bigint] NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,MAX_USAGE [float] NULL
		,MIN_USAGE [float] NULL
		,TOTAL_VARIANCE [float] NULL
		,TOTAL_SPEND [float] NULL
		,TOTAL_ANNUAL_SPEND [float] NULL
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL		

		CONSTRAINT [PK_MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q(

		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,NO_OF_PHYSICIANS [bigint] NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,MAX_USAGE [float] NULL
		,MIN_USAGE [float] NULL
		,TOTAL_VARIANCE [float] NULL
		,TOTAL_SPEND [float] NULL
		,TOTAL_ANNUAL_SPEND [float] NULL
		,PERIOD [int] NOT NULL
		,[YEAR] [int] NOT NULL		

		CONSTRAINT [PK_MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_H(

		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,NO_OF_PHYSICIANS [bigint] NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,MAX_USAGE [float] NULL
		,MIN_USAGE [float] NULL
		,TOTAL_VARIANCE [float] NULL
		,TOTAL_SPEND [float] NULL
		,TOTAL_ANNUAL_SPEND [float] NULL
		,PERIOD [int] NOT NULL
		,[YEAR] [int] NOT NULL		

		CONSTRAINT [PK_MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,[SPECIALTY_DESCRIPTION] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,NO_OF_PHYSICIANS [bigint] NULL
		,NO_OF_PROCEDURES [bigint] NULL
		,MAX_USAGE [float] NULL
		,MIN_USAGE [float] NULL
		,TOTAL_VARIANCE [float] NULL
		,TOTAL_SPEND [float] NULL
		,TOTAL_ANNUAL_SPEND [float] NULL
		,[YEAR] [int] NOT NULL

		CONSTRAINT [PK_MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END


	--EXTENDED VARIANCE BY SERGEON

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_M(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL		
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,NO_OF_PROCEDURES [bigint] NULL
		,MIN_PROC_COST [float] NULL
		,MAX_PROC_COST [float] NULL 
		,AVG_PROC_COST [float] NULL
		,TOTAL_SPEND [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,PER_VAR_TOTAL_SPEND [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,PHYSICIAN_RANK INT NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[NO_OF_PHY_DEPT] [int] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[NO_OF_PROCS_DEPT] [int] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[LOW_COST_AVG_DEPT] [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,MIN_PROC_VARIANCE [float] NULL
		,EXTENDED_VARIANCE [float] NULL
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL		

		CONSTRAINT [PK_MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

		IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Q(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL		
		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,NO_OF_PROCEDURES [bigint] NULL
		,MIN_PROC_COST [float] NULL
		,MAX_PROC_COST [float] NULL 
		,AVG_PROC_COST [float] NULL
		,TOTAL_SPEND [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,PER_VAR_TOTAL_SPEND [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,PHYSICIAN_RANK INT NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[NO_OF_PHY_DEPT] [int] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[NO_OF_PROCS_DEPT] [int] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[LOW_COST_AVG_DEPT] [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,MIN_PROC_VARIANCE [float] NULL
		,EXTENDED_VARIANCE [float] NULL
		,PERIOD [int] NOT NULL
		,[YEAR] [int] NOT NULL		

		CONSTRAINT [PK_MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

		IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,NO_OF_PROCEDURES [bigint] NULL
		,MIN_PROC_COST [float] NULL
		,MAX_PROC_COST [float] NULL 
		,AVG_PROC_COST [float] NULL
		,TOTAL_SPEND [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,PER_VAR_TOTAL_SPEND [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,PHYSICIAN_RANK INT NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[NO_OF_PHY_DEPT] [int] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[NO_OF_PROCS_DEPT] [int] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[LOW_COST_AVG_DEPT] [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,MIN_PROC_VARIANCE [float] NULL
		,EXTENDED_VARIANCE [float] NULL
		,PERIOD [int] NOT NULL
		,[YEAR] [int] NOT NULL		

		CONSTRAINT [PK_MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

		IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,NO_OF_PROCEDURES [bigint] NULL
		,MIN_PROC_COST [float] NULL
		,MAX_PROC_COST [float] NULL 
		,AVG_PROC_COST [float] NULL
		,TOTAL_SPEND [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,PER_VAR_TOTAL_SPEND [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,PHYSICIAN_RANK INT NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[NO_OF_PHY_DEPT] [int] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[NO_OF_PROCS_DEPT] [int] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,[LOW_COST_AVG_DEPT] [float] NULL --ADDED FOR PHYSICIAN BENCH MARK
		,MIN_PROC_VARIANCE [float] NULL 
		,EXTENDED_VARIANCE [float] NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	--SPEND BY GROUP (SPEND BY ITEM CATEGORY)

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_SPEND_BY_GROUP_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_SPEND_BY_GROUP_M(

		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_ITEMS_BY_ITEM_GROUP [bigint] NULL
		,ITEM_GROUP [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL		
		,TOTAL_NO_OF_CASES_PHYSICIAN [bigint] NULL
		,TOTAL_COST_ITEM_GROUP [float] NULL
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_SPEND_BY_GROUP_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_GROUP ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_SPEND_BY_GROUP_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_SPEND_BY_GROUP_Q(

		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_ITEMS_BY_ITEM_GROUP [bigint] NULL
		,ITEM_GROUP [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	
		,TOTAL_NO_OF_CASES_PHYSICIAN [bigint] NULL
		,TOTAL_COST_ITEM_GROUP [float] NULL
		,PERIOD [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_SPEND_BY_GROUP_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_GROUP ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_SPEND_BY_GROUP_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_SPEND_BY_GROUP_H(

		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_ITEMS_BY_ITEM_GROUP [bigint] NULL
		,ITEM_GROUP [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP_DESCRIPTION [nvarchar](255)COLLATE SQL_Latin1_General_CP1_CI_AS NULL	
		,TOTAL_NO_OF_CASES_PHYSICIAN [bigint] NULL
		,TOTAL_COST_ITEM_GROUP [float] NULL
		,PERIOD [int] NOT NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_SPEND_BY_GROUP_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_GROUP ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_SPEND_BY_GROUP_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_SPEND_BY_GROUP_Y(

		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,NO_OF_ITEMS_BY_ITEM_GROUP [bigint] NULL
		,ITEM_GROUP [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL	
		,TOTAL_NO_OF_CASES_PHYSICIAN [bigint] NULL
		,TOTAL_COST_ITEM_GROUP [float] NULL
		,[YEAR] [int] NOT NULL
		CONSTRAINT [PK_MT_POU_RPT_SPEND_BY_GROUP_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_GROUP ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	--SUPPLY BY COMPARISON (SUPPLY DETAILS)

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_SUPPLY_COMPARISON_M]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_SUPPLY_COMPARISON_M(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,ITEM_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,MFR_CATALOG_NO [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,UNIT_COST [float] NULL
		,NO_OF_TIMES_ITEM_USED_BY_PHY [bigint] NULL
		,[MONTH] [int] NOT NULL
		,[YEAR] [int] NOT NULL	
		CONSTRAINT [PK_MT_POU_RPT_SUPPLY_COMPARISON_M] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_GROUP ASC,
			 ITEM_ID ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [MONTH] ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_SUPPLY_COMPARISON_Q]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_SUPPLY_COMPARISON_Q(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,ITEM_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,MFR_CATALOG_NO [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,UNIT_COST [float] NULL
		,NO_OF_TIMES_ITEM_USED_BY_PHY [bigint] NULL
		,PERIOD [int] NOT NULL
		,[YEAR] [int] NOT NULL	
		CONSTRAINT [PK_MT_POU_RPT_SUPPLY_COMPARISON_Q] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_GROUP ASC,
			 ITEM_ID ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_SUPPLY_COMPARISON_H]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_SUPPLY_COMPARISON_H(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,ITEM_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,MFR_CATALOG_NO [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,UNIT_COST [float] NULL
		,NO_OF_TIMES_ITEM_USED_BY_PHY [bigint] NULL
		,PERIOD [int] NOT NULL
		,[YEAR] [int] NOT NULL	
		CONSTRAINT [PK_MT_POU_RPT_SUPPLY_COMPARISON_H] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_GROUP ASC,
			 ITEM_ID ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 PERIOD ASC,
		     [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	IF NOT EXISTS (select * from dbo.sysobjects where id = object_id(N'[MT_POU_RPT_SUPPLY_COMPARISON_Y]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
	BEGIN
		CREATE TABLE MT_POU_RPT_SUPPLY_COMPARISON_Y(
		[SPECIALTY_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_DESCRIPTION [nvarchar](254) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,DIAGNOSIS_CODE_TYPE INT NOT NULL		
		,PHYSICIAN_ID [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,PHYSICIAN_NAME [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_GROUP_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,ITEM_ID [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
		,ITEM_DESCRIPTION [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,MFR_CATALOG_NO [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
		,UNIT_COST [float] NULL
		,NO_OF_TIMES_ITEM_USED_BY_PHY [bigint] NULL
		,[YEAR] [int] NOT NULL	
		CONSTRAINT [PK_MT_POU_RPT_SUPPLY_COMPARISON_Y] PRIMARY KEY CLUSTERED 
		  (
			 SPECIALTY_CODE ASC,
			 DIAGNOSIS_CODE ASC,
			 PHYSICIAN_ID ASC,
			 ITEM_GROUP ASC,
			 ITEM_ID ASC,
			 DIAGNOSIS_CODE_TYPE ASC,
			 [YEAR] ASC
		  )ON [PRIMARY]
		) ON [PRIMARY]
	END

	RETURN @intReturn

	ERR_HANDLER:
	
	SET @intReturn = 1

	PRINT 'Failed in ATPAR_SP_POU_RPT_TABLES_PATCH30 store procedure returning non zero value ' 
	RETURN @intReturn

END

GO


