/*  --------------------------------------------------------------------------------------------
	
	AUTHOR  : PRAVEEN.N
	DATE    : 07/08/2017
	PURPOSE : STORED PROCEDURE CHANGES WITH RESPECTIVE TO 3.0 CHANGES
--------------------------------------------------------------------------------------------------	
*/

IF OBJECT_ID('GET_PREF_OPT_HEADER_DATA') IS NOT NULL
DROP PROCEDURE GET_PREF_OPT_HEADER_DATA
GO  
CREATE PROCEDURE GET_PREF_OPT_HEADER_DATA                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,   
@SPECIALTYCODE NVARCHAR(100), 
@PROCEDURE_CODE NVARCHAR(100),    
@PREF_LIST_ID NVARCHAR(100),  
@PHYSICIAN_ID NVARCHAR(100)   
AS                
BEGIN      
IF @HALFYEAR <> 0 
BEGIN
	SELECT SUM(CURRENT_OPEN_QTY), 
	SUM(CURRENT_OPEN_QTY*ITEM_PRICE),
	SUM(CURRENT_HOLD_QTY), 
	SUM(CURRENT_HOLD_QTY*ITEM_PRICE), 
	SUM(ROUND(SUGGESTED_OPEN_QTY, 0)),
	SUM(ROUND(SUGGESTED_OPEN_QTY, 0)*ITEM_PRICE), 
	SUM(ROUND(SUGGESTED_HOLD_QTY, 0)), 
	SUM(ROUND(SUGGESTED_HOLD_QTY, 0)*ITEM_PRICE)
	FROM MT_POU_RPT_OPT_BY_PREFERENCE_H 
	WHERE PERIOD = @HALFYEAR 
		AND YEAR = @YEAR 
		AND SPECIALTY_CODE = @SPECIALTYCODE 
		AND PROCEDURE_CODE = @PROCEDURE_CODE 
		AND PREF_LIST_ID = @PREF_LIST_ID 
		AND PHYSICIAN_ID = @PHYSICIAN_ID
END 
ELSE IF @QUARTER <> 0
BEGIN
	SELECT SUM(CURRENT_OPEN_QTY), 
	SUM(CURRENT_OPEN_QTY*ITEM_PRICE),
	SUM(CURRENT_HOLD_QTY), 
	SUM(CURRENT_HOLD_QTY*ITEM_PRICE), 
	SUM(ROUND(SUGGESTED_OPEN_QTY, 0)),
	SUM(ROUND(SUGGESTED_OPEN_QTY, 0)*ITEM_PRICE), 
	SUM(ROUND(SUGGESTED_HOLD_QTY, 0)), 
	SUM(ROUND(SUGGESTED_HOLD_QTY, 0)*ITEM_PRICE)
	FROM MT_POU_RPT_OPT_BY_PREFERENCE_Q 
		WHERE PERIOD = @QUARTER 
		AND YEAR = @YEAR 
		AND SPECIALTY_CODE = @SPECIALTYCODE 
		AND PROCEDURE_CODE = @PROCEDURE_CODE 
		AND PREF_LIST_ID = @PREF_LIST_ID 
		AND PHYSICIAN_ID = @PHYSICIAN_ID
END
ELSE IF @MONTH <> 0 
BEGIN 
	SELECT SUM(CURRENT_OPEN_QTY), 
	SUM(CURRENT_OPEN_QTY*ITEM_PRICE),
	SUM(CURRENT_HOLD_QTY), 
	SUM(CURRENT_HOLD_QTY*ITEM_PRICE), 
	SUM(ROUND(SUGGESTED_OPEN_QTY, 0)),
	SUM(ROUND(SUGGESTED_OPEN_QTY, 0)*ITEM_PRICE), 
	SUM(ROUND(SUGGESTED_HOLD_QTY, 0)), 
	SUM(ROUND(SUGGESTED_HOLD_QTY, 0)*ITEM_PRICE)
	FROM MT_POU_RPT_OPT_BY_PREFERENCE_M 
		WHERE MONTH = @MONTH 
		AND YEAR = @YEAR 
		AND SPECIALTY_CODE = @SPECIALTYCODE 
		AND PROCEDURE_CODE = @PROCEDURE_CODE 
		AND PREF_LIST_ID = @PREF_LIST_ID 
		AND PHYSICIAN_ID = @PHYSICIAN_ID
END
ELSE IF @YEAR <> 0 AND @HALFYEAR = 0 AND	@QUARTER = 0 AND @MONTH = 0
BEGIN          
	SELECT SUM(CURRENT_OPEN_QTY), 
	SUM(CURRENT_OPEN_QTY*ITEM_PRICE),
	SUM(CURRENT_HOLD_QTY), 
	SUM(CURRENT_HOLD_QTY*ITEM_PRICE), 
	SUM(ROUND(SUGGESTED_OPEN_QTY, 0)),
	SUM(ROUND(SUGGESTED_OPEN_QTY, 0)*ITEM_PRICE), 
	SUM(ROUND(SUGGESTED_HOLD_QTY, 0)), 
	SUM(ROUND(SUGGESTED_HOLD_QTY, 0)*ITEM_PRICE)
	FROM MT_POU_RPT_OPT_BY_PREFERENCE_Y 
		WHERE YEAR = @YEAR 
		AND SPECIALTY_CODE = @SPECIALTYCODE 
		AND PROCEDURE_CODE = @PROCEDURE_CODE 
		AND PREF_LIST_ID = @PREF_LIST_ID 
		AND PHYSICIAN_ID = @PHYSICIAN_ID
END
END
GO

IF OBJECT_ID('GET_PREF_OPT_DETAILS_DATA') IS NOT NULL
DROP PROCEDURE GET_PREF_OPT_DETAILS_DATA
GO
CREATE PROCEDURE GET_PREF_OPT_DETAILS_DATA                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,   
@SPECIALTYCODE NVARCHAR(100), 
@PROCEDURE_CODE NVARCHAR(100),    
@PREF_LIST_ID NVARCHAR(100),  
@PHYSICIAN_ID NVARCHAR(100),
@REMOVE INT,
@ADDTOHOLDSTART INT, 
@ADDTOHOLDEND INT,
@ADDTOOPEN INT   
AS
DECLARE @SQL NVARCHAR(MAX)                  
BEGIN      
IF @HALFYEAR <> 0 
BEGIN
   SET @SQL='SELECT ITEM_ID,ITEM_DESCRIPTION,MAX(ISNULL(MAX_USAGE,0)) AS MAX_USAGE, 
   MIN(ISNULL(MIN_USAGE,0)) AS MIN_USAGE, AVG(ISNULL(MEAN_USAGE,0))  AS MEAN_USAGE,
   AVG(ISNULL(USAGE_PER,0)) USAGE_PER,
   SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' THEN 0
   WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND 
   USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' THEN 0
   WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' THEN CONVERT(INT,ROUND(CAST(MEAN_USAGE AS DECIMAL) ,0))
   WHEN USAGE_PER IS NULL THEN 0  
   END) AS SUGGESTED_OPEN_QTY ,
   SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' THEN 0 
   WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND 
   USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' THEN CONVERT(INT,ROUND(CAST(MEAN_USAGE AS DECIMAL) ,0))
   WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' THEN 0  
   WHEN USAGE_PER IS NULL THEN 0
   END) AS SUGGESTED_HOLD_QTY, 
   AVG(ISNULL(NET_CHANGE_OPEN_QTY,0)) AS NET_CHANGE_OPEN_QTY,
   AVG(ISNULL(NET_CHANGE_HOLD_QTY,0)) AS NET_CHANGE_HOLD_QTY, 
   CEILING(AVG(ISNULL(NET_CHANGE_OPEN_VALUE,0))) AS NET_CHANGE_OPEN_VALUE,
   CEILING(AVG(ISNULL(NET_CHANGE_HOLD_VALUE,0))) AS NET_CHANGE_HOLD_VALUE,
   ISNULL(ITEM_TYPE,0) AS ITEM_TYPE,CEILING(SUM(ISNULL(ITEM_PRICE,0))) AS ITEM_PRICE,
   AVG(ISNULL(CURRENT_OPEN_QTY,0)) AS CURRENT_OPEN_QTY,
   AVG(ISNULL(CURRENT_HOLD_QTY,0)) AS CURRENT_HOLD_QTY,
   SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' AND ITEM_TYPE=0 THEN 1
        WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 1
		WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND  
		USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 2
		WHEN USAGE_PER>'+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND  
		USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' 
		AND ITEM_TYPE=0 THEN 2
		WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 3
		WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' AND ITEM_TYPE=0 THEN 4
   END) AS COLORCODE
   FROM MT_POU_RPT_OPT_BY_PREFERENCE_H
   WHERE  PERIOD ='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' AND 
   SPECIALTY_CODE ='''+@SPECIALTYCODE+''' AND PROCEDURE_CODE = '''+@PROCEDURE_CODE+''' AND
   PREF_LIST_ID ='''+@PREF_LIST_ID+''' AND PHYSICIAN_ID = '''+@PHYSICIAN_ID+'''
   GROUP BY ITEM_ID,ITEM_DESCRIPTION,ITEM_TYPE ORDER BY COLORCODE DESC'
END 
ELSE IF @QUARTER <> 0
BEGIN
   SET @SQL='SELECT ITEM_ID,ITEM_DESCRIPTION,MAX(ISNULL(MAX_USAGE,0)) AS MAX_USAGE, 
   MIN(ISNULL(MIN_USAGE,0)) AS MIN_USAGE, AVG(ISNULL(MEAN_USAGE,0))  AS MEAN_USAGE, 
   AVG(ISNULL(USAGE_PER,0)) USAGE_PER,
   SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' THEN 0
   WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND 
   USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' THEN 0
   WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' THEN CONVERT(INT,ROUND(CAST(MEAN_USAGE AS DECIMAL) ,0))
   WHEN USAGE_PER IS NULL THEN 0  
   END) AS SUGGESTED_OPEN_QTY ,
   SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' THEN 0 
   WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND 
   USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' THEN CONVERT(INT,ROUND(CAST(MEAN_USAGE AS DECIMAL) ,0))
   WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' THEN 0  
   WHEN USAGE_PER IS NULL THEN 0
   END) AS SUGGESTED_HOLD_QTY, 
   AVG(ISNULL(NET_CHANGE_OPEN_QTY,0)) AS NET_CHANGE_OPEN_QTY, 
   AVG(ISNULL(NET_CHANGE_HOLD_QTY,0)) AS NET_CHANGE_HOLD_QTY, 
   CEILING(AVG(ISNULL(NET_CHANGE_OPEN_VALUE,0))) AS NET_CHANGE_OPEN_VALUE, 
   CEILING(AVG(ISNULL(NET_CHANGE_HOLD_VALUE,0))) AS NET_CHANGE_HOLD_VALUE,
   ISNULL(ITEM_TYPE,0) AS ITEM_TYPE,CEILING(SUM(ISNULL(ITEM_PRICE,0))) AS ITEM_PRICE,
   AVG(ISNULL(CURRENT_OPEN_QTY,0)) AS CURRENT_OPEN_QTY,
   AVG(ISNULL(CURRENT_HOLD_QTY,0)) AS CURRENT_HOLD_QTY,
   SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' AND ITEM_TYPE=0 THEN 1
        WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 1
		WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND  
		USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 2
		WHEN USAGE_PER>'+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND  
		USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' 
		AND ITEM_TYPE=0 THEN 2
		WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 3
		WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' AND ITEM_TYPE=0 THEN 4
   END) AS COLORCODE 
   FROM MT_POU_RPT_OPT_BY_PREFERENCE_Q
   WHERE  PERIOD ='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
   AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' AND PROCEDURE_CODE = '''+@PROCEDURE_CODE+''' 
   AND PREF_LIST_ID ='''+@PREF_LIST_ID+''' AND PHYSICIAN_ID = '''+@PHYSICIAN_ID+'''
   GROUP BY ITEM_ID,ITEM_DESCRIPTION,ITEM_TYPE ORDER BY COLORCODE DESC'
END
ELSE IF @MONTH <> 0 
BEGIN
  SET @SQL='SELECT ITEM_ID,ITEM_DESCRIPTION,MAX(ISNULL(MAX_USAGE,0)) AS MAX_USAGE, 
  MIN(ISNULL(MIN_USAGE,0)) AS MIN_USAGE, AVG(ISNULL(MEAN_USAGE,0))  AS MEAN_USAGE, 
  AVG(ISNULL(USAGE_PER,0)) USAGE_PER,
  SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' THEN 0
  WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND 
  USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' THEN 0
  WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' THEN CONVERT(INT,ROUND(CAST(MEAN_USAGE AS DECIMAL) ,0))
  WHEN USAGE_PER IS NULL THEN 0  
  END) AS SUGGESTED_OPEN_QTY ,
  SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' THEN 0 
  WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND 
  USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' THEN CONVERT(INT,ROUND(CAST(MEAN_USAGE AS DECIMAL) ,0))
  WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' THEN 0  
  WHEN USAGE_PER IS NULL THEN 0
  END) AS SUGGESTED_HOLD_QTY, SUM(ISNULL(NET_CHANGE_OPEN_QTY,0)) AS NET_CHANGE_OPEN_QTY, 
  AVG(ISNULL(NET_CHANGE_HOLD_QTY,0)) AS NET_CHANGE_HOLD_QTY, 
  CEILING(AVG(ISNULL(NET_CHANGE_OPEN_VALUE,0))) AS NET_CHANGE_OPEN_VALUE,
  CEILING(AVG(ISNULL(NET_CHANGE_HOLD_VALUE,0))) AS NET_CHANGE_HOLD_VALUE,
  ISNULL(ITEM_TYPE,0) AS ITEM_TYPE,CEILING(SUM(ISNULL(ITEM_PRICE,0))) AS ITEM_PRICE,
  AVG(ISNULL(CURRENT_OPEN_QTY,0)) AS CURRENT_OPEN_QTY,
  AVG(ISNULL(CURRENT_HOLD_QTY,0)) AS CURRENT_HOLD_QTY,
  SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' AND ITEM_TYPE=0 THEN 1
        WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 1
		WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND  
		USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 2
		WHEN USAGE_PER>'+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND  
		USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' 
		AND ITEM_TYPE=0 THEN 2
		WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 3
		WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' AND ITEM_TYPE=0 THEN 4
   END) AS COLORCODE
   FROM MT_POU_RPT_OPT_BY_PREFERENCE_M
  WHERE  MONTH ='+ CAST(@MONTH AS NVARCHAR(MAX)) +' AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
  AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' AND PROCEDURE_CODE = '''+@PROCEDURE_CODE+''' 
  AND PREF_LIST_ID ='''+@PREF_LIST_ID+''' AND PHYSICIAN_ID = '''+@PHYSICIAN_ID+'''
  GROUP BY ITEM_ID,ITEM_DESCRIPTION,ITEM_TYPE ORDER BY COLORCODE DESC'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR = 0 AND	@QUARTER = 0 AND @MONTH = 0
BEGIN
   SET @SQL='SELECT ITEM_ID,ITEM_DESCRIPTION,MAX(ISNULL(MAX_USAGE,0)) AS MAX_USAGE,
    MIN(ISNULL(MIN_USAGE,0)) AS MIN_USAGE, AVG(ISNULL(MEAN_USAGE,0))  AS MEAN_USAGE,
	AVG(ISNULL(USAGE_PER,0)) USAGE_PER,
	SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' THEN 0
    WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND 
    USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' THEN 0
    WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' THEN CONVERT(INT,ROUND(CAST(MEAN_USAGE AS DECIMAL) ,0))
    WHEN USAGE_PER IS NULL THEN 0  
    END) AS SUGGESTED_OPEN_QTY ,
    SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' THEN 0 
    WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND 
    USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' THEN CONVERT(INT,ROUND(CAST(MEAN_USAGE AS DECIMAL) ,0))
    WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' THEN 0  
    WHEN USAGE_PER IS NULL THEN 0
    END) AS SUGGESTED_HOLD_QTY, 
    AVG(ISNULL(NET_CHANGE_OPEN_QTY,0)) AS NET_CHANGE_OPEN_QTY,
    AVG(ISNULL(NET_CHANGE_HOLD_QTY,0)) AS NET_CHANGE_HOLD_QTY, 
    CEILING(AVG(ISNULL(NET_CHANGE_OPEN_VALUE,0))) AS NET_CHANGE_OPEN_VALUE,
    CEILING(AVG(ISNULL(NET_CHANGE_HOLD_VALUE,0))) AS NET_CHANGE_HOLD_VALUE,
    ISNULL(ITEM_TYPE,0) AS ITEM_TYPE,CEILING(SUM(ISNULL(ITEM_PRICE,0))) AS ITEM_PRICE,
    AVG(ISNULL(CURRENT_OPEN_QTY,0)) AS CURRENT_OPEN_QTY,
    AVG(ISNULL(CURRENT_HOLD_QTY,0)) AS CURRENT_HOLD_QTY,
	SUM(CASE WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' AND ITEM_TYPE=0 THEN 1
        WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 1
		WHEN USAGE_PER>='+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND  
		USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 2
		WHEN USAGE_PER>'+ CAST(@ADDTOHOLDSTART AS NVARCHAR(MAX)) +' AND  
		USAGE_PER<='+ CAST(@ADDTOHOLDEND AS NVARCHAR(MAX)) +' 
		AND ITEM_TYPE=0 THEN 2
		WHEN USAGE_PER<='+ CAST(@REMOVE AS NVARCHAR(MAX)) +' AND ITEM_TYPE=1 THEN 3
		WHEN USAGE_PER>'+ CAST(@ADDTOOPEN AS NVARCHAR(MAX)) +' AND ITEM_TYPE=0 THEN 4
   END) AS COLORCODE 
	FROM MT_POU_RPT_OPT_BY_PREFERENCE_Y
    WHERE YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' 
    AND PROCEDURE_CODE = '''+@PROCEDURE_CODE+''' AND PREF_LIST_ID ='''+@PREF_LIST_ID+''' 
    AND PHYSICIAN_ID = '''+@PHYSICIAN_ID+'''
    GROUP BY ITEM_ID,ITEM_DESCRIPTION,ITEM_TYPE ORDER BY COLORCODE DESC'
END
EXEC sp_executesql @SQL
END
GO

IF OBJECT_ID('GET_PREF_OPT_BY_PROCEDURE') IS NOT NULL
DROP PROCEDURE GET_PREF_OPT_BY_PROCEDURE
GO
CREATE PROCEDURE GET_PREF_OPT_BY_PROCEDURE                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,   
@SPECIALTYCODE NVARCHAR(100)           
AS 
DECLARE @SQL NVARCHAR(MAX)                 
BEGIN      
IF @HALFYEAR <> 0 
BEGIN
  SET @SQL=' SELECT SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, 
			SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS , 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES ,
			SUM(ISNULL(NO_OF_PREF_LISTS,0)) AS NO_OF_PREF_LISTS,
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE, 
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE,
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE,
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY,
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE,
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE,
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE 
			FROM MT_POU_RPT_OPT_BY_PROCEDURE_H
			WHERE  PERIOD ='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' 
			GROUP BY  SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
ELSE IF @QUARTER <> 0
BEGIN
 SET @SQL=' SELECT SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, 
			SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS , 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES ,
			SUM(ISNULL(NO_OF_PREF_LISTS,0)) AS NO_OF_PREF_LISTS,
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE, 
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE,
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE,
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY, 
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE,
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY,
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0)) AS TOTAL_WASTED_VALUE,
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE 
			FROM MT_POU_RPT_OPT_BY_PROCEDURE_Q
			WHERE  PERIOD ='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' GROUP BY  
			SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
ELSE IF @MONTH <> 0 
BEGIN
SET @SQL=' SELECT SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, 
			SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS , 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES ,
			SUM(ISNULL(NO_OF_PREF_LISTS,0)) AS NO_OF_PREF_LISTS,
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE, 
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY,
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE,
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE,
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY, 
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE,
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE,
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE 
			FROM MT_POU_RPT_OPT_BY_PROCEDURE_M
			WHERE  MONTH ='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' 
			GROUP BY  SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR = 0 AND @QUARTER = 0 AND @MONTH = 0
BEGIN
SET @SQL=' SELECT SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION,
			SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS , 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES ,
			SUM(ISNULL(NO_OF_PREF_LISTS,0)) AS NO_OF_PREF_LISTS,
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE, 
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE,
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE,
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY,
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE,
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE,
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE 
			FROM MT_POU_RPT_OPT_BY_PROCEDURE_Y
			WHERE YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' GROUP BY  
			SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
EXEC sp_executesql @SQL
END
GO

IF OBJECT_ID('GET_PREF_OPT_BY_PHYSICIAN') IS NOT NULL
DROP PROCEDURE GET_PREF_OPT_BY_PHYSICIAN
GO

CREATE PROCEDURE GET_PREF_OPT_BY_PHYSICIAN                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,   
@SPECIALTYCODE NVARCHAR(100), 
@PROCEDURE_CODE NVARCHAR(100)         
AS
DECLARE @SQL NVARCHAR(MAX)                     
BEGIN      
IF @HALFYEAR <> 0 
BEGIN
   SET @SQL=' SELECT SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, PHYSICIAN_ID, PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			PREF_LIST_ID, PREF_LIST_DESCRIPTION, 
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE, 
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY,
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE,
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE , 
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY, 
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE,
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE, 
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE  
			FROM MT_POU_RPT_OPT_BY_PHYSICIAN_H
			WHERE PERIOD ='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' 
			AND PROCEDURE_CODE = '''+@PROCEDURE_CODE+'''
			GROUP BY SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, PHYSICIAN_ID, 
			PHYSICIAN_NAME,PREF_LIST_ID, 
			PREF_LIST_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END 
ELSE IF @QUARTER <> 0
BEGIN
SET @SQL=' SELECT SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, PHYSICIAN_ID, PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			PREF_LIST_ID, PREF_LIST_DESCRIPTION, 
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE, 
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY,
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE , 
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY, 
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE,
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY,
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE, 
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE  
			FROM MT_POU_RPT_OPT_BY_PHYSICIAN_Q
			WHERE PERIOD ='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' 
			AND PROCEDURE_CODE = '''+@PROCEDURE_CODE+'''
			GROUP BY SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, PHYSICIAN_ID, 
			PHYSICIAN_NAME,PREF_LIST_ID, 
			PREF_LIST_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
ELSE IF @MONTH <> 0 
BEGIN
SET @SQL=' SELECT SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, PHYSICIAN_ID, PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			PREF_LIST_ID, PREF_LIST_DESCRIPTION, 
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE, 
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY,
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE,
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE , 
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY, 
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE,
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE, 
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE  
			FROM MT_POU_RPT_OPT_BY_PHYSICIAN_M
			WHERE   MONTH ='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE ='''+@SPECIALTYCODE+'''
			AND PROCEDURE_CODE = '''+@PROCEDURE_CODE+'''
			GROUP BY SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, PHYSICIAN_ID, 
			PHYSICIAN_NAME,PREF_LIST_ID, 
			PREF_LIST_DESCRIPTION 
			ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR = 0 AND @QUARTER = 0 AND @MONTH = 0
BEGIN
SET @SQL=' SELECT SPECIALTY_CODE, PROCEDURE_CODE,
			PROCEDURE_DESCRIPTION, PHYSICIAN_ID, PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			PREF_LIST_ID, PREF_LIST_DESCRIPTION, 
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE, 
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE , 
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY, 
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE,
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE, 
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE  
			FROM MT_POU_RPT_OPT_BY_PHYSICIAN_Y
			WHERE YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE ='''+@SPECIALTYCODE+''' 
			AND PROCEDURE_CODE = '''+@PROCEDURE_CODE+'''
			GROUP BY SPECIALTY_CODE, PROCEDURE_CODE, 
			PROCEDURE_DESCRIPTION, PHYSICIAN_ID, 
			PHYSICIAN_NAME,PREF_LIST_ID, 
			PREF_LIST_DESCRIPTION 
			ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
PRINT @SQL
EXEC sp_executesql @SQL
END
GO

IF OBJECT_ID('GET_PREF_OPT_BY_SPECIALTY') IS NOT NULL
DROP PROCEDURE GET_PREF_OPT_BY_SPECIALTY
GO
CREATE PROCEDURE GET_PREF_OPT_BY_SPECIALTY                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT              
AS   
DECLARE @SQL NVARCHAR(MAX)                
BEGIN      
IF @HALFYEAR <> 0 
BEGIN
 SET @SQL='SELECT SPECIALTY_CODE, SPECIALTY_DESCRIPTION, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
			SUM(ISNULL(NO_OF_PREF_LISTS,0)) AS NO_OF_PREF_LISTS , 
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE,
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE, 
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY,
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE, 
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY,
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE,
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE FROM MT_POU_RPT_OPT_BY_SPECIALTY_H
			WHERE  PERIOD = '+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			GROUP BY SPECIALTY_CODE, SPECIALTY_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
 
END
ELSE IF @QUARTER <> 0
BEGIN
SET @SQL='SELECT SPECIALTY_CODE, SPECIALTY_DESCRIPTION, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
			SUM(ISNULL(NO_OF_PREF_LISTS,0)) AS NO_OF_PREF_LISTS , 
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE,
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE, 
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY,
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE, 
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY,
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE,
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE FROM MT_POU_RPT_OPT_BY_SPECIALTY_Q
			WHERE  PERIOD = '+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			GROUP BY SPECIALTY_CODE, SPECIALTY_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
ELSE IF @MONTH <> 0 
BEGIN
     SET @SQL='SELECT SPECIALTY_CODE, SPECIALTY_DESCRIPTION, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
			SUM(ISNULL(NO_OF_PREF_LISTS,0)) AS NO_OF_PREF_LISTS , 
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE,
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE, 
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY,
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE, 
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY,
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE,
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE FROM MT_POU_RPT_OPT_BY_SPECIALTY_M
			WHERE  MONTH = '+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			GROUP BY SPECIALTY_CODE, SPECIALTY_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR = 0 AND	@QUARTER = 0 AND @MONTH = 0
BEGIN
 SET @SQL='SELECT SPECIALTY_CODE, SPECIALTY_DESCRIPTION, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
			SUM(ISNULL(NO_OF_PREF_LISTS,0)) AS NO_OF_PREF_LISTS , 
			SUM(ISNULL(EFFICIENCY_PERCENTAGE,0)) AS EFFICIENCY_PERCENTAGE,
			SUM(ISNULL(TOTAL_PICKED_QTY,0)) AS TOTAL_PICKED_QTY, 
			CEILING(SUM(ISNULL(TOTAL_PICKED_VALUE,0))) AS TOTAL_PICKED_VALUE, 
			SUM(ISNULL(TOTAL_ISSUED_EXISTING_QTY,0)) AS TOTAL_ISSUED_EXISTING_QTY, 
			CEILING(SUM(ISNULL(TOTAL_ISSUED_EXISTING_VALUE,0))) AS TOTAL_ISSUED_EXISTING_VALUE,
			SUM(ISNULL(TOTAL_ISSUED_NEW_QTY,0)) AS TOTAL_ISSUED_NEW_QTY,
			CEILING(SUM(ISNULL(TOTAL_ISSUED_NEW_VALUE,0))) AS TOTAL_ISSUED_NEW_VALUE, 
			SUM(ISNULL(TOTAL_RETURN_QTY,0)) AS TOTAL_RETURN_QTY,
			CEILING(SUM(ISNULL(TOTAL_RETURN_VALUE,0))) AS TOTAL_RETURN_VALUE, 
			SUM(ISNULL(TOTAL_WASTED_QTY,0)) AS TOTAL_WASTED_QTY,
			CEILING(SUM(ISNULL(TOTAL_WASTED_VALUE,0))) AS TOTAL_WASTED_VALUE,
			CEILING(SUM(ISNULL(TOTAL_USAGE,0))) AS TOTAL_USAGE FROM MT_POU_RPT_OPT_BY_SPECIALTY_Y
			WHERE YEAR ='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			GROUP BY SPECIALTY_CODE, SPECIALTY_DESCRIPTION ORDER BY EFFICIENCY_PERCENTAGE DESC'
END
EXEC sp_executesql @SQL
END
GO

IF OBJECT_ID('GET_COSTVARIANCE_BY_SPECIALTY') IS NOT NULL
DROP PROCEDURE GET_COSTVARIANCE_BY_SPECIALTY
GO
CREATE PROCEDURE GET_COSTVARIANCE_BY_SPECIALTY
@CODE_TEXT NVARCHAR(100),                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT              
AS    
DECLARE @SQL NVARCHAR(MAX)  
DECLARE @DIAGNOSIS INT 
DECLARE @APPEND NVARCHAR(MAX)     
DECLARE @GROUPBY NVARCHAR(MAX)       
BEGIN 
IF @CODE_TEXT='PROCEDURE_CODE'
BEGIN
SET @DIAGNOSIS=3 
END
IF @CODE_TEXT='CPT_CODE'
BEGIN
SET @DIAGNOSIS=2
END
IF @CODE_TEXT='ICD_CODE'
BEGIN
SET @DIAGNOSIS=1
END    
SET @APPEND=' AND DIAGNOSIS_CODE_TYPE='+CAST(@DIAGNOSIS AS NVARCHAR(MAX))
SET @GROUPBY=' GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION ORDER BY TOTAL_VARIANCE DESC' 
IF @HALFYEAR <> 0 
BEGIN
SET @SQL=' SELECT  SPECIALTY_CODE,SPECIALTY_DESCRIPTION,
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND,
			CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE,
			ROUND((SUM(ISNULL(TOTAL_VARIANCE,0))/SUM(CASE WHEN TOTAL_SPEND IS NULL OR TOTAL_SPEND = 0 THEN 1 ELSE TOTAL_SPEND END))*100,1) AS PERVARIANCE 
			FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_H
			WHERE PERIOD='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+'' 
END
ELSE IF @QUARTER <>0
BEGIN
SET @SQL=' SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION,
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND,
			CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE,
			ROUND((SUM(ISNULL(TOTAL_VARIANCE,0))/SUM(CASE WHEN TOTAL_SPEND IS NULL OR TOTAL_SPEND = 0 THEN 1 ELSE TOTAL_SPEND END))*100,1) AS PERVARIANCE 
			FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q
			WHERE PERIOD='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+'' 
END
ELSE IF @MONTH <> 0 
BEGIN
SET @SQL=' SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION,
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND,
			CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE,
			ROUND((SUM(ISNULL(TOTAL_VARIANCE,0))/SUM(CASE WHEN TOTAL_SPEND IS NULL OR TOTAL_SPEND = 0 THEN 1 ELSE TOTAL_SPEND END))*100,1) AS PERVARIANCE 
			FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M
			WHERE MONTH='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+'' 
END
ELSE IF @YEAR <> 0 AND @HALFYEAR=0 AND	@QUARTER=0 AND @MONTH=0
BEGIN
    SET @SQL=' SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION,
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND,
			CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE,
			ROUND((SUM(ISNULL(TOTAL_VARIANCE,0))/SUM(CASE WHEN TOTAL_SPEND IS NULL OR TOTAL_SPEND = 0 THEN 1 ELSE TOTAL_SPEND END))*100,1) AS PERVARIANCE 
			FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y
			WHERE YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+'' 
END
set @SQL=@SQL+@APPEND+@GROUPBY

EXEC sp_executesql @SQL
END

GO

IF OBJECT_ID('GET_COSTVARIANCE_ITEMGROUP_HDR_DETAILS') IS NOT NULL
DROP PROCEDURE GET_COSTVARIANCE_ITEMGROUP_HDR_DETAILS
GO
CREATE PROCEDURE GET_COSTVARIANCE_ITEMGROUP_HDR_DETAILS                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,
@SPECIALTYCODE NVARCHAR(100),
@CODE_TEXT NVARCHAR(100),
@DIAGNOSIS_CODE NVARCHAR(100)                     
AS  
DECLARE @SQL NVARCHAR(MAX)
DECLARE @DIAGNOSIS INT 
DECLARE @APPEND NVARCHAR(MAX)     
DECLARE @GROUPBY NVARCHAR(MAX)                        
BEGIN 
IF @DIAGNOSIS_CODE='PROCEDURE_CODE'
BEGIN
SET @DIAGNOSIS=3 
END
IF @DIAGNOSIS_CODE='CPT_CODE'
BEGIN
SET @DIAGNOSIS=2
END
IF @DIAGNOSIS_CODE='ICD_CODE'
BEGIN
SET @DIAGNOSIS=1
END    
SET @APPEND=' AND DIAGNOSIS_CODE_TYPE='+CAST(@DIAGNOSIS AS NVARCHAR(MAX))
SET @GROUPBY=' GROUP BY ITEM_GROUP,ITEM_GROUP_DESCRIPTION'      
IF @HALFYEAR <> 0 
BEGIN
 SET @SQL=' SELECT  ITEM_GROUP,ITEM_GROUP_DESCRIPTION, CEILING(SUM(ISNULL(TOTAL_COST_ITEM_GROUP,0))) AS TOTALSPEND, 
			SUM(ISNULL(NO_OF_ITEMS_BY_ITEM_GROUP,0)) AS NO_OF_ITEMS_BY_ITEM_GROUP , 
			CEILING(SUM(ISNULL(TOTAL_COST_ITEM_GROUP,0))) AS TOTAL_COST_ITEM_GROUP 
			FROM MT_POU_RPT_SPEND_BY_GROUP_H
			WHERE PERIOD='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @QUARTER <>0
BEGIN
 SET @SQL=' SELECT  ITEM_GROUP,ITEM_GROUP_DESCRIPTION, CEILING(SUM(ISNULL(TOTAL_COST_ITEM_GROUP,0))) AS TOTALSPEND, 
			SUM(ISNULL(NO_OF_ITEMS_BY_ITEM_GROUP,0)) AS NO_OF_ITEMS_BY_ITEM_GROUP , 
			CEILING(SUM(ISNULL(TOTAL_COST_ITEM_GROUP,0))) AS TOTAL_COST_ITEM_GROUP 
			FROM MT_POU_RPT_SPEND_BY_GROUP_Q
			WHERE PERIOD='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @MONTH <> 0 
BEGIN
SET @SQL=' SELECT  ITEM_GROUP,ITEM_GROUP_DESCRIPTION,CEILING(SUM(ISNULL(TOTAL_COST_ITEM_GROUP,0))) AS TOTALSPEND, 
			SUM(ISNULL(NO_OF_ITEMS_BY_ITEM_GROUP,0)) AS NO_OF_ITEMS_BY_ITEM_GROUP , 
			CEILING(SUM(ISNULL(TOTAL_COST_ITEM_GROUP,0))) AS TOTAL_COST_ITEM_GROUP 
			FROM MT_POU_RPT_SPEND_BY_GROUP_M
			WHERE MONTH='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' AND 
			SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR=0 AND	@QUARTER=0 AND @MONTH=0
BEGIN
SET @SQL=' SELECT ITEM_GROUP,ITEM_GROUP_DESCRIPTION,CEILING(SUM(ISNULL(TOTAL_COST_ITEM_GROUP,0))) AS TOTALSPEND, 
			SUM(ISNULL(NO_OF_ITEMS_BY_ITEM_GROUP,0)) AS NO_OF_ITEMS_BY_ITEM_GROUP , 
			CEILING(SUM(ISNULL(TOTAL_COST_ITEM_GROUP,0))) AS TOTAL_COST_ITEM_GROUP 
			FROM MT_POU_RPT_SPEND_BY_GROUP_Y
			WHERE YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
SET @SQL=@SQL+@APPEND+@GROUPBY
EXEC sp_executesql @SQL
END
GO


IF OBJECT_ID('GET_COSTVARIANCE_SURGEON_HDR_DATA') IS NOT NULL
DROP PROCEDURE GET_COSTVARIANCE_SURGEON_HDR_DATA
GO
CREATE PROCEDURE GET_COSTVARIANCE_SURGEON_HDR_DATA                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,
@SPECIALTYCODE NVARCHAR(100),
@CODE_TEXT NVARCHAR(100),
@DIAGNOSIS_CODE NVARCHAR(100)                  
AS                
DECLARE @SQL NVARCHAR(MAX)
DECLARE @DIAGNOSIS INT 
DECLARE @APPEND NVARCHAR(MAX)     
DECLARE @GROUPBY NVARCHAR(MAX) 
BEGIN
IF @DIAGNOSIS_CODE='PROCEDURE_CODE'
BEGIN
SET @DIAGNOSIS=3
END
IF @DIAGNOSIS_CODE='CPT_CODE'
BEGIN
SET @DIAGNOSIS=2
END
IF @DIAGNOSIS_CODE='ICD_CODE'
BEGIN
SET @DIAGNOSIS=1
END
SET @APPEND=' AND DIAGNOSIS_CODE_TYPE='+CAST(@DIAGNOSIS AS NVARCHAR(MAX))   
SET @GROUPBY=' GROUP BY PHYSICIAN_ID , PHYSICIAN_NAME'         
IF @HALFYEAR <> 0 
BEGIN
 SET @SQL=' SELECT SUM(ISNULL(TOTAL_NO_OF_CASES_PHYSICIAN,0)) AS TOTAL_NO_OF_CASES_PHYSICIAN ,  
			PHYSICIAN_ID , PHYSICIAN_NAME 
			FROM MT_POU_RPT_SPEND_BY_GROUP_H
			WHERE  PERIOD='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @QUARTER <>0
BEGIN
SET @SQL=' SELECT SUM(ISNULL(TOTAL_NO_OF_CASES_PHYSICIAN,0)) AS TOTAL_NO_OF_CASES_PHYSICIAN , 
			PHYSICIAN_ID , PHYSICIAN_NAME 
			FROM MT_POU_RPT_SPEND_BY_GROUP_Q
			WHERE  PERIOD='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @MONTH <> 0 
BEGIN
SET @SQL=' SELECT  SUM(ISNULL(TOTAL_NO_OF_CASES_PHYSICIAN,0)) AS TOTAL_NO_OF_CASES_PHYSICIAN , 
			PHYSICIAN_ID , PHYSICIAN_NAME 
			FROM MT_POU_RPT_SPEND_BY_GROUP_M
			WHERE  MONTH='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR=0 AND	@QUARTER=0 AND @MONTH=0
BEGIN
SET @SQL=' SELECT SUM(ISNULL(TOTAL_NO_OF_CASES_PHYSICIAN,0)) AS TOTAL_NO_OF_CASES_PHYSICIAN , 
			PHYSICIAN_ID , PHYSICIAN_NAME 
			FROM MT_POU_RPT_SPEND_BY_GROUP_Y
			WHERE YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
SET @SQL=@SQL+@APPEND+@GROUPBY
EXEC sp_executesql @SQL
END
GO


IF OBJECT_ID('GET_COSTVARIANCE_BY_DIAGNOSISCODE') IS NOT NULL
DROP PROCEDURE GET_COSTVARIANCE_BY_DIAGNOSISCODE
GO
CREATE PROCEDURE GET_COSTVARIANCE_BY_DIAGNOSISCODE                
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,
@SPECIALTYCODE NVARCHAR(100),  
@CODE_TEXT NVARCHAR(100),
@DESCRTEXT NVARCHAR(100)              
AS   
DECLARE @SQL NVARCHAR(MAX) 
DECLARE @TEXT NVARCHAR(MAX)  
DECLARE @DIAGNOSIS INT 
DECLARE @APPEND NVARCHAR(MAX)  
DECLARE @ORDERBY NVARCHAR(MAX)                       
BEGIN  
IF @CODE_TEXT='PROCEDURE_CODE'
BEGIN
SET @DIAGNOSIS=3
END
IF @CODE_TEXT='CPT_CODE'
BEGIN
SET @DIAGNOSIS=2
END
IF @CODE_TEXT='ICD_CODE'
BEGIN
SET @DIAGNOSIS=1
END
IF @HALFYEAR <> 0 AND @QUARTER=0 AND @MONTH=0
BEGIN  
SET @SQL='SELECT SPECIALTY_CODE,DIAGNOSIS_CODE AS CODE,
			DIAGNOSIS_DESCRIPTION AS DESCRIPTION, 
			SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 			
			CEILING(MAX(ISNULL(MAX_USAGE,0))) AS MAX_USAGE, 
			CEILING(MIN(ISNULL(MIN_USAGE,0))) AS MIN_USAGE,
			CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE, 
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
			CEILING(SUM(ISNULL(TOTAL_ANNUAL_SPEND,0))) AS TOTAL_ANNUAL_SPEND,
			ROUND((SUM(ISNULL(TOTAL_VARIANCE,0))/SUM(CASE WHEN TOTAL_SPEND IS NULL OR TOTAL_SPEND = 0 THEN 1 ELSE TOTAL_SPEND END))*100,1) AS PERVARIANCE  
			FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_H
			WHERE  PERIOD='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''''   
  END
ELSE IF @QUARTER <> 0 AND @HALFYEAR=0 AND @MONTH=0
BEGIN  
SET @SQL='SELECT SPECIALTY_CODE,DIAGNOSIS_CODE AS CODE,
			DIAGNOSIS_DESCRIPTION AS DESCRIPTION, SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			CEILING(MAX(ISNULL(MAX_USAGE,0))) AS MAX_USAGE,
			CEILING(MIN(ISNULL(MIN_USAGE,0))) AS MIN_USAGE, 
			CEILING(SUM(TOTAL_VARIANCE)) AS TOTAL_VARIANCE, 
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
			CEILING(SUM(ISNULL(TOTAL_ANNUAL_SPEND,0))) AS TOTAL_ANNUAL_SPEND,
			ROUND((SUM(ISNULL(TOTAL_VARIANCE,0))/SUM(CASE WHEN TOTAL_SPEND IS NULL OR TOTAL_SPEND = 0 THEN 1 ELSE TOTAL_SPEND END))*100,1) AS PERVARIANCE  
			FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Q
			WHERE  PERIOD='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''''
  
END
ELSE IF @MONTH <> 0 AND @HALFYEAR=0 AND	@QUARTER=0
BEGIN
SET @SQL='SELECT SPECIALTY_CODE,DIAGNOSIS_CODE AS CODE,
			DIAGNOSIS_DESCRIPTION AS DESCRIPTION, 
			SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			CEILING(MAX(ISNULL(MAX_USAGE,0))) AS MAX_USAGE, 
			CEILING(MIN(ISNULL(MIN_USAGE,0))) AS MIN_USAGE, 
			CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE, 
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
			CEILING(SUM(ISNULL(TOTAL_ANNUAL_SPEND,0))) AS TOTAL_ANNUAL_SPEND,
			ROUND((SUM(ISNULL(TOTAL_VARIANCE,0))/SUM(CASE WHEN TOTAL_SPEND IS NULL OR TOTAL_SPEND = 0 THEN 1 ELSE TOTAL_SPEND END))*100,1) AS PERVARIANCE  
			FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_M
			WHERE  MONTH='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''''  
  
END
ELSE IF @YEAR<>0 AND @HALFYEAR=0 AND	@QUARTER=0 AND @MONTH=0
BEGIN
SET @SQL='SELECT SPECIALTY_CODE,DIAGNOSIS_CODE AS CODE,
			DIAGNOSIS_DESCRIPTION AS DESCRIPTION, 
			SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
			CEILING(MAX(ISNULL(MAX_USAGE,0))) AS MAX_USAGE, 
			CEILING(MIN(ISNULL(MIN_USAGE,0))) AS MIN_USAGE, 
			CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE, 
			CEILING(SUM(TOTAL_SPEND)) AS TOTAL_SPEND, 
			CEILING(SUM(ISNULL(TOTAL_ANNUAL_SPEND,0))) AS TOTAL_ANNUAL_SPEND,
			ROUND((SUM(ISNULL(TOTAL_VARIANCE,0))/SUM(CASE WHEN TOTAL_SPEND IS NULL OR TOTAL_SPEND = 0 THEN 1 ELSE TOTAL_SPEND END))*100,1) AS PERVARIANCE  
			FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y
			WHERE YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+'''' 
END
  SET @APPEND=' AND DIAGNOSIS_CODE_TYPE='+CAST(@DIAGNOSIS AS NVARCHAR(MAX))
  SET @TEXT=' GROUP BY SPECIALTY_CODE,DIAGNOSIS_CODE,DIAGNOSIS_DESCRIPTION'
  SET @ORDERBY=' ORDER BY TOTAL_VARIANCE DESC'
  SET @SQL=@SQL+@APPEND+@TEXT+@ORDERBY 
  EXEC sp_executesql @SQL
END
GO

IF OBJECT_ID('GET_COSTVARIANCE_ITEMGROUPS') IS NOT NULL
DROP PROCEDURE GET_COSTVARIANCE_ITEMGROUPS
GO
CREATE PROCEDURE GET_COSTVARIANCE_ITEMGROUPS
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,
@SPECIALTYCODE NVARCHAR(100),
@CODE_TEXT NVARCHAR(100),
@DIAGNOSIS_CODE NVARCHAR(100)        
AS                
DECLARE @SQL NVARCHAR(MAX) 
DECLARE @DIAGNOSIS INT 
DECLARE @APPEND NVARCHAR(MAX)
DECLARE @GROUPBY NVARCHAR(MAX)
BEGIN
SET @GROUPBY=' GROUP BY ITEM_GROUP, ITEM_GROUP_DESCRIPTION'
IF @DIAGNOSIS_CODE='PROCEDURE_CODE'
BEGIN
SET @DIAGNOSIS=3
END
IF @DIAGNOSIS_CODE='CPT_CODE'
BEGIN
SET @DIAGNOSIS=2
END
IF @DIAGNOSIS_CODE='ICD_CODE'
BEGIN
SET @DIAGNOSIS=1
END   
SET @APPEND=' AND DIAGNOSIS_CODE_TYPE='+CAST(@DIAGNOSIS AS NVARCHAR(MAX)) 
IF @HALFYEAR <> 0 
BEGIN
 SET @SQL=' SELECT ITEM_GROUP_DESCRIPTION, ITEM_GROUP_DESCRIPTION AS ITEM_GROUP
			FROM MT_POU_RPT_SPEND_BY_GROUP_H
			WHERE  PERIOD='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @QUARTER <>0
BEGIN
SET @SQL=' SELECT ITEM_GROUP_DESCRIPTION, ITEM_GROUP_DESCRIPTION AS ITEM_GROUP
			FROM MT_POU_RPT_SPEND_BY_GROUP_Q
			WHERE  PERIOD='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @MONTH <> 0 
BEGIN
SET @SQL=' SELECT  ITEM_GROUP_DESCRIPTION, ITEM_GROUP_DESCRIPTION AS ITEM_GROUP
			FROM MT_POU_RPT_SPEND_BY_GROUP_M
			WHERE  MONTH='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR=0 AND	@QUARTER=0 AND @MONTH=0
BEGIN
SET @SQL=' SELECT ITEM_GROUP_DESCRIPTION, ITEM_GROUP_DESCRIPTION AS ITEM_GROUP
			FROM MT_POU_RPT_SPEND_BY_GROUP_Y
			WHERE YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
SET @SQL=@SQL+@APPEND+@GROUPBY
EXEC sp_executesql @SQL
END
GO


IF OBJECT_ID('GET_COSTVARIANCE_SUPPLY_HDR_DATA') IS NOT NULL
DROP PROCEDURE GET_COSTVARIANCE_SUPPLY_HDR_DATA
GO
CREATE PROCEDURE GET_COSTVARIANCE_SUPPLY_HDR_DATA               
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,
@SPECIALTYCODE NVARCHAR(100),
@CODE_TEXT NVARCHAR(100),
@DIAGNOSIS_CODE NVARCHAR(100)                   
AS  
DECLARE @SQL NVARCHAR(MAX)   
DECLARE @DIAGNOSIS INT 
DECLARE @APPEND NVARCHAR(MAX)  
DECLARE @GROUPBY NVARCHAR(MAX)                  
BEGIN 
SET @GROUPBY='  GROUP BY PHYSICIAN_ID , PHYSICIAN_NAME'
IF @DIAGNOSIS_CODE='PROCEDURE_CODE'
BEGIN
SET @DIAGNOSIS=3
END
IF @DIAGNOSIS_CODE='CPT_CODE'
BEGIN
SET @DIAGNOSIS=2
END
IF @DIAGNOSIS_CODE='ICD_CODE'
BEGIN
SET @DIAGNOSIS=1
END     
SET @APPEND=' AND DIAGNOSIS_CODE_TYPE='+CAST(@DIAGNOSIS AS NVARCHAR(MAX)) 
IF @HALFYEAR <> 0 
BEGIN
 SET @SQL=' SELECT PHYSICIAN_ID,PHYSICIAN_NAME,
			COUNT(DISTINCT PHYSICIAN_ID) AS NUMPHYS 
			FROM MT_POU_RPT_SUPPLY_COMPARISON_H
			WHERE  PERIOD='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @QUARTER <>0
BEGIN
   SET @SQL=' SELECT PHYSICIAN_ID,PHYSICIAN_NAME,
			COUNT(DISTINCT PHYSICIAN_ID) AS NUMPHYS 
			FROM MT_POU_RPT_SUPPLY_COMPARISON_Q
			WHERE  PERIOD='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @MONTH <> 0 
BEGIN
    SET @SQL=' SELECT PHYSICIAN_ID,PHYSICIAN_NAME,
			COUNT(DISTINCT PHYSICIAN_ID) AS NUMPHYS 
			FROM MT_POU_RPT_SUPPLY_COMPARISON_M
			WHERE  MONTH='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR=0 AND	@QUARTER=0 AND @MONTH=0
BEGIN
     SET @SQL=' SELECT PHYSICIAN_ID,PHYSICIAN_NAME,
			COUNT(DISTINCT PHYSICIAN_ID) AS NUMPHYS 
			FROM MT_POU_RPT_SUPPLY_COMPARISON_Y
			WHERE YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
SET @SQL=@SQL+@APPEND+@GROUPBY
EXEC sp_executesql @SQL
END
GO

IF OBJECT_ID('GET_COSTVARIANCE_SUPPLY_ITEM_DETAILS') IS NOT NULL
DROP PROCEDURE GET_COSTVARIANCE_SUPPLY_ITEM_DETAILS
GO
CREATE PROCEDURE GET_COSTVARIANCE_SUPPLY_ITEM_DETAILS
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,
@SPECIALTYCODE NVARCHAR(100),
@CODE_TEXT NVARCHAR(100),
@DIAGNOSIS_CODE NVARCHAR(100)                   
AS  
DECLARE @SQL NVARCHAR(MAX)   
DECLARE @DIAGNOSIS INT 
DECLARE @APPEND NVARCHAR(MAX)  
DECLARE @GROUPBY NVARCHAR(MAX)                  
BEGIN 
SET @GROUPBY='  GROUP BY ITEM_GROUP, ITEM_GROUP_DESCRIPTION'
IF @DIAGNOSIS_CODE='PROCEDURE_CODE'
BEGIN
SET @DIAGNOSIS=3 
END
IF @DIAGNOSIS_CODE='CPT_CODE'
BEGIN
SET @DIAGNOSIS=2
END
IF @DIAGNOSIS_CODE='ICD_CODE'
BEGIN
SET @DIAGNOSIS=1
END    
SET @APPEND=' AND DIAGNOSIS_CODE_TYPE='+CAST(@DIAGNOSIS AS NVARCHAR(MAX))
IF @HALFYEAR <> 0 
BEGIN
 SET @SQL=' SELECT ITEM_GROUP, ITEM_GROUP_DESCRIPTION 
			FROM MT_POU_RPT_SUPPLY_COMPARISON_H
			WHERE  PERIOD='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @QUARTER <>0
BEGIN
SET @SQL=' SELECT ITEM_GROUP, ITEM_GROUP_DESCRIPTION 
			FROM MT_POU_RPT_SUPPLY_COMPARISON_Q
			WHERE  PERIOD='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @MONTH <> 0 
BEGIN
SET @SQL=' SELECT  ITEM_GROUP, ITEM_GROUP_DESCRIPTION 
			FROM MT_POU_RPT_SUPPLY_COMPARISON_M
			WHERE  MONTH='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+'''
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR=0 AND	@QUARTER=0 AND @MONTH=0
BEGIN
SET @SQL=' SELECT ITEM_GROUP, ITEM_GROUP_DESCRIPTION 
			FROM MT_POU_RPT_SUPPLY_COMPARISON_Y
			WHERE YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@CODE_TEXT+''')'
END
SET @SQL=@SQL+@APPEND+@GROUPBY
EXEC sp_executesql @SQL
END
GO



IF OBJECT_ID('GET_COSTVARIANCE_BY_SURGEON') IS NOT NULL
DROP PROCEDURE GET_COSTVARIANCE_BY_SURGEON
GO
CREATE PROCEDURE GET_COSTVARIANCE_BY_SURGEON             
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT,
@SPECIALTYCODE NVARCHAR(100),
@CODE_TEXT NVARCHAR(100),
@REIMBURSEMENT_CODE NVARCHAR(100)            
AS  
DECLARE @SQL NVARCHAR(MAX)
DECLARE @DIAGNOSIS INT 
DECLARE @APPEND NVARCHAR(MAX) 
DECLARE @GROUPBY NVARCHAR(MAX)              
BEGIN 
SET @GROUPBY=' GROUP BY PHYSICIAN_ID,PHYSICIAN_NAME ORDER BY EXTENDED_VARIANCE DESC'
IF @CODE_TEXT='PROCEDURE_CODE'
BEGIN
SET @DIAGNOSIS=3
END
IF @CODE_TEXT='CPT_CODE'
BEGIN
SET @DIAGNOSIS=2
END
IF @CODE_TEXT='ICD_CODE'
BEGIN
SET @DIAGNOSIS=1
END   
SET @APPEND=' AND DIAGNOSIS_CODE_TYPE='+CAST(@DIAGNOSIS AS NVARCHAR(MAX))   
IF @HALFYEAR <> 0 
BEGIN
 SET @SQL='SELECT COUNT(ISNULL(PHYSICIAN_ID,0)) AS COUNT,
			PHYSICIAN_ID, PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES , 
			CEILING(MIN(ISNULL(MIN_PROC_COST,0))) AS MIN_PROC_COST, 
			CEILING(MAX(ISNULL(MAX_PROC_COST,0))) AS MAX_PROC_COST , 
			CEILING(AVG(ISNULL(AVG_PROC_COST,0))) AS AVG_PROC_COST,
			CEILING(SUM(ISNULL(MIN_PROC_VARIANCE,0))) AS MIN_PROC_VARIANCE ,
			CEILING(SUM(ISNULL(EXTENDED_VARIANCE,0))) AS EXTENDED_VARIANCE 
			FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
			WHERE  PERIOD='+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@REIMBURSEMENT_CODE+''')'

END
ELSE IF @QUARTER <>0
BEGIN
SET @SQL='SELECT COUNT(ISNULL(PHYSICIAN_ID,0)) AS COUNT,
			PHYSICIAN_ID, PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES ,
			CEILING(MIN(ISNULL(MIN_PROC_COST,0))) AS MIN_PROC_COST, 
			CEILING(MAX(ISNULL(MAX_PROC_COST,0))) AS MAX_PROC_COST ,
			CEILING(AVG(ISNULL(AVG_PROC_COST,0))) AS AVG_PROC_COST,
			CEILING(SUM(ISNULL(MIN_PROC_VARIANCE,0))) AS MIN_PROC_VARIANCE ,
			CEILING(SUM(ISNULL(EXTENDED_VARIANCE,0))) AS EXTENDED_VARIANCE 
			FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Q
			WHERE  PERIOD='+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@REIMBURSEMENT_CODE+''')'

END
ELSE IF @MONTH <> 0 
BEGIN
SET @SQL='SELECT COUNT(ISNULL(PHYSICIAN_ID,0)) AS COUNT,
			PHYSICIAN_ID, PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES ,
			CEILING(MIN(ISNULL(MIN_PROC_COST,0))) AS MIN_PROC_COST, 
			CEILING(MAX(ISNULL(MAX_PROC_COST,0))) AS MAX_PROC_COST , 
			CEILING(AVG(ISNULL(AVG_PROC_COST,0))) AS AVG_PROC_COST,
			CEILING(SUM(ISNULL(MIN_PROC_VARIANCE,0))) AS MIN_PROC_VARIANCE ,
			CEILING(SUM(ISNULL(EXTENDED_VARIANCE,0))) AS EXTENDED_VARIANCE 
			FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_M
			WHERE  MONTH='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
			AND YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@REIMBURSEMENT_CODE+''')'

END
ELSE IF @YEAR <> 0 AND @HALFYEAR=0 AND	@QUARTER=0 AND @MONTH=0
BEGIN
SET @SQL='SELECT COUNT(ISNULL(PHYSICIAN_ID,0)) AS COUNT,PHYSICIAN_ID,
			PHYSICIAN_NAME, SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES , 
			CEILING(MIN(ISNULL(MIN_PROC_COST,0))) AS MIN_PROC_COST, 
			CEILING(MAX(ISNULL(MAX_PROC_COST,0))) AS MAX_PROC_COST , 
			CEILING(AVG(ISNULL(AVG_PROC_COST,0))) AS AVG_PROC_COST,
			CEILING(SUM(ISNULL(MIN_PROC_VARIANCE,0))) AS MIN_PROC_VARIANCE ,
			CEILING(SUM(ISNULL(EXTENDED_VARIANCE,0))) AS EXTENDED_VARIANCE 
			FROM  MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y
			WHERE YEAR='+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE='''+@SPECIALTYCODE+''' 
			AND (DIAGNOSIS_CODE='''+@REIMBURSEMENT_CODE+''')'
END
SET @SQL=@SQL+@APPEND+@GROUPBY
EXEC sp_executesql @SQL
END
GO

IF OBJECT_ID('GET_PHY_SUMMARY_BY_SPECIALTY') IS NOT NULL
DROP PROCEDURE GET_PHY_SUMMARY_BY_SPECIALTY
GO
CREATE PROCEDURE GET_PHY_SUMMARY_BY_SPECIALTY
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT              
AS   
DECLARE @SQL NVARCHAR(MAX)              
BEGIN      
IF @HALFYEAR <> 0 
BEGIN
  SET @SQL = 'SELECT SPECIALTY_CODE, 
		SPECIALTY_DESCRIPTION, 
		SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
		SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS, 
		CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
		CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE 
		FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_H
		WHERE PERIOD = '+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
		AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+'
		AND DIAGNOSIS_CODE_TYPE = 3  
		GROUP BY SPECIALTY_CODE, 
		SPECIALTY_DESCRIPTION 
		ORDER BY TOTAL_VARIANCE ASC'
END
ELSE IF @QUARTER <> 0
BEGIN
  SET @SQL = 'SELECT SPECIALTY_CODE, 
			SPECIALTY_DESCRIPTION, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
			SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS, 
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
			CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE 
			FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Q
			WHERE PERIOD = '+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND DIAGNOSIS_CODE_TYPE = 3
			GROUP BY SPECIALTY_CODE, 
			SPECIALTY_DESCRIPTION 
			ORDER BY TOTAL_VARIANCE ASC'
END
ELSE IF @MONTH <> 0 
BEGIN
     SET @SQL = 'SELECT SPECIALTY_CODE, 
				SPECIALTY_DESCRIPTION, 
				SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
				SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS, 
				CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
				CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE 
				FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_M
				WHERE MONTH = '+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
				AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+'
				AND DIAGNOSIS_CODE_TYPE = 3
				GROUP BY SPECIALTY_CODE, 
				SPECIALTY_DESCRIPTION 
				ORDER BY TOTAL_VARIANCE ASC'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR = 0 AND @QUARTER = 0 AND @MONTH = 0
BEGIN
     SET @SQL = 'SELECT SPECIALTY_CODE, 
				SPECIALTY_DESCRIPTION, 
				SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
				SUM(ISNULL(NO_OF_PHYSICIANS,0)) AS NO_OF_PHYSICIANS, 
				CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
				CEILING(SUM(ISNULL(TOTAL_VARIANCE,0))) AS TOTAL_VARIANCE 
				FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y
				WHERE YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+'
				AND DIAGNOSIS_CODE_TYPE = 3
				GROUP BY SPECIALTY_CODE, 
				SPECIALTY_DESCRIPTION 
				ORDER BY TOTAL_VARIANCE ASC'
END
EXEC sp_executesql @SQL
END
GO

IF OBJECT_ID('GET_PHY_SCORE_CARD_DATA') IS NOT NULL
DROP PROCEDURE GET_PHY_SCORE_CARD_DATA
GO
CREATE PROCEDURE GET_PHY_SCORE_CARD_DATA
@SPECIALTYCODE NVARCHAR(100), 
@PHYSICIAN_ID NVARCHAR(100),              
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT              
AS   
DECLARE @SQL NVARCHAR(MAX)              
BEGIN      
IF @HALFYEAR <> 0 
BEGIN
  SET @SQL =' SELECT SUM(ISNULL(MIN_PROC_COST,0)) AS MIN_PROC_COST, 
  SUM(ISNULL(MAX_PROC_COST,0)) AS MAX_PROC_COST, 
  DIAGNOSIS_CODE AS PROCEDURE_CODE, 
  DIAGNOSIS_DESCRIPTION AS PROCEDURE_DESCRIPTION, 
  PHYSICIAN_ID, 
  PHYSICIAN_NAME, 
  SUM(PHYSICIAN_RANK) AS PHYSICIAN_RANK, 
  SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES,
  CEILING(SUM(ISNULL(AVG_PROC_COST,0))) AS AVG_PROC_COST, 
  CEILING(SUM(ISNULL(EXTENDED_VARIANCE,0))) AS EXTENDED_VARIANCE, 
  CEILING(SUM(ISNULL(PER_VAR_TOTAL_SPEND,0))) AS TOTAL_VARIANCE, 
  SUM(ISNULL(NO_OF_PHY_DEPT,0)) AS NO_OF_PHY_DEPT, 
  SUM(ISNULL(NO_OF_PROCS_DEPT,0)) AS NO_OF_PROCS_DEPT, 
  CEILING(SUM(ISNULL(LOW_COST_AVG_DEPT,0))) AS LOW_COST_AVG_DEPT,
  ROUND((CONVERT(FLOAT,SUM(ISNULL(NO_OF_PROCEDURES,0)))/CONVERT(FLOAT,SUM(ISNULL(NO_OF_PROCS_DEPT,1))))*100,2) PER_PROC_PERFORMED,
 CEILING((SUM(ISNULL(AVG_PROC_COST,0)) - SUM(ISNULL(LOW_COST_AVG_DEPT,0)))) VAR_FROM_LOW_AVG
  FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
	WHERE PERIOD = '+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
	AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
	AND SPECIALTY_CODE = '''+@SPECIALTYCODE+''' 
	AND PHYSICIAN_ID = '''+@PHYSICIAN_ID+''' 
	AND DIAGNOSIS_CODE_TYPE = 3
	GROUP BY DIAGNOSIS_CODE, 
	DIAGNOSIS_DESCRIPTION, 
	PHYSICIAN_ID, 
	PHYSICIAN_NAME 
	ORDER BY PER_PROC_PERFORMED DESC'
END
ELSE IF @QUARTER <> 0
BEGIN
  SET @SQL=' SELECT SUM(ISNULL(MIN_PROC_COST,0)) AS MIN_PROC_COST, 
  SUM(ISNULL(MAX_PROC_COST,0)) AS MAX_PROC_COST, 
  DIAGNOSIS_CODE AS PROCEDURE_CODE, 
  DIAGNOSIS_DESCRIPTION AS PROCEDURE_DESCRIPTION,  
  PHYSICIAN_ID, 
  PHYSICIAN_NAME, 
  SUM(PHYSICIAN_RANK) AS PHYSICIAN_RANK, 
  SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
  CEILING(SUM(ISNULL(AVG_PROC_COST,0))) AS AVG_PROC_COST, 
  CEILING(SUM(ISNULL(EXTENDED_VARIANCE,0))) AS EXTENDED_VARIANCE, 
  CEILING(SUM(ISNULL(PER_VAR_TOTAL_SPEND,0))) AS TOTAL_VARIANCE, 
  SUM(ISNULL(NO_OF_PHY_DEPT,0)) AS NO_OF_PHY_DEPT, 
  SUM(ISNULL(NO_OF_PROCS_DEPT,0)) AS NO_OF_PROCS_DEPT, 
  CEILING(SUM(ISNULL(LOW_COST_AVG_DEPT,0))) AS LOW_COST_AVG_DEPT,
  ROUND((CONVERT(FLOAT,SUM(ISNULL(NO_OF_PROCEDURES,0)))/CONVERT(FLOAT,SUM(ISNULL(NO_OF_PROCS_DEPT,1))))*100,2) PER_PROC_PERFORMED,
 CEILING((SUM(ISNULL(AVG_PROC_COST,0)) - SUM(ISNULL(LOW_COST_AVG_DEPT,0)))) VAR_FROM_LOW_AVG  
  FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Q
  WHERE PERIOD = '+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
  AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
  AND SPECIALTY_CODE = '''+@SPECIALTYCODE+''' 
  AND PHYSICIAN_ID = '''+@PHYSICIAN_ID+''' 
  AND DIAGNOSIS_CODE_TYPE = 3
  GROUP BY DIAGNOSIS_CODE, 
  DIAGNOSIS_DESCRIPTION, 
  PHYSICIAN_ID, 
  PHYSICIAN_NAME 
  ORDER BY PER_PROC_PERFORMED DESC'
END
ELSE IF @MONTH <> 0 
BEGIN
     SET @SQL = 'SELECT SUM(ISNULL(MIN_PROC_COST,0)) AS MIN_PROC_COST, 
	 SUM(ISNULL(MAX_PROC_COST,0)) AS MAX_PROC_COST, 
	 DIAGNOSIS_CODE AS PROCEDURE_CODE, 
     DIAGNOSIS_DESCRIPTION AS PROCEDURE_DESCRIPTION, 
	 PHYSICIAN_ID, 
	 PHYSICIAN_NAME, 
	 SUM(PHYSICIAN_RANK) AS PHYSICIAN_RANK, 
	 SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
	 CEILING(SUM(ISNULL(AVG_PROC_COST,0))) AS AVG_PROC_COST, 
	 CEILING(SUM(ISNULL(EXTENDED_VARIANCE,0))) AS EXTENDED_VARIANCE, 
	 CEILING(SUM(ISNULL(PER_VAR_TOTAL_SPEND,0))) AS TOTAL_VARIANCE, 
	 SUM(ISNULL(NO_OF_PHY_DEPT,0)) AS NO_OF_PHY_DEPT, 
	 SUM(ISNULL(NO_OF_PROCS_DEPT,0)) AS NO_OF_PROCS_DEPT, 
	 CEILING(SUM(ISNULL(LOW_COST_AVG_DEPT,0))) AS LOW_COST_AVG_DEPT,
	 ROUND((CONVERT(FLOAT,SUM(ISNULL(NO_OF_PROCEDURES,0)))/CONVERT(FLOAT,SUM(ISNULL(NO_OF_PROCS_DEPT,1))))*100,2) PER_PROC_PERFORMED,
	CEILING((SUM(ISNULL(AVG_PROC_COST,0)) - SUM(ISNULL(LOW_COST_AVG_DEPT,0)))) VAR_FROM_LOW_AVG
	 FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_M
	 WHERE MONTH ='+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
	 AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
	 AND SPECIALTY_CODE = '''+@SPECIALTYCODE+''' 
	 AND PHYSICIAN_ID = '''+@PHYSICIAN_ID+''' 
	 AND DIAGNOSIS_CODE_TYPE = 3
	 GROUP BY DIAGNOSIS_CODE, 
	 DIAGNOSIS_DESCRIPTION, 
	 PHYSICIAN_ID, 
	 PHYSICIAN_NAME 
	 ORDER BY PER_PROC_PERFORMED DESC'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR = 0 AND	@QUARTER = 0 AND @MONTH = 0
BEGIN
     SET @SQL = 'SELECT SUM(ISNULL(MIN_PROC_COST,0)) AS MIN_PROC_COST, 
	 SUM(ISNULL(MAX_PROC_COST,0)) AS MAX_PROC_COST, 
	 DIAGNOSIS_CODE AS PROCEDURE_CODE, 
     DIAGNOSIS_DESCRIPTION AS PROCEDURE_DESCRIPTION,  
	 PHYSICIAN_ID, 
	 PHYSICIAN_NAME, 
	 SUM(PHYSICIAN_RANK) AS PHYSICIAN_RANK, 
	 SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
	 CEILING(SUM(ISNULL(AVG_PROC_COST,0))) AS AVG_PROC_COST, 
	 CEILING(SUM(ISNULL(EXTENDED_VARIANCE,0))) AS EXTENDED_VARIANCE, 
	 CEILING(SUM(ISNULL(PER_VAR_TOTAL_SPEND,0))) AS TOTAL_VARIANCE, 
	 SUM(ISNULL(NO_OF_PHY_DEPT,0)) AS NO_OF_PHY_DEPT, 
	 SUM(ISNULL(NO_OF_PROCS_DEPT,0)) AS NO_OF_PROCS_DEPT, 
	 CEILING(SUM(ISNULL(LOW_COST_AVG_DEPT,0))) AS LOW_COST_AVG_DEPT,
	 ROUND((CONVERT(FLOAT,SUM(ISNULL(NO_OF_PROCEDURES,0)))/CONVERT(FLOAT,SUM(ISNULL(NO_OF_PROCS_DEPT,1))))*100,2) PER_PROC_PERFORMED,
	CEILING((SUM(ISNULL(AVG_PROC_COST,0)) - SUM(ISNULL(LOW_COST_AVG_DEPT,0)))) VAR_FROM_LOW_AVG
	 FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y
		WHERE YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
		AND SPECIALTY_CODE = '''+@SPECIALTYCODE+''' 
		AND PHYSICIAN_ID = '''+@PHYSICIAN_ID+''' 
		AND DIAGNOSIS_CODE_TYPE = 3
		GROUP BY DIAGNOSIS_CODE, 
	    DIAGNOSIS_DESCRIPTION, 
		PHYSICIAN_ID, 
		PHYSICIAN_NAME 
		ORDER BY PER_PROC_PERFORMED DESC'
END
EXEC sp_executesql @SQL
END
GO   

IF OBJECT_ID('GET_PHY_RANK_DATA') IS NOT NULL
DROP PROCEDURE GET_PHY_RANK_DATA
GO
CREATE PROCEDURE GET_PHY_RANK_DATA
@SPECIALTYCODE NVARCHAR(100),               
@YEAR INT,                           
@HALFYEAR INT,                
@QUARTER INT,
@MONTH INT              
AS   
DECLARE @SQL NVARCHAR(MAX)              
BEGIN      
IF @HALFYEAR <> 0 
BEGIN
	SET @SQL = 
		'SELECT DENSE_RANK() OVER(ORDER BY CASE WHEN SUM(ISNULL(TOTAL_SPEND,0)) > 0 THEN (SUM(ISNULL([EXTENDED_VARIANCE],0)) / SUM(ISNULL(TOTAL_SPEND,0))) * 100 ELSE 0 END ASC) PHYSICIAN_RANK,
		PHYSICIAN_ID, 
		PHYSICIAN_NAME, 
		SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
		CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
		CEILING(SUM(ISNULL([EXTENDED_VARIANCE],0))) AS TOTAL_VARIANCE, 
		CASE WHEN SUM(ISNULL(TOTAL_SPEND,0)) > 0 THEN (SUM(ISNULL([EXTENDED_VARIANCE],0)) / SUM(ISNULL(TOTAL_SPEND,0))) * 100 ELSE 0 END AS PER_VAR_TOTAL_SPEND 
		FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
			WHERE PERIOD = '+ CAST(@HALFYEAR AS NVARCHAR(MAX)) +' 
			AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE = '''+@SPECIALTYCODE+''' 
			AND DIAGNOSIS_CODE_TYPE = 3
			GROUP BY PHYSICIAN_ID, 
			PHYSICIAN_NAME 
			ORDER BY PER_VAR_TOTAL_SPEND ASC'
END
ELSE IF @QUARTER <>0
BEGIN
  SET @SQL = 
		'SELECT DENSE_RANK() OVER(ORDER BY CASE WHEN SUM(ISNULL(TOTAL_SPEND,0)) > 0 THEN (SUM(ISNULL([EXTENDED_VARIANCE],0)) / SUM(ISNULL(TOTAL_SPEND,0))) * 100 ELSE 0 END ASC) PHYSICIAN_RANK,
		PHYSICIAN_ID, 
		PHYSICIAN_NAME, 
		SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
		CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
		CEILING(SUM(ISNULL([EXTENDED_VARIANCE],0))) AS TOTAL_VARIANCE, 
		CASE WHEN SUM(ISNULL(TOTAL_SPEND,0)) > 0 THEN (SUM(ISNULL([EXTENDED_VARIANCE],0)) / SUM(ISNULL(TOTAL_SPEND,0))) * 100 ELSE 0 END AS PER_VAR_TOTAL_SPEND 
		FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Q
			WHERE PERIOD = '+ CAST(@QUARTER AS NVARCHAR(MAX)) +' 
			AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE = '''+@SPECIALTYCODE+''' 
			AND DIAGNOSIS_CODE_TYPE = 3
			GROUP BY PHYSICIAN_ID, 
			PHYSICIAN_NAME 
			ORDER BY PER_VAR_TOTAL_SPEND ASC'
END
ELSE IF @MONTH <> 0 
BEGIN
     SET @SQL = 
			'SELECT DENSE_RANK() OVER(ORDER BY CASE WHEN SUM(ISNULL(TOTAL_SPEND,0)) > 0 THEN (SUM(ISNULL([EXTENDED_VARIANCE],0)) / SUM(ISNULL(TOTAL_SPEND,0))) * 100 ELSE 0 END ASC) PHYSICIAN_RANK,
			PHYSICIAN_ID, 
			PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
			CEILING(SUM(ISNULL([EXTENDED_VARIANCE],0))) AS TOTAL_VARIANCE, 
			CASE WHEN SUM(ISNULL(TOTAL_SPEND,0)) > 0 THEN (SUM(ISNULL([EXTENDED_VARIANCE],0)) / SUM(ISNULL(TOTAL_SPEND,0))) * 100 ELSE 0 END AS PER_VAR_TOTAL_SPEND 
			FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_M
				WHERE MONTH = '+ CAST(@MONTH AS NVARCHAR(MAX)) +' 
				AND YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
				AND SPECIALTY_CODE = '''+@SPECIALTYCODE+''' 
				AND DIAGNOSIS_CODE_TYPE = 3
				GROUP BY PHYSICIAN_ID, 
				PHYSICIAN_NAME 
				ORDER BY PER_VAR_TOTAL_SPEND ASC'
END
ELSE IF @YEAR <> 0 AND @HALFYEAR = 0 AND @QUARTER = 0 AND @MONTH = 0
BEGIN
     SET @SQL = 
			'SELECT DENSE_RANK() OVER(ORDER BY CASE WHEN SUM(ISNULL(TOTAL_SPEND,0)) > 0 THEN (SUM(ISNULL([EXTENDED_VARIANCE],0)) / SUM(ISNULL(TOTAL_SPEND,0))) * 100 ELSE 0 END ASC) PHYSICIAN_RANK,
			PHYSICIAN_ID, 
			PHYSICIAN_NAME, 
			SUM(ISNULL(NO_OF_PROCEDURES,0)) AS NO_OF_PROCEDURES, 
			CEILING(SUM(ISNULL(TOTAL_SPEND,0))) AS TOTAL_SPEND, 
			CEILING(SUM(ISNULL([EXTENDED_VARIANCE],0))) AS TOTAL_VARIANCE, 
			CASE WHEN SUM(ISNULL(TOTAL_SPEND,0)) > 0 THEN (SUM(ISNULL([EXTENDED_VARIANCE],0)) / SUM(ISNULL(TOTAL_SPEND,0))) * 100 ELSE 0 END AS PER_VAR_TOTAL_SPEND 
			FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_Y
			WHERE YEAR = '+ CAST(@YEAR AS NVARCHAR(MAX))+' 
			AND SPECIALTY_CODE = '''+@SPECIALTYCODE+''' 
			AND DIAGNOSIS_CODE_TYPE = 3
			GROUP BY PHYSICIAN_ID, 
			PHYSICIAN_NAME 
			ORDER BY PER_VAR_TOTAL_SPEND ASC'
END
EXEC sp_executesql @SQL
END
GO  




