--By ICD

------------------COST VARIANCE BY SPECIALTY---------------------------
--DROP TABLE TEMP_PHYSICIAN_AVERAGE
--DROP TABLE TEMP
--by procedure
--TEMP TABLE:contains min max average usage among all physicians


--BY YEAR
--  SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y WHERE DIAGNOSIS_CODE_TYPE=1

DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y WHERE DIAGNOSIS_CODE_TYPE=1
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y
		    ([SPECIALTY_CODE]
           ,[SPECIALTY_DESCRIPTION]
           ,[NO_OF_PROCEDURES]
           ,[NO_OF_PHYSICIANS]
           ,[TOTAL_SPEND]
           ,[TOTAL_VARIANCE]
		   ,[DIAGNOSIS_CODE_TYPE]
           ,[YEAR])
SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION, SUM(NO_OF_PROCEDURES), SUM(NO_OF_PHYSICIANS) , SUM([TOTAL_SPEND]), SUM([TOTAL_VARIANCE]), DIAGNOSIS_CODE_TYPE,[YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y WHERE DIAGNOSIS_CODE_TYPE=1
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION,DIAGNOSIS_CODE_TYPE,[YEAR]




--By PROCEDURE

------------------COST VARIANCE BY SPECIALTY---------------------------

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE')
BEGIN
drop table TEMP_PHYSICIAN_AVERAGE
END

--DROP TABLE TEMP

--TEMP TABLE:contains min max average usage among all physicians


--BY YEAR
--  SELECT * FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y WHERE DIAGNOSIS_CODE_TYPE=1

DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y WHERE DIAGNOSIS_CODE_TYPE=1
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y
		    ([SPECIALTY_CODE]
           ,[SPECIALTY_DESCRIPTION]
           ,[NO_OF_PROCEDURES]
           ,[NO_OF_PHYSICIANS]
           ,[TOTAL_SPEND]
           ,[TOTAL_VARIANCE]
		   ,[DIAGNOSIS_CODE_TYPE]
           ,[YEAR])
SELECT SPECIALTY_CODE,SPECIALTY_DESCRIPTION, SUM(NO_OF_PROCEDURES), SUM(NO_OF_PHYSICIANS) , SUM([TOTAL_SPEND]), SUM([TOTAL_VARIANCE]), DIAGNOSIS_CODE_TYPE,[YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y WHERE DIAGNOSIS_CODE_TYPE=1
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION,DIAGNOSIS_CODE_TYPE,[YEAR]


DELETE FROM MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y WHERE [DIAGNOSIS_CODE_TYPE]=3
INSERT INTO MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y
	([SPECIALTY_CODE]
	,[SPECIALTY_DESCRIPTION]
	,[NO_OF_PROCEDURES]
	,[NO_OF_PHYSICIANS]
	,[TOTAL_SPEND]
	,[TOTAL_VARIANCE]
	,[DIAGNOSIS_CODE_TYPE]
	,[YEAR])
SELECT SPECIALTY_CODE,
SPECIALTY_DESCRIPTION, 
SUM(NO_OF_PROCEDURES), 
AVG(TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC.NO_OF_PHYSICIANS) , 
SUM([TOTAL_SPEND]), 
SUM([TOTAL_VARIANCE]), 
DIAGNOSIS_CODE_TYPE, 
MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.[YEAR] 
FROM MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y,TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC
WHERE DIAGNOSIS_CODE_TYPE = 3
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.SPECIALTY_CODE= TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC.SERVICE_CODE
AND MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.[YEAR]= TEMP_PHYSICIAN_COUNT_TAB2_SUMMARY_Y_PROC.[YEAR] 
GROUP BY SPECIALTY_CODE,SPECIALTY_DESCRIPTION, DIAGNOSIS_CODE_TYPE,MT_POU_RPT_COST_VARIANCE_BY_REIMBURSEMENT_Y.[YEAR]

update MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y set SPECIALTY_CODE='OTHERS' where SPECIALTY_CODE=''
update MT_POU_RPT_COST_VARIANCE_BY_SPECIALTY_Y set SPECIALTY_DESCRIPTION=SPECIALTY_CODE where SPECIALTY_DESCRIPTION=''






