--By ICD:



IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_ICD_H1')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_ICD_H1
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PROCEDURES_COUNT_H1_ICD')
BEGIN
DROP TABLE TEMP_PROCEDURES_COUNT_H1_ICD
END


--DROP TABLE TEMP_PHYSICIAN_AVERAGE_ICD_H1
--DROP TABLE TEMP_PROCEDURES_COUNT_H1_ICD


  --DELETE FROM MT_POU_RPT_SPEND_BY_GROUP_H
--BY ICD
--MT_POU_RPT_SPEND_BY_GROUP

-------------------------------------------------------------------------------------

-------------------------PROCEDURES COUNT--------------------

SELECT COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SERVICE_CODE, PHYSICIAN, ICD10,
 DATEPART(YYYY,[performdatewtime]) [YEAR] INTO TEMP_PROCEDURES_COUNT_H1_ICD
FROM [Item_details]
WHERE datepart(mm,[performdatewtime]) <= 6 and ICD10 is not null
GROUP BY  SERVICE_CODE, PHYSICIAN, ICD10,
DATEPART(YYYY,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_ICD_H1 TABLE:contains min max average usage by physician and item group

SELECT DISTINCT([Group]) [Group], C.SERVICE_CODE, PHYSICIAN, ICD10, [ICD10 DESCRIPTION], SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY, SUM(TOTAL_SPEND) TOTAL_SPEND, 
				 [YEAR] INTO TEMP_PHYSICIAN_AVERAGE_ICD_H1
FROM (SELECT SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, CASEID, [Group] ,  SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED]))  TOTAL_ITEM_QTY, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY]) - (([TOTALRETURNED] + [TOTAL WASTED]))) * [CURRENTITEMCOST])) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details]
			 WHERE 
			ICD10 IS NOT NULL AND 
			 datepart(mm,[performdatewtime]) <= 6 
			 --WHERE SERVICE_CODE='ORTHOPEDICS' AND ICD10 IS NOT NULL AND ICD10='C79.51'			  
GROUP BY SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]), [Group]) C
GROUP BY SERVICE_CODE, PHYSICIAN, ICD10, [ICD10 DESCRIPTION], [YEAR], [Group]

------------------------------------------------
 

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_ICD_H1 ADD NO_OF_CASES INT


UPDATE TEMP_PHYSICIAN_AVERAGE_ICD_H1 SET TEMP_PHYSICIAN_AVERAGE_ICD_H1.NO_OF_CASES = TEMP_PROCEDURES_COUNT_H1_ICD.NO_OF_PROCEDURES
--SELECT TEMP_PROCEDURES_COUNT_H1_ICD.NO_OF_PROCEDURES
FROM TEMP_PHYSICIAN_AVERAGE_ICD_H1, TEMP_PROCEDURES_COUNT_H1_ICD
WHERE TEMP_PHYSICIAN_AVERAGE_ICD_H1.SERVICE_CODE = TEMP_PROCEDURES_COUNT_H1_ICD.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_ICD_H1.PHYSICIAN = TEMP_PROCEDURES_COUNT_H1_ICD.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_ICD_H1.[YEAR] = TEMP_PROCEDURES_COUNT_H1_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_ICD_H1.ICD10 = TEMP_PROCEDURES_COUNT_H1_ICD.ICD10
------------------------------H2-----------------------------------------------------------------

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_ICD_H2')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_ICD_H2
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PROCEDURES_COUNT_H2_ICD')
BEGIN
DROP TABLE TEMP_PROCEDURES_COUNT_H2_ICD
END


--DROP TABLE TEMP_PHYSICIAN_AVERAGE_ICD_H2
--DROP TABLE TEMP_PROCEDURES_COUNT_H2_ICD


-------------------------PROCEDURES COUNT--------------------

SELECT COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SERVICE_CODE, PHYSICIAN, ICD10,
 DATEPART(YYYY,[performdatewtime]) [YEAR] INTO TEMP_PROCEDURES_COUNT_H2_ICD
FROM [Item_details]
WHERE datepart(mm,[performdatewtime]) >= 7 and ICD10 is not null
GROUP BY  SERVICE_CODE, PHYSICIAN, ICD10,
DATEPART(YYYY,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_ICD_H2 TABLE:contains min max average usage by physician and item group

SELECT DISTINCT([Group]) [Group], C.SERVICE_CODE, PHYSICIAN, ICD10, [ICD10 DESCRIPTION], SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY, SUM(TOTAL_SPEND) TOTAL_SPEND, 
				 [YEAR] INTO TEMP_PHYSICIAN_AVERAGE_ICD_H2
FROM (SELECT SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, CASEID, [Group] ,  SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED]))  TOTAL_ITEM_QTY, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY]) - (([TOTALRETURNED] + [TOTAL WASTED]))) * [CURRENTITEMCOST])) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details]
			 WHERE 
			 ICD10 IS NOT NULL AND 
			 datepart(mm,[performdatewtime])  >= 7
			 --WHERE SERVICE_CODE='ORTHOPEDICS' AND ICD10 IS NOT NULL AND ICD10='C79.51'			  
GROUP BY SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]), [Group]) C
GROUP BY SERVICE_CODE, PHYSICIAN, ICD10, [ICD10 DESCRIPTION], [YEAR], [Group]

------------------------------------------------
 

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_ICD_H2 ADD NO_OF_CASES INT


UPDATE TEMP_PHYSICIAN_AVERAGE_ICD_H2 SET TEMP_PHYSICIAN_AVERAGE_ICD_H2.NO_OF_CASES = TEMP_PROCEDURES_COUNT_H2_ICD.NO_OF_PROCEDURES
--SELECT TEMP_PROCEDURES_COUNT_H2_ICD.NO_OF_PROCEDURES
FROM TEMP_PHYSICIAN_AVERAGE_ICD_H2, TEMP_PROCEDURES_COUNT_H2_ICD
WHERE TEMP_PHYSICIAN_AVERAGE_ICD_H2.SERVICE_CODE = TEMP_PROCEDURES_COUNT_H2_ICD.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_ICD_H2.PHYSICIAN = TEMP_PROCEDURES_COUNT_H2_ICD.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_ICD_H2.[YEAR] = TEMP_PROCEDURES_COUNT_H2_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_ICD_H2.ICD10 = TEMP_PROCEDURES_COUNT_H2_ICD.ICD10

-- delete from MT_POU_RPT_SPEND_BY_GROUP_H WHERE [DIAGNOSIS_CODE_TYPE]=1(10923)
INSERT INTO MT_POU_RPT_SPEND_BY_GROUP_H
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[NO_OF_ITEMS_BY_ITEM_GROUP]
,[ITEM_GROUP]
,[ITEM_GROUP_DESCRIPTION]
,[TOTAL_NO_OF_CASES_PHYSICIAN]
,[TOTAL_COST_ITEM_GROUP]
,[PERIOD]
,[YEAR])
SELECT TEMP_PHYSICIAN_AVERAGE_ICD_H1.SERVICE_CODE, ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H1.ICD10, ' '),
-- ' ',  
--ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H1.ICD10, ' ') ICD10, 
ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H1.[ICD10 DESCRIPTION], ' '),
 1 AS 'DIAGNOSIS_CODE_TYPE',  
--ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H1.[ICD10 DESCRIPTION], ' ') ICD10_DESCR ,' ', 
 ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H1.PHYSICIAN,' '), 
 '' PHYSICIAN_NAME,  
SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY,[Group],[Group], AVG(ISNULL(TEMP_PROCEDURES_COUNT_H1_ICD.NO_OF_PROCEDURES,0)),  
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND,
1,
TEMP_PHYSICIAN_AVERAGE_ICD_H1.[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_ICD_H1, TEMP_PROCEDURES_COUNT_H1_ICD
WHERE TEMP_PHYSICIAN_AVERAGE_ICD_H1.SERVICE_CODE = TEMP_PROCEDURES_COUNT_H1_ICD.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_ICD_H1.PHYSICIAN = TEMP_PROCEDURES_COUNT_H1_ICD.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_ICD_H1.[YEAR] = TEMP_PROCEDURES_COUNT_H1_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_ICD_H1.ICD10 = TEMP_PROCEDURES_COUNT_H1_ICD.ICD10
--AND  TEMP_PHYSICIAN_AVERAGE_ICD_H1.SERVICE_CODE='ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_ICD_H1.ICD10='M17.12'
GROUP BY TEMP_PHYSICIAN_AVERAGE_ICD_H1.SERVICE_CODE,TEMP_PHYSICIAN_AVERAGE_ICD_H1.ICD10,TEMP_PHYSICIAN_AVERAGE_ICD_H1.[ICD10 DESCRIPTION],
TEMP_PHYSICIAN_AVERAGE_ICD_H1.PHYSICIAN,[Group],TEMP_PHYSICIAN_AVERAGE_ICD_H1.[YEAR]

UNION
SELECT TEMP_PHYSICIAN_AVERAGE_ICD_H2.SERVICE_CODE, ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H2.ICD10, ' '), 
--' ',  ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H2.ICD10, ' ') ICD10, 
ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H2.[ICD10 DESCRIPTION], ' ') ,
1 AS 'DIAGNOSIS_CODE_TYPE', 
-- ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H2.[ICD10 DESCRIPTION], ' ') ICD10_DESCR ,' ', 
ISNULL(TEMP_PHYSICIAN_AVERAGE_ICD_H2.PHYSICIAN,' ') PHYSICIAN, 
 '' PHYSICIAN_NAME,  
SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY,[Group],[Group], AVG(ISNULL(TEMP_PROCEDURES_COUNT_H2_ICD.NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND,
2,
TEMP_PHYSICIAN_AVERAGE_ICD_H2.[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_ICD_H2, TEMP_PROCEDURES_COUNT_H2_ICD
WHERE TEMP_PHYSICIAN_AVERAGE_ICD_H2.SERVICE_CODE = TEMP_PROCEDURES_COUNT_H2_ICD.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_ICD_H2.PHYSICIAN = TEMP_PROCEDURES_COUNT_H2_ICD.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_ICD_H2.[YEAR] = TEMP_PROCEDURES_COUNT_H2_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_ICD_H2.ICD10 = TEMP_PROCEDURES_COUNT_H2_ICD.ICD10
--AND  TEMP_PHYSICIAN_AVERAGE_ICD_H2.SERVICE_CODE='ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_ICD_H2.ICD10='M17.12'
GROUP BY TEMP_PHYSICIAN_AVERAGE_ICD_H2.SERVICE_CODE,TEMP_PHYSICIAN_AVERAGE_ICD_H2.ICD10,TEMP_PHYSICIAN_AVERAGE_ICD_H2.[ICD10 DESCRIPTION],
TEMP_PHYSICIAN_AVERAGE_ICD_H2.PHYSICIAN,[Group],TEMP_PHYSICIAN_AVERAGE_ICD_H2.[YEAR]
--ORDER BY TEMP_PHYSICIAN_AVERAGE_ICD_H2.[Group]



--UPDATE MT_POU_RPT_SPEND_BY_GROUP_H SET DIAGNOSIS_CODE_TYPE=3 WHERE ICD_CODE=' ' AND ICD10 IS NOT NULL
--SELECT COUNT(*) FROM MT_POU_RPT_SPEND_BY_GROUP_H WHERE ICD_CODE=' ' AND ICD10 IS NOT NULL

-----------------------------
UPDATE MT_POU_RPT_SPEND_BY_GROUP_H SET [PHYSICIAN_NAME]=ISNULL([Item_details].SURGE_DESCIPTION_orig,'') FROM MT_POU_RPT_SPEND_BY_GROUP_H,[Item_details]
WHERE MT_POU_RPT_SPEND_BY_GROUP_H.PHYSICIAN_ID=[Item_details].PHYSICIAN


--------------------------------
--SELECT ITEM_GROUP, SUM([TOTAL_COST_ITEM_GROUP]) FROM MT_POU_RPT_SPEND_BY_GROUP_H WHERE SPECIALTY_CODE='ORTHOPEDICS' AND ICD_CODE='M17.12' GROUP BY ITEM_GROUP





--By PROCEDURE:

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_PROC_H1')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_ICD_H1
END


IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PROCEDURES_COUNT_H1_PROC')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_ICD_H1
END



--DROP TABLE TEMP_PHYSICIAN_AVERAGE_PROC_H1
--DROP TABLE TEMP_PROCEDURES_COUNT_H1_PROC


  --DELETE FROM MT_POU_RPT_SPEND_BY_GROUP_H
--BY ICD
--MT_POU_RPT_SPEND_BY_GROUP

-------------------------------------------------------------------------------------

-------------------------PROCEDURES COUNT--------------------

SELECT COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE,
 DATEPART(YYYY,[performdatewtime]) [YEAR] INTO TEMP_PROCEDURES_COUNT_H1_PROC
FROM [Item_details]
WHERE datepart(mm,[performdatewtime]) <= 6 
GROUP BY  SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE,
DATEPART(YYYY,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_PROC_H1 TABLE:contains min max average usage by physician and item group

SELECT DISTINCT([Group]) [Group], C.SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE, proc_descr, SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY, SUM(TOTAL_SPEND) TOTAL_SPEND, 
				 [YEAR] INTO TEMP_PHYSICIAN_AVERAGE_PROC_H1
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, CASEID, [Group] ,  SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED]))  TOTAL_ITEM_QTY, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY]) - (([TOTALRETURNED] + [TOTAL WASTED]))) * [CURRENTITEMCOST])) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details]
			 --WHERE PROCEDURE_CODE IS NOT NULL 
			WHERE datepart(mm,[performdatewtime]) <= 6 
			 --WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='C79.51'			  
GROUP BY SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]), [Group]) C
GROUP BY SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE, proc_descr, [YEAR], [Group]

------------------------------------------------
 

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_PROC_H1 ADD NO_OF_CASES INT


UPDATE TEMP_PHYSICIAN_AVERAGE_PROC_H1 SET TEMP_PHYSICIAN_AVERAGE_PROC_H1.NO_OF_CASES = TEMP_PROCEDURES_COUNT_H1_PROC.NO_OF_PROCEDURES
--SELECT TEMP_PROCEDURES_COUNT_H1_PROC.NO_OF_PROCEDURES
FROM TEMP_PHYSICIAN_AVERAGE_PROC_H1, TEMP_PROCEDURES_COUNT_H1_PROC
WHERE TEMP_PHYSICIAN_AVERAGE_PROC_H1.SERVICE_CODE = TEMP_PROCEDURES_COUNT_H1_PROC.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_PROC_H1.PHYSICIAN = TEMP_PROCEDURES_COUNT_H1_PROC.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_PROC_H1.[YEAR] = TEMP_PROCEDURES_COUNT_H1_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_PROC_H1.PROCEDURE_CODE = TEMP_PROCEDURES_COUNT_H1_PROC.PROCEDURE_CODE
------------------------------H2-----------------------------------------------------------------
--DROP TABLE TEMP_PHYSICIAN_AVERAGE_PROC_H2
--DROP TABLE TEMP_PROCEDURES_COUNT_H2_PROC
-------------------------PROCEDURES COUNT--------------------

SELECT COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE,
 DATEPART(YYYY,[performdatewtime]) [YEAR] INTO TEMP_PROCEDURES_COUNT_H2_PROC
FROM [Item_details]
WHERE datepart(mm,[performdatewtime]) >= 7 
GROUP BY  SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE,
DATEPART(YYYY,[performdatewtime])

-------------------------
--TEMP_PHYSICIAN_AVERAGE_PROC_H2 TABLE:contains min max average usage by physician and item group

SELECT DISTINCT([Group]) [Group], C.SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE, proc_descr, SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY, SUM(TOTAL_SPEND) TOTAL_SPEND, 
				 [YEAR] INTO TEMP_PHYSICIAN_AVERAGE_PROC_H2
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, CASEID, [Group] ,  SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED]))  TOTAL_ITEM_QTY, 
			 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY]) - (([TOTALRETURNED] + [TOTAL WASTED]))) * [CURRENTITEMCOST])) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details]
			 WHERE 
			 --PROCEDURE_CODE IS NOT NULL 
			--AND 
			 datepart(mm,[performdatewtime])  >= 7
			 --WHERE SERVICE_CODE='ORTHOPEDICS' AND PROCEDURE_CODE IS NOT NULL AND PROCEDURE_CODE='C79.51'			  
GROUP BY SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]), [Group]) C
GROUP BY SERVICE_CODE, PHYSICIAN, PROCEDURE_CODE, proc_descr, [YEAR], [Group]

------------------------------------------------
 

ALTER TABLE TEMP_PHYSICIAN_AVERAGE_PROC_H2 ADD NO_OF_CASES INT


UPDATE TEMP_PHYSICIAN_AVERAGE_PROC_H2 SET TEMP_PHYSICIAN_AVERAGE_PROC_H2.NO_OF_CASES = TEMP_PROCEDURES_COUNT_H2_PROC.NO_OF_PROCEDURES
--SELECT TEMP_PROCEDURES_COUNT_H2_PROC.NO_OF_PROCEDURES
FROM TEMP_PHYSICIAN_AVERAGE_PROC_H2, TEMP_PROCEDURES_COUNT_H2_PROC
WHERE TEMP_PHYSICIAN_AVERAGE_PROC_H2.SERVICE_CODE = TEMP_PROCEDURES_COUNT_H2_PROC.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_PROC_H2.PHYSICIAN = TEMP_PROCEDURES_COUNT_H2_PROC.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_PROC_H2.[YEAR] = TEMP_PROCEDURES_COUNT_H2_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_PROC_H2.PROCEDURE_CODE = TEMP_PROCEDURES_COUNT_H2_PROC.PROCEDURE_CODE

--select * from MT_POU_RPT_SPEND_BY_GROUP_H
-- delete from MT_POU_RPT_SPEND_BY_GROUP_H (10923)
INSERT INTO MT_POU_RPT_SPEND_BY_GROUP_H
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[NO_OF_ITEMS_BY_ITEM_GROUP]
,[ITEM_GROUP]
,[ITEM_GROUP_DESCRIPTION]
,[TOTAL_NO_OF_CASES_PHYSICIAN]
,[TOTAL_COST_ITEM_GROUP]
,[PERIOD]
,[YEAR])
SELECT TEMP_PHYSICIAN_AVERAGE_PROC_H1.SERVICE_CODE,
-- ' ', ' ',
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_H1.PROCEDURE_CODE, ' ') PROCEDURE_CODE, 
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_H1.proc_descr, ' ') PROCEDURE_DESCR,
 3 AS 'DIAGNOSIS_CODE_TYPE',
-- ' ' ICD10_DESCR ,' ', 
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_H1.PHYSICIAN,' ') PHYSICIAN, 
 '' PHYSICIAN_NAME,  
SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY,[Group],[Group], AVG(ISNULL(TEMP_PROCEDURES_COUNT_H1_PROC.NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND,
1,
TEMP_PHYSICIAN_AVERAGE_PROC_H1.[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_PROC_H1, TEMP_PROCEDURES_COUNT_H1_PROC
WHERE TEMP_PHYSICIAN_AVERAGE_PROC_H1.SERVICE_CODE = TEMP_PROCEDURES_COUNT_H1_PROC.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_PROC_H1.PHYSICIAN = TEMP_PROCEDURES_COUNT_H1_PROC.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_PROC_H1.[YEAR] = TEMP_PROCEDURES_COUNT_H1_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_PROC_H1.PROCEDURE_CODE = TEMP_PROCEDURES_COUNT_H1_PROC.PROCEDURE_CODE
--AND  TEMP_PHYSICIAN_AVERAGE_PROC_H1.SERVICE_CODE='ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_PROC_H1.PROCEDURE_CODE='M17.12'
GROUP BY TEMP_PHYSICIAN_AVERAGE_PROC_H1.SERVICE_CODE,TEMP_PHYSICIAN_AVERAGE_PROC_H1.PROCEDURE_CODE,TEMP_PHYSICIAN_AVERAGE_PROC_H1.proc_descr,
TEMP_PHYSICIAN_AVERAGE_PROC_H1.PHYSICIAN,[Group],TEMP_PHYSICIAN_AVERAGE_PROC_H1.[YEAR]

UNION
SELECT TEMP_PHYSICIAN_AVERAGE_PROC_H2.SERVICE_CODE,
--' ', ' ',
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_H2.PROCEDURE_CODE, ' ') PROCEDURE_CODE, 
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_H2.proc_descr, ' ') PROCEDURE_DESCR,
 3 AS 'DIAGNOSIS_CODE_TYPE',
--' ' ICD10_DESCR ,' ', 
ISNULL(TEMP_PHYSICIAN_AVERAGE_PROC_H2.PHYSICIAN,' ') PHYSICIAN, 
 '' PHYSICIAN_NAME,  
SUM(TOTAL_ITEM_QTY) TOTAL_ITEM_QTY,[Group],[Group], AVG(ISNULL(TEMP_PROCEDURES_COUNT_H2_PROC.NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  
ROUND(SUM(ISNULL(TOTAL_SPEND,0)),2) TOTAL_SPEND,
2,
TEMP_PHYSICIAN_AVERAGE_PROC_H2.[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_PROC_H2, TEMP_PROCEDURES_COUNT_H2_PROC
WHERE TEMP_PHYSICIAN_AVERAGE_PROC_H2.SERVICE_CODE = TEMP_PROCEDURES_COUNT_H2_PROC.SERVICE_CODE
AND TEMP_PHYSICIAN_AVERAGE_PROC_H2.PHYSICIAN = TEMP_PROCEDURES_COUNT_H2_PROC.PHYSICIAN
AND TEMP_PHYSICIAN_AVERAGE_PROC_H2.[YEAR] = TEMP_PROCEDURES_COUNT_H2_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_PROC_H2.PROCEDURE_CODE = TEMP_PROCEDURES_COUNT_H2_PROC.PROCEDURE_CODE
--AND  TEMP_PHYSICIAN_AVERAGE_PROC_H2.SERVICE_CODE='ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_PROC_H2.PROCEDURE_CODE='M17.12'
GROUP BY TEMP_PHYSICIAN_AVERAGE_PROC_H2.SERVICE_CODE,TEMP_PHYSICIAN_AVERAGE_PROC_H2.PROCEDURE_CODE,TEMP_PHYSICIAN_AVERAGE_PROC_H2.proc_descr,
TEMP_PHYSICIAN_AVERAGE_PROC_H2.PHYSICIAN,[Group],TEMP_PHYSICIAN_AVERAGE_PROC_H2.[YEAR]
--ORDER BY TEMP_PHYSICIAN_AVERAGE_PROC_H2.[Group]

--UPDATE MT_POU_RPT_SPEND_BY_GROUP_H SET DIAGNOSIS_CODE_TYPE=3 WHERE ICD_CODE=' ' AND PROCEDURE_CODE IS NOT NULL
--SELECT COUNT(*) FROM MT_POU_RPT_SPEND_BY_GROUP_H WHERE ICD_CODE=' ' AND PROCEDURE_CODE IS NOT NULL

-----------------------------
UPDATE MT_POU_RPT_SPEND_BY_GROUP_H SET [PHYSICIAN_NAME]=ISNULL([Item_details].SURGE_DESCIPTION_orig,'') FROM MT_POU_RPT_SPEND_BY_GROUP_H,[Item_details]
WHERE MT_POU_RPT_SPEND_BY_GROUP_H.PHYSICIAN_ID=[Item_details].PHYSICIAN


--------------------------------
--SELECT ITEM_GROUP, SUM([TOTAL_COST_ITEM_GROUP]) FROM MT_POU_RPT_SPEND_BY_GROUP_H WHERE SPECIALTY_CODE='ORTHOPEDICS' AND ICD_CODE='M17.12' GROUP BY ITEM_GROUP


