--By ICD:


--MT_POU_RPT_SUPPLY_COMPARISON
--MT_POU_RPT_SUPPLY_COMPARISON_M

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_TAB3_H1_ICD')
BEGIN
DROP TABLE TEMP_TAB3_H1_ICD
END


-- DROP TABLE MT_POU_RPT_SUPPLY_COMPARISON_H
-------------------------
ALTER TABLE [Item_details]
ALTER COLUMN [ICD10] [nvarchar](255) NULL
---------------------
--ALTER TABLE MT_POU_RPT_SUPPLY_COMPARISON_M
--ALTER COLUMN PROCEDURE_DESCRIPTION NVARCHAR(254) NULL

-- BY QUARTER

	-- DELETE FROM MT_POU_RPT_SUPPLY_COMPARISON_H where [DIAGNOSIS_CODE_TYPE]=1(297404)
INSERT INTO MT_POU_RPT_SUPPLY_COMPARISON_H
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[ITEM_GROUP]
,[ITEM_GROUP_DESCRIPTION]
,[ITEM_ID]
,[ITEM_DESCRIPTION]
,[MFR_CATALOG_NO]
,[UNIT_COST]
,[NO_OF_TIMES_ITEM_USED_BY_PHY]
,[PERIOD]
,[YEAR])
SELECT SERVICE_CODE, 
ISNULL(ICD10, ' ') ICD10,
-- ' ' [CPT_CODE], ISNULL(ICD10, ' ') ICD10, ISNULL([ICD10 DESCRIPTION],' ') PROCEDURE_DESCR , 
ISNULL([ICD10 DESCRIPTION],' ') ICD10_DESCR,1 AS 'DIAGNOSIS_CODE_TYPE',
--' ' [CPT_DESCR], 
ISNULL(PHYSICIAN,' ') PHYSICIAN, ' ' PHYSICIAN_NAME,  
[Group],[Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID], AVG(ISNULL([CURRENTITEMCOST],0)) [CURRENTITEMCOST], ISNULL(SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])),0)  TOTAL_ITEM_QTY ,  
1,
DATEPART(YYYY,[performdatewtime]) [YEAR] 
FROM [Item_details] 
WHERE [POU ITEM] IS NOT NULL 
AND ICD10 IS NOT NULL 
AND datepart(mm,[performdatewtime]) <= 6
--AND SERVICE_CODE = 'UROLOGY' AND ICD10 = 'Z43.6' AND PHYSICIAN = 'KOGAN' AND [POU ITEM] = '10884521007819'
GROUP BY SERVICE_CODE, ICD10,[ICD10 DESCRIPTION], PHYSICIAN, [Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID],
 DATEPART(YYYY,[performdatewtime])

UNION

SELECT SERVICE_CODE, ISNULL(ICD10, ' ') ICD10,
-- ' ' [CPT_CODE], ISNULL(ICD10, ' ') ICD10, ISNULL([ICD10 DESCRIPTION],' ') PROCEDURE_DESCR , 
ISNULL([ICD10 DESCRIPTION],' ') ICD10_DESCR,1 AS 'DIAGNOSIS_CODE_TYPE',
--' ' [CPT_DESCR], 
ISNULL(PHYSICIAN,' ') PHYSICIAN, ' ' PHYSICIAN_NAME,  
[Group],[Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID], AVG(ISNULL([CURRENTITEMCOST],0)) [CURRENTITEMCOST], ISNULL(SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])),0)  TOTAL_ITEM_QTY ,  
2,
DATEPART(YYYY,[performdatewtime]) [YEAR] 
FROM [Item_details] 
WHERE [POU ITEM] IS NOT NULL 
AND ICD10 IS NOT NULL 
AND datepart(mm,[performdatewtime]) >= 7
--AND SERVICE_CODE = 'UROLOGY' AND ICD10 = 'Z43.6' AND PHYSICIAN = 'KOGAN' AND [POU ITEM] = '10884521007819'
GROUP BY SERVICE_CODE, ICD10,[ICD10 DESCRIPTION], PHYSICIAN, [Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID],
 DATEPART(YYYY,[performdatewtime])
ORDER BY [POU ITEM]

--select count(*) from [Item_details] where len([MHS MFGID]) >50

UPDATE MT_POU_RPT_SUPPLY_COMPARISON_H SET [PHYSICIAN_NAME]=ISNULL([Item_details].SURGE_DESCIPTION_orig,'') FROM MT_POU_RPT_SUPPLY_COMPARISON_H,[Item_details]
WHERE MT_POU_RPT_SUPPLY_COMPARISON_H.PHYSICIAN_ID=[Item_details].PHYSICIAN

--------------------------------







--By PROCEDURE:



--MT_POU_RPT_SUPPLY_COMPARISON
--MT_POU_RPT_SUPPLY_COMPARISON_M
-- DROP TABLE MT_POU_RPT_SUPPLY_COMPARISON_H
-------------------------
ALTER TABLE [Item_details]
ALTER COLUMN [ICD10] [nvarchar](255) NULL
---------------------
--ALTER TABLE MT_POU_RPT_SUPPLY_COMPARISON_M
--ALTER COLUMN PROCEDURE_DESCRIPTION NVARCHAR(254) NULL

-- BY QUARTER

	-- DELETE FROM MT_POU_RPT_SUPPLY_COMPARISON_H (297404)
INSERT INTO MT_POU_RPT_SUPPLY_COMPARISON_H
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[DIAGNOSIS_CODE_TYPE]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[ITEM_GROUP]
,[ITEM_GROUP_DESCRIPTION]
,[ITEM_ID]
,[ITEM_DESCRIPTION]
,[MFR_CATALOG_NO]
,[UNIT_COST]
,[NO_OF_TIMES_ITEM_USED_BY_PHY]
,[PERIOD]
,[YEAR])
SELECT SERVICE_CODE,
--' ' ICD10,' ' [CPT_CODE], 
ISNULL(PROCEDURE_CODE, ' ') PROCEDURE_CODE, ISNULL(proc_descr,' ') PROCEDURE_DESCR , 3 AS 'DIAGNOSIS_CODE_TYPE',
--' ' ICD10_DESCR,' ' [CPT_DESCR], 
ISNULL(PHYSICIAN,' ') PHYSICIAN, ' ' PHYSICIAN_NAME,  
[Group],[Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID], AVG(ISNULL([CURRENTITEMCOST],0)) [CURRENTITEMCOST], ISNULL(SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])),0)  TOTAL_ITEM_QTY ,  
1,
DATEPART(YYYY,[performdatewtime]) [YEAR] 
FROM [Item_details] 
WHERE [POU ITEM] IS NOT NULL 
--AND ICD10 IS NOT NULL 
AND datepart(mm,[performdatewtime]) <= 6
--AND SERVICE_CODE = 'UROLOGY' AND ICD10 = 'Z43.6' AND PHYSICIAN = 'KOGAN' AND [POU ITEM] = '10884521007819'
GROUP BY SERVICE_CODE, PROCEDURE_CODE,[proc_descr], PHYSICIAN, [Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID],
 DATEPART(YYYY,[performdatewtime])
 
UNION

SELECT SERVICE_CODE, 
--' ' ICD10,' ' [CPT_CODE], 
ISNULL(PROCEDURE_CODE, ' ') PROCEDURE_CODE, ISNULL(proc_descr,' ') PROCEDURE_DESCR , 3 AS 'DIAGNOSIS_CODE_TYPE',
--' ' ICD10_DESCR,' ' [CPT_DESCR], 
ISNULL(PHYSICIAN,' ') PHYSICIAN, ' ' PHYSICIAN_NAME,  
[Group],[Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID], AVG(ISNULL([CURRENTITEMCOST],0)) [CURRENTITEMCOST], ISNULL(SUM((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])),0)  TOTAL_ITEM_QTY ,  
2,
DATEPART(YYYY,[performdatewtime]) [YEAR] 
FROM [Item_details] 
WHERE [POU ITEM] IS NOT NULL 
--AND ICD10 IS NOT NULL 
AND datepart(mm,[performdatewtime]) >= 7
--AND SERVICE_CODE = 'UROLOGY' AND ICD10 = 'Z43.6' AND PHYSICIAN = 'KOGAN' AND [POU ITEM] = '10884521007819'
GROUP BY SERVICE_CODE, PROCEDURE_CODE,[proc_descr], PHYSICIAN, [Group], [POU ITEM], [POU DESCRIPTION], [MHS MFGID],
 DATEPART(YYYY,[performdatewtime])
ORDER BY [POU ITEM]


UPDATE MT_POU_RPT_SUPPLY_COMPARISON_H SET [PHYSICIAN_NAME]=ISNULL([Item_details].SURGE_DESCIPTION_orig,'') FROM MT_POU_RPT_SUPPLY_COMPARISON_H,[Item_details]
WHERE MT_POU_RPT_SUPPLY_COMPARISON_H.PHYSICIAN_ID=[Item_details].PHYSICIAN

--------------------------------




