--By ICD:

--TEMP_TAB3_H1_ICD TABLE:contains min max average usage among all physicians

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_TAB3_H1_ICD')
BEGIN
DROP TABLE TEMP_TAB3_H1_ICD
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP1_TAB3_H1_ICD')
BEGIN
DROP TABLE TEMP1_TAB3_H1_ICD
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD
END


  --DELETE FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
--BY ICD
--GYNECOLOGY

-----------------------
------------------------------------------------------------------------------------------------

SELECT  B.SERVICE_CODE , B.ICD10, MIN(AVG_SPEND) MIN_AVG, MAX(AVG_SPEND) MAX_AVG, 
[YEAR] INTO TEMP_TAB3_H1_ICD
FROM (SELECT C.SERVICE_CODE, C.ICD10,  C.PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN,CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details]
			   WHERE datepart(mm,[performdatewtime]) <= 6 and ICD10 is not null		  			
GROUP BY  SERVICE_CODE, ICD10, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]) ) C
GROUP BY  SERVICE_CODE, ICD10, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, ICD10, [YEAR]

-------------------------PHYSICIAN COUNT--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS_DEPT, 
COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES_DEPT,
SERVICE_CODE, ICD10, DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP1_TAB3_H1_ICD
FROM [Item_details]
 WHERE datepart(mm,[performdatewtime]) <= 6 and ICD10 is not null			
GROUP BY  SERVICE_CODE, ICD10, DATEPART(YYYY,[performdatewtime]) 

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD TABLE:contains min max average usage by physician

SELECT C.SERVICE_CODE, PHYSICIAN, SURGE_DESCIPTION_orig, ICD10, [ICD10 DESCRIPTION], COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SUM(TOTAL_SPEND) TOTAL_SPEND,
	   MIN(TOTAL_SPEND) MIN_SPEND, AVG(ISNULL(TOTAL_SPEND,0)) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND, [YEAR] 
	   INTO TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD
FROM (SELECT SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, SURGE_DESCIPTION_orig , CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details]
			  WHERE datepart(mm,[performdatewtime]) <= 6 and ICD10 is not null						 			 
GROUP BY SERVICE_CODE, ICD10,[ICD10 DESCRIPTION], PHYSICIAN,SURGE_DESCIPTION_orig, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PHYSICIAN,SURGE_DESCIPTION_orig, ICD10,[ICD10 DESCRIPTION], [YEAR]


ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD ADD NO_OF_PHYSICIANS_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD ADD NO_OF_PROCEDURES_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD ADD [PER_VAR_TOTAL_SPEND] FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD ADD [LOW_COST_AVG_DEPT] FLOAT

--SET TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.MIN_AVG_ALL_PHYSICIANS = TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.AVG_SPEND - TEMP_TAB3_H1_ICD.MIN_AVG,

UPDATE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD 
SET TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.VARIANCE = ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.AVG_SPEND - TEMP_TAB3_H1_ICD.MIN_AVG),2),
TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.[PER_VAR_TOTAL_SPEND] = CASE WHEN ISNULL(TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.TOTAL_SPEND,0) > 0 THEN (ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.AVG_SPEND - TEMP_TAB3_H1_ICD.MIN_AVG),2) / TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.TOTAL_SPEND) * 100 ELSE 0 END ,
NO_OF_PHYSICIANS_DEPT = TEMP1_TAB3_H1_ICD.NO_OF_PHYSICIANS_DEPT,
NO_OF_PROCEDURES_DEPT = TEMP1_TAB3_H1_ICD.NO_OF_PROCEDURES_DEPT,
[LOW_COST_AVG_DEPT] = TEMP_TAB3_H1_ICD.MIN_AVG
--SELECT ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.AVG_SPEND - TEMP_TAB3_H1_ICD.MIN_AVG),2) VARIANCE , TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.AVG_SPEND , TEMP_TAB3_H1_ICD.MIN_AVG
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD,TEMP_TAB3_H1_ICD,TEMP1_TAB3_H1_ICD
WHERE TEMP_TAB3_H1_ICD.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.[YEAR] = TEMP_TAB3_H1_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.[YEAR] = TEMP1_TAB3_H1_ICD.[YEAR]
AND TEMP1_TAB3_H1_ICD.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.ICD10 = TEMP1_TAB3_H1_ICD.ICD10
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.ICD10 = TEMP_TAB3_H1_ICD.ICD10
AND TEMP1_TAB3_H1_ICD.SERVICE_CODE=TEMP_TAB3_H1_ICD.SERVICE_CODE 
--AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.SERVICE_CODE = 'ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD.ICD10='M17.12'
--------------------------------H2------------------------

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_TAB3_H2_ICD')
BEGIN
DROP TABLE TEMP_TAB3_H2_ICD
END


IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP1_TAB3_H2_ICD')
BEGIN
DROP TABLE TEMP1_TAB3_H2_ICD
END


IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD
END





  --DELETE FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
--BY ICD
--GYNECOLOGY

-----------------------
------------------------------------------------------------------------------------------------

SELECT  B.SERVICE_CODE , B.ICD10, MIN(AVG_SPEND) MIN_AVG, MAX(AVG_SPEND) MAX_AVG, 
[YEAR] INTO TEMP_TAB3_H2_ICD
FROM (SELECT C.SERVICE_CODE, C.ICD10,  C.PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, ICD10, PHYSICIAN,CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details]
			   WHERE datepart(mm,[performdatewtime]) >= 7 and ICD10 is not null		  			
GROUP BY  SERVICE_CODE, ICD10, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]) ) C
GROUP BY  SERVICE_CODE, ICD10, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, ICD10, [YEAR]

-------------------------PHYSICIAN COUNT--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS_DEPT, 
COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES_DEPT,
SERVICE_CODE, ICD10, DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP1_TAB3_H2_ICD
FROM [Item_details]
 WHERE datepart(mm,[performdatewtime]) >= 7 and ICD10 is not null	 			
GROUP BY  SERVICE_CODE, ICD10, DATEPART(YYYY,[performdatewtime]) 

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD TABLE:contains min max average usage by physician

SELECT C.SERVICE_CODE, PHYSICIAN, SURGE_DESCIPTION_orig, ICD10, [ICD10 DESCRIPTION], COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SUM(TOTAL_SPEND) TOTAL_SPEND,
	   MIN(TOTAL_SPEND) MIN_SPEND, AVG(ISNULL(TOTAL_SPEND,0)) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND, [YEAR] 
	   INTO TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD
FROM (SELECT SERVICE_CODE, ICD10, [ICD10 DESCRIPTION], PHYSICIAN, SURGE_DESCIPTION_orig , CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details]
			  WHERE datepart(mm,[performdatewtime]) >= 7 and ICD10 is not null							 			 
GROUP BY SERVICE_CODE, ICD10,[ICD10 DESCRIPTION], PHYSICIAN,SURGE_DESCIPTION_orig, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PHYSICIAN,SURGE_DESCIPTION_orig, ICD10,[ICD10 DESCRIPTION], [YEAR]


ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD ADD NO_OF_PHYSICIANS_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD ADD NO_OF_PROCEDURES_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD ADD [PER_VAR_TOTAL_SPEND] FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD ADD [LOW_COST_AVG_DEPT] FLOAT

--SET TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.MIN_AVG_ALL_PHYSICIANS = TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.AVG_SPEND - TEMP_TAB3_H2_ICD.MIN_AVG,

UPDATE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD 
SET TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.VARIANCE = ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.AVG_SPEND - TEMP_TAB3_H2_ICD.MIN_AVG),2),
TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.[PER_VAR_TOTAL_SPEND] = CASE WHEN ISNULL(TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.TOTAL_SPEND,0) > 0 THEN (ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.AVG_SPEND - TEMP_TAB3_H2_ICD.MIN_AVG),2) / TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.TOTAL_SPEND) * 100 ELSE 0 END ,
NO_OF_PHYSICIANS_DEPT = TEMP1_TAB3_H2_ICD.NO_OF_PHYSICIANS_DEPT,
NO_OF_PROCEDURES_DEPT = TEMP1_TAB3_H2_ICD.NO_OF_PROCEDURES_DEPT,
[LOW_COST_AVG_DEPT] = TEMP_TAB3_H2_ICD.MIN_AVG
--SELECT ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.AVG_SPEND - TEMP_TAB3_H2_ICD.MIN_AVG),2) VARIANCE , TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.AVG_SPEND , TEMP_TAB3_H2_ICD.MIN_AVG
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD,TEMP_TAB3_H2_ICD,TEMP1_TAB3_H2_ICD
WHERE TEMP_TAB3_H2_ICD.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.[YEAR] = TEMP_TAB3_H2_ICD.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.[YEAR] = TEMP1_TAB3_H2_ICD.[YEAR]
AND TEMP1_TAB3_H2_ICD.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.ICD10 = TEMP1_TAB3_H2_ICD.ICD10
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD.ICD10 = TEMP_TAB3_H2_ICD.ICD10
AND TEMP1_TAB3_H2_ICD.SERVICE_CODE=TEMP_TAB3_H2_ICD.SERVICE_CODE 


---INSERT INTO MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON
-- SELECT *  FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H  (3846)
--BY YEAR
DELETE FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
-- WHERE [DIAGNOSIS_CODE_TYPE]=1
INSERT INTO MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[DIAGNOSIS_CODE_TYPE]
,[NO_OF_PROCEDURES]
,[MIN_PROC_COST]
,[MAX_PROC_COST]
,[AVG_PROC_COST]
,[TOTAL_SPEND]
,[PER_VAR_TOTAL_SPEND]
,[PHYSICIAN_RANK]
,[NO_OF_PHY_DEPT]
,[NO_OF_PROCS_DEPT]
,[LOW_COST_AVG_DEPT]
,[MIN_PROC_VARIANCE]
,[EXTENDED_VARIANCE]
,[PERIOD]
,[YEAR])
SELECT SERVICE_CODE, ISNULL(ICD10, ' '),ISNULL(ICD10, ' ') ICD10,ISNULL(PHYSICIAN,' ') PHYSICIAN, '' PHYSICIAN_NAME , --ISNULL([ICD10 DESCRIPTION], ' '),
1 AS 'DIAGNOSIS_CODE_TYPE', 
--ISNULL([ICD10 DESCRIPTION], ' '),' ', 
AVG(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  MIN(ISNULL(MIN_SPEND,0)) MIN_SPEND, MAX(ISNULL(MAX_SPEND,0)) MAX_SPEND, AVG(ISNULL(AVG_SPEND,0)) AVG_SPEND,
ISNULL(SUM(TOTAL_SPEND),0) TOTAL_SPEND, 
SUM([PER_VAR_TOTAL_SPEND]) [PER_VAR_TOTAL_SPEND],
0,
AVG(NO_OF_PHYSICIANS_DEPT) NO_OF_PHYSICIANS_DEPT,
AVG(NO_OF_PROCEDURES_DEPT) NO_OF_PROCEDURES_DEPT,
AVG([LOW_COST_AVG_DEPT]) [LOW_COST_AVG_DEPT],
ROUND(SUM([VARIANCE]),2) [VARIANCE],
ROUND((SUM(ISNULL(NO_OF_PROCEDURES,0)) * SUM([VARIANCE])),2) [EXTENDED_VARIANCE],
1,
[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_H1_ICD
GROUP BY SERVICE_CODE,ICD10,[ICD10 DESCRIPTION],PHYSICIAN, [YEAR]
UNION
SELECT SERVICE_CODE, ISNULL(ICD10, ' '),ISNULL(ICD10, ' ') ICD10,ISNULL(PHYSICIAN,' ') PHYSICIAN, '' PHYSICIAN_NAME , --ISNULL([ICD10 DESCRIPTION], ' '),
1 AS 'DIAGNOSIS_CODE_TYPE', 
--ISNULL([ICD10 DESCRIPTION], ' '),' ', 
AVG(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  MIN(ISNULL(MIN_SPEND,0)) MIN_SPEND, MAX(ISNULL(MAX_SPEND,0)) MAX_SPEND, AVG(ISNULL(AVG_SPEND,0)) AVG_SPEND,
ISNULL(SUM(TOTAL_SPEND),0) TOTAL_SPEND, 
SUM([PER_VAR_TOTAL_SPEND]) [PER_VAR_TOTAL_SPEND],
0,
AVG(NO_OF_PHYSICIANS_DEPT) NO_OF_PHYSICIANS_DEPT,
AVG(NO_OF_PROCEDURES_DEPT) NO_OF_PROCEDURES_DEPT,
AVG([LOW_COST_AVG_DEPT]) [LOW_COST_AVG_DEPT],
ROUND(SUM([VARIANCE]),2) [VARIANCE],
ROUND((SUM(ISNULL(NO_OF_PROCEDURES,0)) * SUM([VARIANCE])),2) [EXTENDED_VARIANCE],
2,
[YEAR]
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_H2_ICD
GROUP BY SERVICE_CODE,ICD10,[ICD10 DESCRIPTION],PHYSICIAN, [YEAR] 





------------------------------------------------------------------------------

ALTER TABLE [Item_details]
ALTER COLUMN PHYSICIAN [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

UPDATE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H SET [PHYSICIAN_NAME] = ISNULL([Item_details].SURGE_DESCIPTION_orig,'') 
FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H,[Item_details]
WHERE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.PHYSICIAN_ID=[Item_details].PHYSICIAN






--By PROCEDURE:


--TEMP_TAB3_H1_PROC TABLE:contains min max average usage among all physicians

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_TAB3_H1_PROC')
BEGIN
DROP TABLE TEMP_TAB3_H1_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP1_TAB3_H1_PROC')
BEGIN
DROP TABLE TEMP1_TAB3_H1_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC
END



--DROP TABLE TEMP_TAB3_H1_PROC
--DROP TABLE TEMP1_TAB3_H1_PROC
--DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC

  --DELETE FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
--BY ICD
--GYNECOLOGY

-----------------------
------------------------------------------------------------------------------------------------

SELECT  B.SERVICE_CODE , B.PROCEDURE_CODE, MIN(AVG_SPEND) MIN_AVG, MAX(AVG_SPEND) MAX_AVG, 
[YEAR] INTO TEMP_TAB3_H1_PROC
FROM (SELECT C.SERVICE_CODE, C.PROCEDURE_CODE,  C.PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN,CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details]
			   WHERE datepart(mm,[performdatewtime]) <= 6 		  			
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]) ) C
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, PROCEDURE_CODE, [YEAR]

-------------------------PHYSICIAN COUNT--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS_DEPT, 
COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES_DEPT,
SERVICE_CODE, PROCEDURE_CODE, DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP1_TAB3_H1_PROC
FROM [Item_details]
 WHERE datepart(mm,[performdatewtime]) <= 6 			
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, DATEPART(YYYY,[performdatewtime]) 

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC TABLE:contains min max average usage by physician

SELECT C.SERVICE_CODE, PHYSICIAN, SURGE_DESCIPTION_orig, PROCEDURE_CODE, proc_descr, COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SUM(TOTAL_SPEND) TOTAL_SPEND,
	   MIN(TOTAL_SPEND) MIN_SPEND, AVG(ISNULL(TOTAL_SPEND,0)) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND, [YEAR] 
	   INTO TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, SURGE_DESCIPTION_orig , CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details]
			  WHERE datepart(mm,[performdatewtime]) <= 6 						 			 
GROUP BY SERVICE_CODE, PROCEDURE_CODE,proc_descr, PHYSICIAN,SURGE_DESCIPTION_orig, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PHYSICIAN,SURGE_DESCIPTION_orig, PROCEDURE_CODE,proc_descr, [YEAR]


ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC ADD NO_OF_PHYSICIANS_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC ADD NO_OF_PROCEDURES_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC ADD [PER_VAR_TOTAL_SPEND] FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC ADD [LOW_COST_AVG_DEPT] FLOAT

--SET TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.MIN_AVG_ALL_PHYSICIANS = TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.AVG_SPEND - TEMP_TAB3_H1_PROC.MIN_AVG,

UPDATE TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC 
SET TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.VARIANCE = ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.AVG_SPEND - TEMP_TAB3_H1_PROC.MIN_AVG),2),
TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.[PER_VAR_TOTAL_SPEND] = CASE WHEN ISNULL(TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.TOTAL_SPEND,0) > 0 THEN (ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.AVG_SPEND - TEMP_TAB3_H1_PROC.MIN_AVG),2) / TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.TOTAL_SPEND) * 100 ELSE 0 END ,
NO_OF_PHYSICIANS_DEPT = TEMP1_TAB3_H1_PROC.NO_OF_PHYSICIANS_DEPT,
NO_OF_PROCEDURES_DEPT = TEMP1_TAB3_H1_PROC.NO_OF_PROCEDURES_DEPT,
[LOW_COST_AVG_DEPT] = TEMP_TAB3_H1_PROC.MIN_AVG
--SELECT ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.AVG_SPEND - TEMP_TAB3_H1_PROC.MIN_AVG),2) VARIANCE , TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.AVG_SPEND , TEMP_TAB3_H1_PROC.MIN_AVG
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC,TEMP_TAB3_H1_PROC,TEMP1_TAB3_H1_PROC
WHERE TEMP_TAB3_H1_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.[YEAR] = TEMP_TAB3_H1_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.[YEAR] = TEMP1_TAB3_H1_PROC.[YEAR]
AND TEMP1_TAB3_H1_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.PROCEDURE_CODE = TEMP1_TAB3_H1_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.PROCEDURE_CODE = TEMP_TAB3_H1_PROC.PROCEDURE_CODE
AND TEMP1_TAB3_H1_PROC.SERVICE_CODE=TEMP_TAB3_H1_PROC.SERVICE_CODE 
--AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.SERVICE_CODE = 'ORTHOPEDICS' AND TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC.PROCEDURE_CODE='M17.12'
--------------------------------H2------------------------

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_TAB3_H2_PROC')
BEGIN
DROP TABLE TEMP_TAB3_H2_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP1_TAB3_H2_PROC')
BEGIN
DROP TABLE TEMP1_TAB3_H2_PROC
END

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC')
BEGIN
DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC
END





--DROP TABLE TEMP_TAB3_H2_PROC
--DROP TABLE TEMP1_TAB3_H2_PROC
--DROP TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC

  --DELETE FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
--BY ICD
--GYNECOLOGY

-----------------------
------------------------------------------------------------------------------------------------

SELECT  B.SERVICE_CODE , B.PROCEDURE_CODE, MIN(AVG_SPEND) MIN_AVG, MAX(AVG_SPEND) MAX_AVG, 
[YEAR] INTO TEMP_TAB3_H2_PROC
FROM (SELECT C.SERVICE_CODE, C.PROCEDURE_CODE,  C.PHYSICIAN, AVG(C.TOTAL_SPEND) AVG_SPEND, C.[YEAR]
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN,CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			  FROM [Item_details]
			   WHERE datepart(mm,[performdatewtime]) >= 7 		  			
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, CASEID, DATEPART(YYYY,[performdatewtime]) ) C
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, PHYSICIAN, [YEAR]) B
GROUP BY SERVICE_CODE, PROCEDURE_CODE, [YEAR]

-------------------------PHYSICIAN COUNT--------------------

SELECT COUNT(DISTINCT(PHYSICIAN)) NO_OF_PHYSICIANS_DEPT, 
COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES_DEPT,
SERVICE_CODE, PROCEDURE_CODE, DATEPART(YYYY,[performdatewtime]) [YEAR] 
INTO TEMP1_TAB3_H2_PROC
FROM [Item_details]
 WHERE datepart(mm,[performdatewtime]) >= 7 	 			
GROUP BY  SERVICE_CODE, PROCEDURE_CODE, DATEPART(YYYY,[performdatewtime]) 

-------------------------
--TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC TABLE:contains min max average usage by physician

SELECT C.SERVICE_CODE, PHYSICIAN, SURGE_DESCIPTION_orig, PROCEDURE_CODE, proc_descr, COUNT(DISTINCT(CASEID)) NO_OF_PROCEDURES, SUM(TOTAL_SPEND) TOTAL_SPEND,
	   MIN(TOTAL_SPEND) MIN_SPEND, AVG(ISNULL(TOTAL_SPEND,0)) AVG_SPEND, MAX(TOTAL_SPEND) MAX_SPEND, [YEAR] 
	   INTO TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC
FROM (SELECT SERVICE_CODE, PROCEDURE_CODE, proc_descr, PHYSICIAN, SURGE_DESCIPTION_orig , CASEID, 
	 SUM(((([TOTALCASEPICKQTY] + [TOTAL IN ROOM QTY] + [TOTAL WASTED])) - ([TOTALRETURNED])) * [CURRENTITEMCOST]) TOTAL_SPEND, 
			 DATEPART(YYYY,[performdatewtime]) [YEAR]
			 FROM [Item_details]
			  WHERE datepart(mm,[performdatewtime]) >= 7 							 			 
GROUP BY SERVICE_CODE, PROCEDURE_CODE,proc_descr, PHYSICIAN,SURGE_DESCIPTION_orig, CASEID, DATEPART(YYYY,[performdatewtime])) C
GROUP BY SERVICE_CODE, PHYSICIAN,SURGE_DESCIPTION_orig, PROCEDURE_CODE,proc_descr, [YEAR]


ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC ADD VARIANCE FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC ADD NO_OF_PHYSICIANS_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC ADD NO_OF_PROCEDURES_DEPT INT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC ADD [PER_VAR_TOTAL_SPEND] FLOAT
ALTER TABLE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC ADD [LOW_COST_AVG_DEPT] FLOAT

--SET TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.MIN_AVG_ALL_PHYSICIANS = TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.AVG_SPEND - TEMP_TAB3_H2_PROC.MIN_AVG,

UPDATE TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC 
SET TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.VARIANCE = ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.AVG_SPEND - TEMP_TAB3_H2_PROC.MIN_AVG),2),
TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.[PER_VAR_TOTAL_SPEND] = CASE WHEN ISNULL(TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.TOTAL_SPEND,0) > 0 THEN (ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.AVG_SPEND - TEMP_TAB3_H2_PROC.MIN_AVG),2) / TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.TOTAL_SPEND) * 100 ELSE 0 END ,
NO_OF_PHYSICIANS_DEPT = TEMP1_TAB3_H2_PROC.NO_OF_PHYSICIANS_DEPT,
NO_OF_PROCEDURES_DEPT = TEMP1_TAB3_H2_PROC.NO_OF_PROCEDURES_DEPT,
[LOW_COST_AVG_DEPT] = TEMP_TAB3_H2_PROC.MIN_AVG
--SELECT ROUND((TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.AVG_SPEND - TEMP_TAB3_H2_PROC.MIN_AVG),2) VARIANCE , TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.AVG_SPEND , TEMP_TAB3_H2_PROC.MIN_AVG
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC,TEMP_TAB3_H2_PROC,TEMP1_TAB3_H2_PROC
WHERE TEMP_TAB3_H2_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.[YEAR] = TEMP_TAB3_H2_PROC.[YEAR]
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.[YEAR] = TEMP1_TAB3_H2_PROC.[YEAR]
AND TEMP1_TAB3_H2_PROC.SERVICE_CODE=TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.SERVICE_CODE 
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.PROCEDURE_CODE = TEMP1_TAB3_H2_PROC.PROCEDURE_CODE
AND TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC.PROCEDURE_CODE = TEMP_TAB3_H2_PROC.PROCEDURE_CODE
AND TEMP1_TAB3_H2_PROC.SERVICE_CODE=TEMP_TAB3_H2_PROC.SERVICE_CODE 


---INSERT INTO MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON
-- SELECT *  FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H  (3846)
--BY YEAR
DELETE FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
INSERT INTO MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
 ([SPECIALTY_CODE]
,[DIAGNOSIS_CODE]
,[DIAGNOSIS_DESCRIPTION]
,[PHYSICIAN_ID]
,[PHYSICIAN_NAME]
,[DIAGNOSIS_CODE_TYPE]
,[NO_OF_PROCEDURES]
,[MIN_PROC_COST]
,[MAX_PROC_COST]
,[AVG_PROC_COST]
,[TOTAL_SPEND]
,[PER_VAR_TOTAL_SPEND]
,[PHYSICIAN_RANK]
,[NO_OF_PHY_DEPT]
,[NO_OF_PROCS_DEPT]
,[LOW_COST_AVG_DEPT]
,[MIN_PROC_VARIANCE]
,[EXTENDED_VARIANCE]
,[PERIOD]
,[YEAR])
SELECT SERVICE_CODE, 
--' ',' ', 
ISNULL(PROCEDURE_CODE, ' ') PROCEDURE_CODE,ISNULL(proc_descr, ' '),ISNULL(PHYSICIAN,' ') PHYSICIAN, '' PHYSICIAN_NAME , 
3 AS 'DIAGNOSIS_CODE_TYPE', 
--' ',' ', 
AVG(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  MIN(ISNULL(MIN_SPEND,0)) MIN_SPEND, MAX(ISNULL(MAX_SPEND,0)) MAX_SPEND, AVG(ISNULL(AVG_SPEND,0)) AVG_SPEND,
ISNULL(SUM(TOTAL_SPEND),0) TOTAL_SPEND, 
SUM([PER_VAR_TOTAL_SPEND]) [PER_VAR_TOTAL_SPEND],
0,
AVG(NO_OF_PHYSICIANS_DEPT) NO_OF_PHYSICIANS_DEPT,
AVG(NO_OF_PROCEDURES_DEPT) NO_OF_PROCEDURES_DEPT,
AVG([LOW_COST_AVG_DEPT]) [LOW_COST_AVG_DEPT],
ROUND(SUM([VARIANCE]),2) [VARIANCE],
ROUND((SUM(ISNULL(NO_OF_PROCEDURES,0)) * SUM([VARIANCE])),2) [EXTENDED_VARIANCE],
1,
[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_H1_PROC
GROUP BY SERVICE_CODE,PROCEDURE_CODE,proc_descr,PHYSICIAN, [YEAR]
UNION
SELECT SERVICE_CODE, 
--' ',' ', 
ISNULL(PROCEDURE_CODE, ' ') PROCEDURE_CODE,ISNULL(proc_descr, ' '),ISNULL(PHYSICIAN,' ') PHYSICIAN, '' PHYSICIAN_NAME , 
3 AS 'DIAGNOSIS_CODE_TYPE', 
--' ',' ', 
AVG(ISNULL(NO_OF_PROCEDURES,0)) NO_OF_PROCEDURES,  MIN(ISNULL(MIN_SPEND,0)) MIN_SPEND, MAX(ISNULL(MAX_SPEND,0)) MAX_SPEND, AVG(ISNULL(AVG_SPEND,0)) AVG_SPEND,
ISNULL(SUM(TOTAL_SPEND),0) TOTAL_SPEND, 
SUM([PER_VAR_TOTAL_SPEND]) [PER_VAR_TOTAL_SPEND],
0,
AVG(NO_OF_PHYSICIANS_DEPT) NO_OF_PHYSICIANS_DEPT,
AVG(NO_OF_PROCEDURES_DEPT) NO_OF_PROCEDURES_DEPT,
AVG([LOW_COST_AVG_DEPT]) [LOW_COST_AVG_DEPT],
ROUND(SUM([VARIANCE]),2) [VARIANCE],
ROUND((SUM(ISNULL(NO_OF_PROCEDURES,0)) * SUM([VARIANCE])),2) [EXTENDED_VARIANCE],
2,
[YEAR] 
FROM TEMP_PHYSICIAN_AVERAGE_TAB3_H2_PROC
GROUP BY SERVICE_CODE,PROCEDURE_CODE,proc_descr,PHYSICIAN, [YEAR] 

------------------------------------------------------------------------------
-------to update RANK 3rd tab--------------
-- DROP TABLE TEMP_PHY_RANK_DATA_H
SELECT SPECIALTY_CODE, DIAGNOSIS_CODE, PHYSICIAN_ID, [AVG_PROC_COST], [YEAR],[PERIOD], DIAGNOSIS_CODE_TYPE
, DENSE_RANK() OVER(partition by SPECIALTY_CODE, DIAGNOSIS_CODE,[PERIOD], [YEAR] ORDER BY [AVG_PROC_COST] ASC) AS [RANK] 
INTO TEMP_PHY_RANK_DATA_H
FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H 
where  DIAGNOSIS_CODE_TYPE=3
order by PHYSICIAN_ID

UPDATE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H
SET [PHYSICIAN_RANK] = TEMP_PHY_RANK_DATA_H.[RANK]
FROM  MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H, TEMP_PHY_RANK_DATA_H
WHERE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.SPECIALTY_CODE = TEMP_PHY_RANK_DATA_H.SPECIALTY_CODE
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.DIAGNOSIS_CODE = TEMP_PHY_RANK_DATA_H.DIAGNOSIS_CODE
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.PHYSICIAN_ID = TEMP_PHY_RANK_DATA_H.PHYSICIAN_ID
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.[YEAR] = TEMP_PHY_RANK_DATA_H.[YEAR]
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.[PERIOD] = TEMP_PHY_RANK_DATA_H.[PERIOD]
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.DIAGNOSIS_CODE_TYPE = TEMP_PHY_RANK_DATA_H.DIAGNOSIS_CODE_TYPE
AND MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.DIAGNOSIS_CODE_TYPE=3

-------------------

ALTER TABLE [Item_details]
ALTER COLUMN PHYSICIAN [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL

UPDATE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H SET [PHYSICIAN_NAME] = ISNULL([Item_details].SURGE_DESCIPTION_orig,'') 
FROM MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H,[Item_details]
WHERE MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H.PHYSICIAN_ID=[Item_details].PHYSICIAN


pdate MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H set PHYSICIAN_NAME=[ATPAR_MT].[MT_POU_PHYSICIAN].FIRST_NAME
+' ' + [ATPAR_MT].[MT_POU_PHYSICIAN].MIDDLE_INITIAL + ' '+[ATPAR_MT].[MT_POU_PHYSICIAN].LAST_NAME
from MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H ,[ATPAR_MT].[MT_POU_PHYSICIAN]
where MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H .PHYSICIAN_ID=[ATPAR_MT].[MT_POU_PHYSICIAN].PHYSICIAN_ID and MT_POU_RPT_EXTENDED_VARIANCE_BY_SURGEON_H .PHYSICIAN_NAME = ''
