'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3623.
'


'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Web.Services.WebServiceBindingAttribute(Name:="AlertTrackIFServiceSoap", [Namespace]:="http://tempuri.org/")> _
Partial Public Class RecallService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

    Private GetLatestAlertsOperationCompleted As System.Threading.SendOrPostCallback

    Private useDefaultCredentialsSetExplicitly As Boolean

    '''<remarks/>
    Public Sub New()
        MyBase.New()
        Me.Url = RecallServiceUrl
    End Sub

    Public Shadows Property Url() As String
        Get
            Return MyBase.Url
        End Get
        Set(ByVal value As String)
            If (((Me.IsLocalFileSystemWebService(MyBase.Url) = True) _
                        AndAlso (Me.useDefaultCredentialsSetExplicitly = False)) _
                        AndAlso (Me.IsLocalFileSystemWebService(value) = False)) Then
                MyBase.UseDefaultCredentials = False
            End If
            MyBase.Url = value
        End Set
    End Property

    Public Shadows Property UseDefaultCredentials() As Boolean
        Get
            Return MyBase.UseDefaultCredentials
        End Get
        Set(ByVal value As Boolean)
            MyBase.UseDefaultCredentials = value
            Me.useDefaultCredentialsSetExplicitly = True
        End Set
    End Property

    '''<remarks/>
    Public Event GetLatestAlertsCompleted As GetLatestAlertsCompletedEventHandler

    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLatestAlerts", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
    Public Function GetLatestAlerts(ByVal pInputParams As String, ByRef pOutputParams As System.Data.DataSet) As Long
        Dim results() As Object = Me.Invoke("GetLatestAlerts", New Object() {pInputParams})
        pOutputParams = CType(results(1), System.Data.DataSet)
        Return CType(results(0), Long)
    End Function

    '''<remarks/>
    Public Overloads Sub GetLatestAlertsAsync(ByVal pInputParams As String)
        Me.GetLatestAlertsAsync(pInputParams, Nothing)
    End Sub

    '''<remarks/>
    Public Overloads Sub GetLatestAlertsAsync(ByVal pInputParams As String, ByVal userState As Object)
        If (Me.GetLatestAlertsOperationCompleted Is Nothing) Then
            Me.GetLatestAlertsOperationCompleted = AddressOf Me.OnGetLatestAlertsOperationCompleted
        End If
        Me.InvokeAsync("GetLatestAlerts", New Object() {pInputParams}, Me.GetLatestAlertsOperationCompleted, userState)
    End Sub

    Private Sub OnGetLatestAlertsOperationCompleted(ByVal arg As Object)
        If (Not (Me.GetLatestAlertsCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent GetLatestAlertsCompleted(Me, New GetLatestAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub

    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub

    Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
        If ((url Is Nothing) _
                    OrElse (url Is String.Empty)) Then
            Return False
        End If
        Dim wsUri As System.Uri = New System.Uri(url)
        If ((wsUri.Port >= 1024) _
                    AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
            Return True
        End If
        Return False
    End Function
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")> _
Public Delegate Sub GetLatestAlertsCompletedEventHandler(ByVal sender As Object, ByVal e As GetLatestAlertsCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code")> _
Partial Public Class GetLatestAlertsCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs

    Private results() As Object

    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub

    '''<remarks/>
    Public ReadOnly Property Result() As Long
        Get
            Me.RaiseExceptionIfNecessary()
            Return CType(Me.results(0), Long)
        End Get
    End Property

    '''<remarks/>
    Public ReadOnly Property pOutputParams() As System.Data.DataSet
        Get
            Me.RaiseExceptionIfNecessary()
            Return CType(Me.results(1), System.Data.DataSet)
        End Get
    End Property
End Class

